// Recettes supplémentaires à fusionner
import type { Recipe } from '../components/RecipesScreen';

export const additionalRecipes: Recipe[] = [
  {
    id: 'new-27',
    name: 'Soupe à l\'Oignon Gratinée',
    image: 'https://images.unsplash.com/photo-1549203438-a7696aed4dac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVuY2glMjBvbmlvbiUyMHNvdXB8ZW58MXx8fHwxNzYyMzkyMTAxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Oignons', quantity: '6' },
      { item: 'Bouillon de bœuf', quantity: '1L' },
      { item: 'Vin blanc', quantity: '100ml' },
      { item: 'Gruyère râpé', quantity: '200g' },
      { item: 'Pain', quantity: '8 tranches' },
      { item: 'Beurre', quantity: '40g' },
      { item: 'Thym', quantity: '2 branches' },
    ],
    steps: [
      'Émincer les oignons finement.',
      'Faire caraméliser dans le beurre 30 minutes.',
      'Déglacer au vin blanc.',
      'Ajouter le bouillon et le thym.',
      'Mijoter 30 minutes.',
      'Verser dans des bols à gratiner.',
      'Ajouter pain et gruyère, gratiner au four.',
    ],
  },
  {
    id: 'new-28',
    name: 'Œufs Bénédictine',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlZ2dzJTIwYmVuZWRpY3R8ZW58MXx8fHwxNzYyNDEzNTEzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    difficulty: 'Moyen',
    category: 'Américain',
    ingredients: [
      { item: 'Œufs', quantity: '4' },
      { item: 'Muffins anglais', quantity: '2' },
      { item: 'Bacon', quantity: '4 tranches' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Jaunes d\'œufs', quantity: '3' },
      { item: 'Citron', quantity: '1' },
      { item: 'Vinaigre blanc', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Préparer la sauce hollandaise : monter beurre et jaunes au bain-marie.',
      'Ajouter le jus de citron.',
      'Griller les muffins et faire cuire le bacon.',
      'Pocher les œufs dans l\'eau vinaigrée.',
      'Assembler : muffin, bacon, œuf poché.',
      'Napper de sauce hollandaise.',
      'Servir immédiatement.',
    ],
  },
  {
    id: 'new-29',
    name: 'Pad Thaï',
    image: 'https://images.unsplash.com/photo-1637806930600-37fa8892069d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWQlMjB0aGFpfGVufDF8fHx8MTc2MjMxNzY5Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Nouilles de riz', quantity: '300g' },
      { item: 'Crevettes', quantity: '300g' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Sauce soja', quantity: '3 c. à soupe' },
      { item: 'Sauce de poisson', quantity: '2 c. à soupe' },
      { item: 'Cacahuètes', quantity: '50g' },
      { item: 'Pousses de soja', quantity: '100g' },
      { item: 'Citron vert', quantity: '2' },
    ],
    steps: [
      'Faire tremper les nouilles 30 minutes.',
      'Faire sauter les crevettes.',
      'Ajouter les œufs battus.',
      'Incorporer les nouilles égouttées.',
      'Ajouter sauces soja et poisson.',
      'Mélanger avec pousses de soja.',
      'Servir avec cacahuètes et citron vert.',
    ],
  },
];
