// Collection ÉPIQUE finale - 100 recettes supplémentaires !
import type { Recipe } from '../components/RecipesScreen';

export const epicRecipes: Recipe[] = [
  // 100 recettes encore différentes pour maximiser le choix
  { id: 'epic-1', name: 'Soupe à l\'Ail', image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 30, servings: 4, difficulty: 'Facile', category: 'Espagnol', ingredients: [{ item: 'Ail', quantity: '20 gousses' }, { item: 'Pain', quantity: '200g' }, { item: 'Bouillon', quantity: '1L' }, { item: 'Paprika', quantity: '1 c. à café' }], steps: ['Faire revenir l\'ail.', 'Ajouter pain et bouillon.', 'Mijoter 25 min.', 'Mixer.'] },
  { id: 'epic-2', name: 'Fricassée de Champignons', image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 20, servings: 4, difficulty: 'Facile', category: 'Français', ingredients: [{ item: 'Champignons', quantity: '600g' }, { item: 'Ail', quantity: '3 gousses' }, { item: 'Persil', quantity: '1 bouquet' }, { item: 'Beurre', quantity: '50g' }], steps: ['Faire sauter les champignons.', 'Ajouter ail et persil.', 'Servir chaud.'] },
  { id: 'epic-3', name: 'Tarte Tatin Ananas', image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 35, servings: 8, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Ananas', quantity: '1' }, { item: 'Pâte feuilletée', quantity: '1' }, { item: 'Sucre', quantity: '150g' }, { item: 'Beurre', quantity: '80g' }], steps: ['Caraméliser l\'ananas.', 'Couvrir de pâte.', 'Cuire 35 min.', 'Démouler.'] },
  { id: 'epic-4', name: 'Salade Waldorf', image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 0, servings: 4, difficulty: 'Facile', category: 'Américain', ingredients: [{ item: 'Pommes', quantity: '3' }, { item: 'Céleri', quantity: '3 branches' }, { item: 'Noix', quantity: '100g' }, { item: 'Mayonnaise', quantity: '150ml' }], steps: ['Couper pommes et céleri.', 'Mélanger avec noix.', 'Assaisonner de mayonnaise.'] },
  { id: 'epic-5', name: 'Buns à la Cannelle', image: 'https://images.unsplash.com/photo-1618667060775-1fe102237f94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 120, cookTime: 25, servings: 12, difficulty: 'Moyen', category: 'Scandinave', ingredients: [{ item: 'Farine', quantity: '500g' }, { item: 'Beurre', quantity: '150g' }, { item: 'Cannelle', quantity: '3 c. à soupe' }, { item: 'Sucre', quantity: '200g' }], steps: ['Préparer une pâte levée.', 'Garnir de beurre-cannelle-sucre.', 'Rouler et trancher.', 'Cuire 25 min.'] },
  
  // 95 autres recettes variées
  { id: 'epic-6', name: 'Gnocchi à la Romaine', image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 25, servings: 6, difficulty: 'Moyen', category: 'Italien', ingredients: [{ item: 'Semoule', quantity: '250g' }, { item: 'Lait', quantity: '1L' }, { item: 'Parmesan', quantity: '150g' }, { item: 'Beurre', quantity: '80g' }], steps: ['Cuire semoule dans lait.', 'Former des disques.', 'Gratiner au four.'] },
  { id: 'epic-7', name: 'Pot-de-Crème Vanille', image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 40, servings: 6, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Crème', quantity: '500ml' }, { item: 'Jaunes d\'œufs', quantity: '6' }, { item: 'Sucre', quantity: '100g' }, { item: 'Vanille', quantity: '1 gousse' }], steps: ['Mélanger crème, jaunes et sucre.', 'Cuire au bain-marie.', 'Réfrigérer.'] },
  { id: 'epic-8', name: 'Pastilla au Poulet', image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 60, cookTime: 40, servings: 8, difficulty: 'Difficile', category: 'Maghrébin', ingredients: [{ item: 'Poulet', quantity: '1kg' }, { item: 'Feuilles brick', quantity: '12' }, { item: 'Amandes', quantity: '200g' }, { item: 'Cannelle', quantity: '2 c. à soupe' }, { item: 'Sucre glace', quantity: '100g' }], steps: ['Cuire le poulet aux épices.', 'Monter en couches avec brick.', 'Cuire au four.', 'Saupoudrer de sucre glace.'] },
  { id: 'epic-9', name: 'Salade de Pommes de Terre', image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 20, servings: 6, difficulty: 'Facile', category: 'Français', ingredients: [{ item: 'Pommes de terre', quantity: '1kg' }, { item: 'Oignons', quantity: '2' }, { item: 'Cornichons', quantity: '100g' }, { item: 'Mayonnaise', quantity: '200ml' }], steps: ['Cuire les pommes de terre.', 'Mélanger avec tous ingrédients.', 'Servir frais.'] },
  { id: 'epic-10', name: 'Tarte au Sucre', image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 25, servings: 8, difficulty: 'Facile', category: 'Belge', ingredients: [{ item: 'Pâte levée', quantity: '1' }, { item: 'Cassonade', quantity: '200g' }, { item: 'Crème fraîche', quantity: '100ml' }, { item: 'Vergeoise', quantity: '50g' }], steps: ['Étaler la pâte.', 'Parsemer de sucre et crème.', 'Cuire 25 min.'] },
  
  { id: 'epic-11', name: 'Poulet Sauce Crémeuse', image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 30, servings: 4, difficulty: 'Facile', category: 'Français', ingredients: [{ item: 'Poulet', quantity: '600g' }, { item: 'Champignons', quantity: '200g' }, { item: 'Crème', quantity: '250ml' }, { item: 'Vin blanc', quantity: '100ml' }], steps: ['Faire dorer le poulet.', 'Ajouter champignons.', 'Incorporer crème et vin.', 'Mijoter 20 min.'] },
  { id: 'epic-12', name: 'Aumônières de Fruits', image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 15, servings: 6, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Crêpes', quantity: '6' }, { item: 'Fruits', quantity: '400g' }, { item: 'Crème pâtissière', quantity: '200g' }, { item: 'Sucre glace', quantity: '50g' }], steps: ['Garnir crêpes de fruits et crème.', 'Fermer en aumônière.', 'Saupoudrer de sucre glace.'] },
  { id: 'epic-13', name: 'Houmous Rouge', image: 'https://images.unsplash.com/photo-1588776814546-daab30f310ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 0, servings: 6, difficulty: 'Facile', category: 'Libanais', ingredients: [{ item: 'Pois chiches', quantity: '400g' }, { item: 'Poivrons rouges', quantity: '2' }, { item: 'Tahini', quantity: '3 c. à soupe' }, { item: 'Citron', quantity: '2' }], steps: ['Griller les poivrons.', 'Mixer avec pois chiches et tahini.', 'Assaisonner.'] },
  { id: 'epic-14', name: 'Poêlée Méditerranéenne', image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 20, servings: 4, difficulty: 'Facile', category: 'Méditerranéen', ingredients: [{ item: 'Aubergines', quantity: '2' }, { item: 'Courgettes', quantity: '2' }, { item: 'Tomates', quantity: '4' }, { item: 'Olives', quantity: '100g' }], steps: ['Faire revenir tous les légumes.', 'Ajouter les olives.', 'Servir chaud.'] },
  { id: 'epic-15', name: 'Tarte Bourdaloue Poires', image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 40, servings: 8, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Pâte sablée', quantity: '1' }, { item: 'Poires', quantity: '6' }, { item: 'Crème d\'amandes', quantity: '300g' }, { item: 'Amandes effilées', quantity: '50g' }], steps: ['Étaler la pâte.', 'Ajouter crème et poires.', 'Parsemer d\'amandes.', 'Cuire 40 min.'] },
  
  { id: 'epic-16', name: 'Soupe Harira', image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 60, servings: 8, difficulty: 'Moyen', category: 'Maghrébin', ingredients: [{ item: 'Agneau', quantity: '400g' }, { item: 'Pois chiches', quantity: '300g' }, { item: 'Lentilles', quantity: '200g' }, { item: 'Tomates', quantity: '400g' }], steps: ['Faire revenir l\'agneau.', 'Ajouter légumineuses.', 'Mijoter 50 min.'] },
  { id: 'epic-17', name: 'Millefeuille Vanille', image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 60, cookTime: 25, servings: 6, difficulty: 'Difficile', category: 'Dessert', ingredients: [{ item: 'Pâte feuilletée', quantity: '500g' }, { item: 'Crème pâtissière', quantity: '600ml' }, { item: 'Fondant', quantity: '200g' }], steps: ['Cuire la pâte.', 'Monter avec crème.', 'Glacer le dessus.'] },
  { id: 'epic-18', name: 'Pâtes Cacio e Pepe', image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 10, cookTime: 12, servings: 4, difficulty: 'Moyen', category: 'Italien', ingredients: [{ item: 'Spaghetti', quantity: '400g' }, { item: 'Pecorino', quantity: '150g' }, { item: 'Poivre noir', quantity: '2 c. à soupe' }], steps: ['Cuire les pâtes.', 'Mélanger avec pecorino et poivre.', 'Ajouter eau de cuisson.'] },
  { id: 'epic-19', name: 'Salade de Haricots Verts', image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 10, servings: 4, difficulty: 'Facile', category: 'Salade', ingredients: [{ item: 'Haricots verts', quantity: '500g' }, { item: 'Tomates', quantity: '3' }, { item: 'Échalotes', quantity: '2' }, { item: 'Vinaigrette', quantity: '6 c. à soupe' }], steps: ['Cuire les haricots.', 'Mélanger avec tomates et échalotes.', 'Assaisonner.'] },
  { id: 'epic-20', name: 'Tarte Fine Pommes', image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 25, servings: 6, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Pâte feuilletée', quantity: '1' }, { item: 'Pommes', quantity: '4' }, { item: 'Sucre', quantity: '50g' }, { item: 'Beurre', quantity: '30g' }], steps: ['Trancher les pommes finement.', 'Disposer sur la pâte.', 'Saupoudrer de sucre.', 'Cuire 25 min.'] },
  
  // Suite avec 80 recettes supplémentaires...
  { id: 'epic-21', name: 'Wraps Végétariens', image: 'https://images.unsplash.com/photo-1626200419455-0348c232b193?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 0, servings: 4, difficulty: 'Facile', category: 'Végétarien', ingredients: [{ item: 'Tortillas', quantity: '4' }, { item: 'Houmous', quantity: '200g' }, { item: 'Légumes', quantity: '400g' }, { item: 'Feta', quantity: '100g' }], steps: ['Tartiner de houmous.', 'Garnir de légumes et feta.', 'Rouler et servir.'] },
  { id: 'epic-22', name: 'Clafoutis Abricots', image: 'https://images.unsplash.com/photo-1565695472822-c7ba1e11c5c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 40, servings: 8, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Abricots', quantity: '600g' }, { item: 'Farine', quantity: '100g' }, { item: 'Œufs', quantity: '4' }, { item: 'Sucre', quantity: '100g' }], steps: ['Disposer les abricots.', 'Verser la pâte.', 'Cuire 40 min.'] },
  { id: 'epic-23', name: 'Bœuf Lok Lak', image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 15, servings: 4, difficulty: 'Moyen', category: 'Asiatique', ingredients: [{ item: 'Bœuf', quantity: '600g' }, { item: 'Sauce soja', quantity: '4 c. à soupe' }, { item: 'Sucre', quantity: '2 c. à soupe' }, { item: 'Citron', quantity: '2' }], steps: ['Faire mariner le bœuf.', 'Faire sauter rapidement.', 'Servir avec riz et citron.'] },
  { id: 'epic-24', name: 'Velouté de Chou-Fleur', image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 25, servings: 6, difficulty: 'Facile', category: 'Soupe', ingredients: [{ item: 'Chou-fleur', quantity: '1' }, { item: 'Pomme de terre', quantity: '1' }, { item: 'Bouillon', quantity: '1L' }, { item: 'Crème', quantity: '100ml' }], steps: ['Cuire chou-fleur et pomme de terre.', 'Mixer avec bouillon.', 'Ajouter crème.'] },
  { id: 'epic-25', name: 'Paris-Brest', image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 45, cookTime: 30, servings: 8, difficulty: 'Difficile', category: 'Dessert', ingredients: [{ item: 'Pâte à choux', quantity: '250g' }, { item: 'Crème mousseline pralinée', quantity: '400g' }, { item: 'Amandes', quantity: '50g' }], steps: ['Former une couronne.', 'Cuire 30 min.', 'Garnir de crème pralinée.'] },
  
  { id: 'epic-26', name: 'Poulet Yassa Sénégalais', image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 120, cookTime: 45, servings: 6, difficulty: 'Moyen', category: 'Africain', ingredients: [{ item: 'Poulet', quantity: '1.5kg' }, { item: 'Oignons', quantity: '6' }, { item: 'Citrons', quantity: '4' }, { item: 'Moutarde', quantity: '3 c. à soupe' }], steps: ['Faire mariner le poulet 2h.', 'Caraméliser les oignons.', 'Cuire le poulet 45 min.'] },
  { id: 'epic-27', name: 'Beignets de Fleurs de Courgette', image: 'https://images.unsplash.com/photo-1619546952812-16f4c7b0fd6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 15, servings: 4, difficulty: 'Moyen', category: 'Italien', ingredients: [{ item: 'Fleurs de courgette', quantity: '12' }, { item: 'Farine', quantity: '150g' }, { item: 'Eau gazeuse', quantity: '200ml' }], steps: ['Préparer la pâte.', 'Tremper les fleurs.', 'Frire dans l\'huile.'] },
  { id: 'epic-28', name: 'Salade de Poulpe', image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 45, servings: 4, difficulty: 'Moyen', category: 'Méditerranéen', ingredients: [{ item: 'Poulpe', quantity: '800g' }, { item: 'Pommes de terre', quantity: '400g' }, { item: 'Citron', quantity: '2' }, { item: 'Persil', quantity: '1 bouquet' }], steps: ['Cuire le poulpe.', 'Couper en morceaux.', 'Mélanger avec pommes de terre.', 'Assaisonner.'] },
  { id: 'epic-29', name: 'Tarte Tropézienne', image: 'https://images.unsplash.com/photo-1560529666-317819712619?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 40, cookTime: 25, servings: 8, difficulty: 'Difficile', category: 'Dessert', ingredients: [{ item: 'Brioche', quantity: '1' }, { item: 'Crème pâtissière', quantity: '400ml' }, { item: 'Crème au beurre', quantity: '300ml' }], steps: ['Préparer brioche.', 'Mélanger les crèmes.', 'Garnir la brioche.'] },
  { id: 'epic-30', name: 'Soupe Won Ton', image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 40, cookTime: 15, servings: 4, difficulty: 'Moyen', category: 'Chinois', ingredients: [{ item: 'Pâte won ton', quantity: '30' }, { item: 'Porc haché', quantity: '300g' }, { item: 'Crevettes', quantity: '200g' }, { item: 'Bouillon', quantity: '1.5L' }], steps: ['Préparer la farce.', 'Farcir les won ton.', 'Les cuire dans le bouillon.'] },
  
  { id: 'epic-31', name: 'Poulet Général Tao', image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 20, servings: 4, difficulty: 'Moyen', category: 'Chinois', ingredients: [{ item: 'Poulet', quantity: '600g' }, { item: 'Sauce soja', quantity: '100ml' }, { item: 'Sucre', quantity: '3 c. à soupe' }, { item: 'Gingembre', quantity: '1 morceau' }], steps: ['Frire le poulet pané.', 'Préparer la sauce.', 'Enrober le poulet.'] },
  { id: 'epic-32', name: 'Bûche Forêt Noire', image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 90, cookTime: 12, servings: 10, difficulty: 'Difficile', category: 'Dessert', ingredients: [{ item: 'Génoise chocolat', quantity: '1' }, { item: 'Chantilly', quantity: '600ml' }, { item: 'Cerises', quantity: '400g' }, { item: 'Kirsch', quantity: '50ml' }], steps: ['Rouler la génoise.', 'Garnir de chantilly et cerises.', 'Glacer.'] },
  { id: 'epic-33', name: 'Risotto Crevettes', image: 'https://images.unsplash.com/photo-1476124369491-f117991cdc65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 30, servings: 4, difficulty: 'Moyen', category: 'Italien', ingredients: [{ item: 'Riz arborio', quantity: '320g' }, { item: 'Crevettes', quantity: '400g' }, { item: 'Vin blanc', quantity: '100ml' }, { item: 'Bouillon', quantity: '1L' }], steps: ['Nacrer le riz.', 'Ajouter bouillon progressivement.', 'Incorporer crevettes.'] },
  { id: 'epic-34', name: 'Galettes Bretonnes', image: 'https://images.unsplash.com/photo-1695518069327-60d7601794a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 60, cookTime: 20, servings: 8, difficulty: 'Facile', category: 'Français', ingredients: [{ item: 'Farine de sarrasin', quantity: '400g' }, { item: 'Eau', quantity: '800ml' }, { item: 'Sel', quantity: '1 c. à café' }], steps: ['Préparer la pâte.', 'Laisser reposer.', 'Cuire les galettes.'] },
  { id: 'epic-35', name: 'Tiramisu Spéculoos', image: 'https://images.unsplash.com/photo-1714385905983-6f8e06fffae1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 0, servings: 8, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Spéculoos', quantity: '300g' }, { item: 'Mascarpone', quantity: '500g' }, { item: 'Œufs', quantity: '4' }, { item: 'Café', quantity: '300ml' }], steps: ['Battre mascarpone et œufs.', 'Tremper biscuits dans café.', 'Monter en couches.', 'Réfrigérer 4h.'] },
  
  { id: 'epic-36', name: 'Soupe Chorba', image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 50, servings: 8, difficulty: 'Moyen', category: 'Maghrébin', ingredients: [{ item: 'Agneau', quantity: '400g' }, { item: 'Pois chiches', quantity: '300g' }, { item: 'Vermicelles', quantity: '100g' }, { item: 'Tomates', quantity: '400g' }], steps: ['Faire revenir l\'agneau.', 'Ajouter légumes et épices.', 'Mijoter 45 min.', 'Ajouter vermicelles.'] },
  { id: 'epic-37', name: 'Maki Saumon Avocat', image: 'https://images.unsplash.com/photo-1625937751876-4515cd8e78bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 45, cookTime: 20, servings: 4, difficulty: 'Moyen', category: 'Japonais', ingredients: [{ item: 'Riz à sushi', quantity: '400g' }, { item: 'Saumon', quantity: '200g' }, { item: 'Avocat', quantity: '2' }, { item: 'Algues nori', quantity: '8' }], steps: ['Cuire le riz.', 'Étaler sur algue.', 'Garnir et rouler.', 'Trancher.'] },
  { id: 'epic-38', name: 'Charlotte Framboise', image: 'https://images.unsplash.com/photo-1560529666-317819712619?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 40, cookTime: 0, servings: 8, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Biscuits cuillère', quantity: '30' }, { item: 'Framboises', quantity: '600g' }, { item: 'Chantilly', quantity: '500ml' }, { item: 'Sucre', quantity: '100g' }], steps: ['Tapisser un moule de biscuits.', 'Préparer mousse framboises.', 'Garnir.', 'Réfrigérer 4h.'] },
  { id: 'epic-39', name: 'Pâtes Vongole', image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 15, servings: 4, difficulty: 'Moyen', category: 'Italien', ingredients: [{ item: 'Spaghetti', quantity: '400g' }, { item: 'Palourdes', quantity: '1kg' }, { item: 'Vin blanc', quantity: '100ml' }, { item: 'Ail', quantity: '4 gousses' }], steps: ['Faire ouvrir palourdes au vin.', 'Cuire pâtes.', 'Mélanger ensemble.', 'Ajouter persil.'] },
  { id: 'epic-40', name: 'Banana Bread', image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 50, servings: 8, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Bananes', quantity: '4' }, { item: 'Farine', quantity: '300g' }, { item: 'Sucre', quantity: '150g' }, { item: 'Œufs', quantity: '2' }], steps: ['Écraser les bananes.', 'Mélanger tous ingrédients.', 'Cuire 50 min à 180°C.'] },
  
  { id: 'epic-41', name: 'Poulet Citron Confit', image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 60, servings: 6, difficulty: 'Moyen', category: 'Maghrébin', ingredients: [{ item: 'Poulet', quantity: '1.5kg' }, { item: 'Citrons confits', quantity: '3' }, { item: 'Olives', quantity: '200g' }, { item: 'Épices', quantity: '3 c. à soupe' }], steps: ['Faire revenir le poulet.', 'Ajouter épices et citrons.', 'Mijoter 50 min.', 'Ajouter olives.'] },
  { id: 'epic-42', name: 'Profiteroles', image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 45, cookTime: 30, servings: 8, difficulty: 'Difficile', category: 'Dessert', ingredients: [{ item: 'Pâte à choux', quantity: '300g' }, { item: 'Glace vanille', quantity: '500ml' }, { item: 'Chocolat', quantity: '200g' }, { item: 'Crème', quantity: '100ml' }], steps: ['Former des choux.', 'Cuire 30 min.', 'Garnir de glace.', 'Napper de sauce chocolat.'] },
  { id: 'epic-43', name: 'Calamars Farcis', image: 'https://images.unsplash.com/photo-1626667215766-0f85a8e7ae47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 40, servings: 4, difficulty: 'Moyen', category: 'Méditerranéen', ingredients: [{ item: 'Calamars', quantity: '800g' }, { item: 'Riz', quantity: '200g' }, { item: 'Tomates', quantity: '400g' }, { item: 'Herbes', quantity: '2 c. à soupe' }], steps: ['Préparer la farce au riz.', 'Farcir les calamars.', 'Cuire dans sauce tomate.'] },
  { id: 'epic-44', name: 'Salade Coleslaw', image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 0, servings: 6, difficulty: 'Facile', category: 'Américain', ingredients: [{ item: 'Chou blanc', quantity: '500g' }, { item: 'Carottes', quantity: '2' }, { item: 'Mayonnaise', quantity: '200ml' }, { item: 'Vinaigre', quantity: '2 c. à soupe' }], steps: ['Râper chou et carottes.', 'Mélanger avec mayonnaise.', 'Réfrigérer.'] },
  { id: 'epic-45', name: 'Gâteau Renversé Ananas', image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 40, servings: 8, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Ananas', quantity: '8 tranches' }, { item: 'Farine', quantity: '200g' }, { item: 'Sucre', quantity: '150g' }, { item: 'Œufs', quantity: '3' }], steps: ['Caraméliser le sucre.', 'Disposer ananas.', 'Verser la pâte.', 'Cuire 40 min.', 'Démouler.'] },
  
  { id: 'epic-46', name: 'Raviolis Maison', image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 60, cookTime: 5, servings: 4, difficulty: 'Difficile', category: 'Italien', ingredients: [{ item: 'Pâte fraîche', quantity: '400g' }, { item: 'Ricotta', quantity: '300g' }, { item: 'Épinards', quantity: '200g' }, { item: 'Parmesan', quantity: '80g' }], steps: ['Préparer la farce.', 'Former les raviolis.', 'Cuire 5 min dans l\'eau.', 'Servir avec sauce.'] },
  { id: 'epic-47', name: 'Moelleux Chocolat Caramel', image: 'https://images.unsplash.com/photo-1606312619070-d48b4f50a8e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 12, servings: 6, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Chocolat', quantity: '200g' }, { item: 'Beurre', quantity: '150g' }, { item: 'Œufs', quantity: '4' }, { item: 'Caramel', quantity: '100g' }], steps: ['Faire fondre chocolat et beurre.', 'Ajouter œufs et caramel.', 'Cuire 12 min à 180°C.'] },
  { id: 'epic-48', name: 'Soupe de Poireaux', image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 30, servings: 6, difficulty: 'Facile', category: 'Français', ingredients: [{ item: 'Poireaux', quantity: '6' }, { item: 'Pommes de terre', quantity: '3' }, { item: 'Bouillon', quantity: '1.5L' }, { item: 'Crème', quantity: '150ml' }], steps: ['Faire revenir poireaux.', 'Ajouter pommes de terre et bouillon.', 'Cuire 25 min.', 'Mixer.'] },
  { id: 'epic-49', name: 'Terrine de Campagne', image: 'https://images.unsplash.com/photo-1587740896339-96a76170508d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 40, cookTime: 90, servings: 12, difficulty: 'Moyen', category: 'Français', ingredients: [{ item: 'Porc', quantity: '800g' }, { item: 'Foie de volaille', quantity: '200g' }, { item: 'Lardons', quantity: '200g' }, { item: 'Cognac', quantity: '50ml' }], steps: ['Mélanger toutes les viandes.', 'Ajouter cognac et épices.', 'Tasser dans une terrine.', 'Cuire au bain-marie 1h30.'] },
  { id: 'epic-50', name: 'Fondant au Café', image: 'https://images.unsplash.com/photo-1606312619070-d48b4f50a8e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 12, servings: 6, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Chocolat blanc', quantity: '200g' }, { item: 'Beurre', quantity: '100g' }, { item: 'Œufs', quantity: '3' }, { item: 'Café', quantity: '3 c. à soupe' }], steps: ['Faire fondre chocolat et beurre.', 'Incorporer œufs et café.', 'Cuire 12 min.'] },
  
  // Continuons avec 50 recettes supplémentaires pour atteindre 100
  { id: 'epic-51', name: 'Poulet Colombo', image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 45, servings: 6, difficulty: 'Moyen', category: 'Antillais', ingredients: [{ item: 'Poulet', quantity: '1.2kg' }, { item: 'Pâte colombo', quantity: '3 c. à soupe' }, { item: 'Légumes', quantity: '600g' }, { item: 'Lait de coco', quantity: '200ml' }], steps: ['Faire revenir le poulet.', 'Ajouter colombo et légumes.', 'Verser lait de coco.', 'Mijoter 40 min.'] },
  { id: 'epic-52', name: 'Éclair au Café', image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 60, cookTime: 25, servings: 12, difficulty: 'Difficile', category: 'Dessert', ingredients: [{ item: 'Pâte à choux', quantity: '300g' }, { item: 'Crème au café', quantity: '400g' }, { item: 'Fondant', quantity: '200g' }], steps: ['Former éclairs.', 'Cuire 25 min.', 'Garnir de crème.', 'Glacer.'] },
  { id: 'epic-53', name: 'Bœuf aux Oignons', image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 10, servings: 4, difficulty: 'Facile', category: 'Asiatique', ingredients: [{ item: 'Bœuf', quantity: '600g' }, { item: 'Oignons', quantity: '3' }, { item: 'Sauce soja', quantity: '4 c. à soupe' }, { item: 'Gingembre', quantity: '1 morceau' }], steps: ['Faire sauter bœuf et oignons.', 'Assaisonner de sauce soja.', 'Servir avec riz.'] },
  { id: 'epic-54', name: 'Verrines Avocat Saumon', image: 'https://images.unsplash.com/photo-1604908815541-ae5e2b7e4c2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 0, servings: 6, difficulty: 'Facile', category: 'Apéritif', ingredients: [{ item: 'Avocats', quantity: '3' }, { item: 'Saumon fumé', quantity: '200g' }, { item: 'Citron', quantity: '2' }, { item: 'Crème', quantity: '100ml' }], steps: ['Préparer crème d\'avocat.', 'Disposer en verrines.', 'Ajouter saumon.', 'Arroser de citron.'] },
  { id: 'epic-55', name: 'Crêpes Flambées', image: 'https://images.unsplash.com/photo-1695518069327-60d7601794a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 20, servings: 6, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Crêpes', quantity: '12' }, { item: 'Beurre', quantity: '80g' }, { item: 'Sucre', quantity: '100g' }, { item: 'Grand Marnier', quantity: '100ml' }], steps: ['Préparer beurre sucré.', 'Faire réchauffer crêpes.', 'Flamber au Grand Marnier.'] },
  
  { id: 'epic-56', name: 'Bœuf Rendang', image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 180, servings: 6, difficulty: 'Difficile', category: 'Indonésien', ingredients: [{ item: 'Bœuf', quantity: '1kg' }, { item: 'Lait de coco', quantity: '800ml' }, { item: 'Pâte de curry', quantity: '4 c. à soupe' }, { item: 'Citronnelle', quantity: '2 tiges' }], steps: ['Faire revenir le bœuf.', 'Ajouter pâte et lait de coco.', 'Mijoter 3h.'] },
  { id: 'epic-57', name: 'Religieuse Chocolat', image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 90, cookTime: 30, servings: 6, difficulty: 'Difficile', category: 'Dessert', ingredients: [{ item: 'Pâte à choux', quantity: '300g' }, { item: 'Crème au chocolat', quantity: '400g' }, { item: 'Fondant chocolat', quantity: '200g' }], steps: ['Former choux de 2 tailles.', 'Garnir de crème.', 'Glacer et assembler.'] },
  { id: 'epic-58', name: 'Salade de Choux', image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 0, servings: 6, difficulty: 'Facile', category: 'Salade', ingredients: [{ item: 'Chou', quantity: '500g' }, { item: 'Carottes', quantity: '2' }, { item: 'Vinaigrette', quantity: '100ml' }], steps: ['Râper chou et carottes.', 'Assaisonner.', 'Laisser mariner.'] },
  { id: 'epic-59', name: 'Gâteau Marbré', image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 40, servings: 8, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Farine', quantity: '200g' }, { item: 'Œufs', quantity: '3' }, { item: 'Sucre', quantity: '150g' }, { item: 'Cacao', quantity: '30g' }], steps: ['Préparer pâte vanille.', 'Diviser et ajouter cacao.', 'Alterner dans moule.', 'Cuire 40 min.'] },
  { id: 'epic-60', name: 'Soupe de Courge', image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 35, servings: 6, difficulty: 'Facile', category: 'Soupe', ingredients: [{ item: 'Courge', quantity: '1kg' }, { item: 'Bouillon', quantity: '1L' }, { item: 'Crème', quantity: '150ml' }], steps: ['Cuire la courge.', 'Mixer avec bouillon.', 'Ajouter crème.'] },
  
  { id: 'epic-61', name: 'Navarin d\'Agneau', image: 'https://images.unsplash.com/photo-1692106914421-e04e1066bd62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 120, servings: 6, difficulty: 'Moyen', category: 'Français', ingredients: [{ item: 'Agneau', quantity: '1.2kg' }, { item: 'Légumes printaniers', quantity: '800g' }, { item: 'Bouquet garni', quantity: '1' }], steps: ['Faire dorer l\'agneau.', 'Ajouter légumes.', 'Mijoter 2h.'] },
  { id: 'epic-62', name: 'Tarte au Citron Meringuée', image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 40, cookTime: 35, servings: 8, difficulty: 'Difficile', category: 'Dessert', ingredients: [{ item: 'Pâte sablée', quantity: '1' }, { item: 'Citrons', quantity: '5' }, { item: 'Œufs', quantity: '6' }, { item: 'Sucre', quantity: '250g' }], steps: ['Cuire la pâte.', 'Préparer crème citron.', 'Monter meringue.', 'Dorer au four.'] },
  { id: 'epic-63', name: 'Nems Végétariens', image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 40, cookTime: 15, servings: 6, difficulty: 'Moyen', category: 'Végétarien', ingredients: [{ item: 'Galettes de riz', quantity: '24' }, { item: 'Légumes', quantity: '600g' }, { item: 'Vermicelles', quantity: '100g' }], steps: ['Préparer la farce.', 'Rouler les nems.', 'Frire dans l\'huile.'] },
  { id: 'epic-64', name: 'Pâtes aux Noix', image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 10, cookTime: 12, servings: 4, difficulty: 'Facile', category: 'Italien', ingredients: [{ item: 'Pâtes', quantity: '400g' }, { item: 'Noix', quantity: '150g' }, { item: 'Parmesan', quantity: '80g' }, { item: 'Crème', quantity: '200ml' }], steps: ['Cuire les pâtes.', 'Mixer noix et parmesan.', 'Mélanger avec crème.'] },
  { id: 'epic-65', name: 'Flan Coco', image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 45, servings: 8, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Lait de coco', quantity: '800ml' }, { item: 'Œufs', quantity: '6' }, { item: 'Sucre', quantity: '150g' }], steps: ['Faire un caramel.', 'Mélanger lait, œufs et sucre.', 'Cuire au bain-marie.'] },
  
  { id: 'epic-66', name: 'Moules Marinières', image: 'https://images.unsplash.com/photo-1690521320157-0dc0d5f76269?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 10, servings: 4, difficulty: 'Facile', category: 'Poisson', ingredients: [{ item: 'Moules', quantity: '2kg' }, { item: 'Vin blanc', quantity: '300ml' }, { item: 'Échalotes', quantity: '4' }, { item: 'Persil', quantity: '1 bouquet' }], steps: ['Faire suer les échalotes.', 'Ajouter vin et moules.', 'Couvrir 8 min.', 'Parsemer de persil.'] },
  { id: 'epic-67', name: 'Crème Catalane', image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 40, servings: 6, difficulty: 'Moyen', category: 'Espagnol', ingredients: [{ item: 'Lait', quantity: '500ml' }, { item: 'Jaunes d\'œufs', quantity: '6' }, { item: 'Sucre', quantity: '100g' }, { item: 'Cannelle', quantity: '1 bâton' }], steps: ['Infuser cannelle dans lait.', 'Mélanger jaunes et sucre.', 'Cuire au bain-marie.', 'Caraméliser le dessus.'] },
  { id: 'epic-68', name: 'Gratin Endives Jambon', image: 'https://images.unsplash.com/photo-1753289595628-e3732ce60039?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 30, servings: 4, difficulty: 'Facile', category: 'Français', ingredients: [{ item: 'Endives', quantity: '8' }, { item: 'Jambon', quantity: '8 tranches' }, { item: 'Béchamel', quantity: '500ml' }, { item: 'Gruyère', quantity: '100g' }], steps: ['Cuire endives.', 'Rouler dans jambon.', 'Napper de béchamel.', 'Gratiner.'] },
  { id: 'epic-69', name: 'Mochi Glacé', image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 60, cookTime: 10, servings: 12, difficulty: 'Difficile', category: 'Japonais', ingredients: [{ item: 'Farine de riz glutineux', quantity: '200g' }, { item: 'Glace', quantity: '500ml' }, { item: 'Sucre', quantity: '100g' }], steps: ['Préparer pâte mochi.', 'Former des boulettes de glace.', 'Enrober de pâte.', 'Congeler.'] },
  { id: 'epic-70', name: 'Salade Avocat Mangue', image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 0, servings: 4, difficulty: 'Facile', category: 'Salade', ingredients: [{ item: 'Avocats', quantity: '3' }, { item: 'Mangue', quantity: '2' }, { item: 'Crevettes', quantity: '200g' }, { item: 'Citron vert', quantity: '2' }], steps: ['Couper fruits.', 'Mélanger avec crevettes.', 'Assaisonner citron vert.'] },
  
  { id: 'epic-71', name: 'Poulet aux Cacahuètes', image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 30, servings: 4, difficulty: 'Moyen', category: 'Asiatique', ingredients: [{ item: 'Poulet', quantity: '600g' }, { item: 'Beurre de cacahuète', quantity: '4 c. à soupe' }, { item: 'Lait de coco', quantity: '200ml' }, { item: 'Sauce soja', quantity: '3 c. à soupe' }], steps: ['Faire revenir le poulet.', 'Ajouter beurre cacahuète et lait.', 'Mijoter 25 min.'] },
  { id: 'epic-72', name: 'Tarte Sablée Framboises', image: 'https://images.unsplash.com/photo-1560529666-317819712619?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 25, servings: 8, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Pâte sablée', quantity: '1' }, { item: 'Framboises', quantity: '500g' }, { item: 'Crème pâtissière', quantity: '300ml' }], steps: ['Cuire la pâte.', 'Garnir de crème.', 'Disposer framboises.'] },
  { id: 'epic-73', name: 'Salade de Pois Chiches', image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 0, servings: 4, difficulty: 'Facile', category: 'Végétarien', ingredients: [{ item: 'Pois chiches', quantity: '400g' }, { item: 'Tomates', quantity: '3' }, { item: 'Concombre', quantity: '1' }, { item: 'Feta', quantity: '150g' }], steps: ['Mélanger tous ingrédients.', 'Assaisonner.'] },
  { id: 'epic-74', name: 'Pain Perdu Caramélisé', image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 10, cookTime: 15, servings: 4, difficulty: 'Facile', category: 'Brunch', ingredients: [{ item: 'Pain de mie', quantity: '8 tranches' }, { item: 'Œufs', quantity: '3' }, { item: 'Lait', quantity: '200ml' }, { item: 'Sucre', quantity: '100g' }], steps: ['Tremper pain dans œufs-lait.', 'Faire dorer au beurre.', 'Caraméliser au sucre.'] },
  { id: 'epic-75', name: 'Velouté Asperges', image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 25, servings: 6, difficulty: 'Facile', category: 'Soupe', ingredients: [{ item: 'Asperges', quantity: '1kg' }, { item: 'Pomme de terre', quantity: '1' }, { item: 'Bouillon', quantity: '1L' }, { item: 'Crème', quantity: '150ml' }], steps: ['Cuire asperges et pomme de terre.', 'Mixer.', 'Ajouter crème.'] },
  
  { id: 'epic-76', name: 'Agneau Korma', image: 'https://images.unsplash.com/photo-1692106914421-e04e1066bd62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 90, servings: 6, difficulty: 'Moyen', category: 'Indien', ingredients: [{ item: 'Agneau', quantity: '1kg' }, { item: 'Yaourt', quantity: '200g' }, { item: 'Crème', quantity: '200ml' }, { item: 'Amandes', quantity: '100g' }], steps: ['Faire mariner l\'agneau.', 'Faire revenir avec épices.', 'Mijoter avec yaourt et crème.'] },
  { id: 'epic-77', name: 'Charlotte au Chocolat', image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 40, cookTime: 0, servings: 8, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Biscuits cuillère', quantity: '30' }, { item: 'Mousse chocolat', quantity: '600g' }], steps: ['Tapisser moule de biscuits.', 'Garnir de mousse.', 'Réfrigérer 4h.'] },
  { id: 'epic-78', name: 'Pâtes Arrabiata', image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 10, cookTime: 20, servings: 4, difficulty: 'Facile', category: 'Italien', ingredients: [{ item: 'Penne', quantity: '400g' }, { item: 'Tomates', quantity: '400g' }, { item: 'Piment', quantity: '2' }, { item: 'Ail', quantity: '3 gousses' }], steps: ['Faire revenir ail et piment.', 'Ajouter tomates.', 'Cuire pâtes et mélanger.'] },
  { id: 'epic-79', name: 'Smoothie Bowl Açaï', image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 10, cookTime: 0, servings: 2, difficulty: 'Facile', category: 'Brunch', ingredients: [{ item: 'Açaï', quantity: '200g' }, { item: 'Bananes', quantity: '2' }, { item: 'Fruits', quantity: '200g' }, { item: 'Granola', quantity: '100g' }], steps: ['Mixer açaï et bananes.', 'Verser dans bols.', 'Garnir de fruits et granola.'] },
  { id: 'epic-80', name: 'Gâteau Invisible Pommes', image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 50, servings: 8, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Pommes', quantity: '1kg' }, { item: 'Œufs', quantity: '3' }, { item: 'Farine', quantity: '100g' }, { item: 'Sucre', quantity: '100g' }], steps: ['Trancher pommes très finement.', 'Préparer appareil.', 'Mélanger et cuire 50 min.'] },
  
  { id: 'epic-81', name: 'Brochettes de Gambas', image: 'https://images.unsplash.com/photo-1633504581786-316c8002b1b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 10, servings: 4, difficulty: 'Facile', category: 'Poisson', ingredients: [{ item: 'Gambas', quantity: '800g' }, { item: 'Ail', quantity: '4 gousses' }, { item: 'Persil', quantity: '1 bouquet' }, { item: 'Citron', quantity: '2' }], steps: ['Enfiler gambas sur brochettes.', 'Badigeonner d\'ail-persil.', 'Griller 10 min.'] },
  { id: 'epic-82', name: 'Tarte aux Myrtilles', image: 'https://images.unsplash.com/photo-1560529666-317819712619?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 35, servings: 8, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Pâte sablée', quantity: '1' }, { item: 'Myrtilles', quantity: '600g' }, { item: 'Sucre', quantity: '100g' }, { item: 'Crème', quantity: '150ml' }], steps: ['Étaler pâte.', 'Disposer myrtilles.', 'Verser crème sucrée.', 'Cuire 35 min.'] },
  { id: 'epic-83', name: 'Soupe de Lentilles', image: 'https://images.unsplash.com/photo-1683743127028-7389d247337b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 35, servings: 6, difficulty: 'Facile', category: 'Soupe', ingredients: [{ item: 'Lentilles', quantity: '300g' }, { item: 'Carottes', quantity: '3' }, { item: 'Bouillon', quantity: '1.5L' }, { item: 'Cumin', quantity: '1 c. à café' }], steps: ['Faire revenir carottes.', 'Ajouter lentilles et bouillon.', 'Cuire 30 min.'] },
  { id: 'epic-84', name: 'Galettes de Quinoa', image: 'https://images.unsplash.com/photo-1753289595628-e3732ce60039?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 25, cookTime: 15, servings: 4, difficulty: 'Facile', category: 'Végétarien', ingredients: [{ item: 'Quinoa', quantity: '300g' }, { item: 'Œuf', quantity: '1' }, { item: 'Légumes', quantity: '200g' }, { item: 'Farine', quantity: '50g' }], steps: ['Cuire quinoa.', 'Mélanger avec œuf et légumes.', 'Former galettes.', 'Faire dorer.'] },
  { id: 'epic-85', name: 'Mousse au Café', image: 'https://images.unsplash.com/photo-1541599468348-e96984315921?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 5, servings: 6, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Café', quantity: '200ml' }, { item: 'Œufs', quantity: '4' }, { item: 'Sucre', quantity: '80g' }], steps: ['Faire fondre café et sucre.', 'Incorporer jaunes.', 'Monter blancs en neige.', 'Mélanger délicatement.'] },
  
  { id: 'epic-86', name: 'Saumon Gravlax', image: 'https://images.unsplash.com/photo-1580217593608-61931cefc821?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 0, servings: 8, difficulty: 'Facile', category: 'Scandinave', ingredients: [{ item: 'Saumon', quantity: '1kg' }, { item: 'Sucre', quantity: '100g' }, { item: 'Sel', quantity: '100g' }, { item: 'Aneth', quantity: '1 bouquet' }], steps: ['Mélanger sucre, sel et aneth.', 'Enrober le saumon.', 'Laisser mariner 48h.', 'Trancher finement.'] },
  { id: 'epic-87', name: 'Financiers Pistache', image: 'https://images.unsplash.com/photo-1571506165871-ee72a35bc9d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 12, servings: 12, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Poudre d\'amandes', quantity: '100g' }, { item: 'Pistaches', quantity: '50g' }, { item: 'Blancs d\'œufs', quantity: '4' }, { item: 'Beurre', quantity: '100g' }], steps: ['Préparer beurre noisette.', 'Mélanger ingrédients.', 'Verser dans moules.', 'Cuire 12 min.'] },
  { id: 'epic-88', name: 'Pâtes Sauce Vodka', image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 10, cookTime: 20, servings: 4, difficulty: 'Facile', category: 'Italien', ingredients: [{ item: 'Penne', quantity: '400g' }, { item: 'Tomates', quantity: '400g' }, { item: 'Vodka', quantity: '50ml' }, { item: 'Crème', quantity: '200ml' }], steps: ['Faire réduire tomates et vodka.', 'Ajouter crème.', 'Cuire pâtes et mélanger.'] },
  { id: 'epic-89', name: 'Salade Taboulé', image: 'https://images.unsplash.com/photo-1637806930600-37fa8892069d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 0, servings: 6, difficulty: 'Facile', category: 'Libanais', ingredients: [{ item: 'Boulgour', quantity: '200g' }, { item: 'Persil', quantity: '2 bottes' }, { item: 'Tomates', quantity: '4' }, { item: 'Menthe', quantity: '1 bouquet' }], steps: ['Faire tremper boulgour.', 'Hacher persil et menthe.', 'Mélanger tous ingrédients.'] },
  { id: 'epic-90', name: 'Riz au Lait Vanille', image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 10, cookTime: 40, servings: 6, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Riz', quantity: '200g' }, { item: 'Lait', quantity: '1L' }, { item: 'Sucre', quantity: '100g' }, { item: 'Vanille', quantity: '1 gousse' }], steps: ['Cuire riz dans lait.', 'Ajouter sucre et vanille.', 'Cuire 35 min.'] },
  
  { id: 'epic-91', name: 'Poulet Cacciatore', image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 45, servings: 6, difficulty: 'Moyen', category: 'Italien', ingredients: [{ item: 'Poulet', quantity: '1.2kg' }, { item: 'Tomates', quantity: '800g' }, { item: 'Champignons', quantity: '200g' }, { item: 'Vin rouge', quantity: '150ml' }], steps: ['Faire dorer poulet.', 'Ajouter légumes et vin.', 'Mijoter 40 min.'] },
  { id: 'epic-92', name: 'Compote de Pommes', image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 10, cookTime: 25, servings: 6, difficulty: 'Facile', category: 'Dessert', ingredients: [{ item: 'Pommes', quantity: '1kg' }, { item: 'Sucre', quantity: '50g' }, { item: 'Cannelle', quantity: '1 c. à café' }], steps: ['Couper les pommes.', 'Cuire avec sucre.', 'Mixer ou écraser.'] },
  { id: 'epic-93', name: 'Salade de Haricots', image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 10, servings: 4, difficulty: 'Facile', category: 'Salade', ingredients: [{ item: 'Haricots rouges', quantity: '400g' }, { item: 'Haricots blancs', quantity: '400g' }, { item: 'Oignon rouge', quantity: '1' }, { item: 'Vinaigrette', quantity: '6 c. à soupe' }], steps: ['Rincer les haricots.', 'Mélanger avec oignon.', 'Assaisonner.'] },
  { id: 'epic-94', name: 'Tarte Fine Endives', image: 'https://images.unsplash.com/photo-1627308595232-d0cd54b31a4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 30, servings: 6, difficulty: 'Facile', category: 'Végétarien', ingredients: [{ item: 'Pâte feuilletée', quantity: '1' }, { item: 'Endives', quantity: '4' }, { item: 'Chèvre', quantity: '150g' }, { item: 'Miel', quantity: '2 c. à soupe' }], steps: ['Caraméliser endives au miel.', 'Disposer sur pâte.', 'Ajouter chèvre.', 'Cuire 25 min.'] },
  { id: 'epic-95', name: 'Mousse Framboise', image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 20, cookTime: 0, servings: 6, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Framboises', quantity: '400g' }, { item: 'Sucre', quantity: '100g' }, { item: 'Blancs d\'œufs', quantity: '3' }, { item: 'Crème', quantity: '200ml' }], steps: ['Mixer framboises et sucre.', 'Monter blancs et crème.', 'Incorporer délicatement.', 'Réfrigérer.'] },
  
  { id: 'epic-96', name: 'Bœuf Teriyaki', image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 15, servings: 4, difficulty: 'Facile', category: 'Japonais', ingredients: [{ item: 'Bœuf', quantity: '600g' }, { item: 'Sauce soja', quantity: '100ml' }, { item: 'Mirin', quantity: '50ml' }, { item: 'Sucre', quantity: '2 c. à soupe' }], steps: ['Faire sauter le bœuf.', 'Ajouter sauce teriyaki.', 'Laisser réduire.', 'Servir avec riz.'] },
  { id: 'epic-97', name: 'Tarte Chocolat Caramel', image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 30, cookTime: 25, servings: 8, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Pâte sablée', quantity: '1' }, { item: 'Caramel', quantity: '200g' }, { item: 'Ganache chocolat', quantity: '300g' }], steps: ['Cuire la pâte.', 'Étaler caramel.', 'Recouvrir de ganache.', 'Réfrigérer.'] },
  { id: 'epic-98', name: 'Soupe de Courgettes', image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 25, servings: 6, difficulty: 'Facile', category: 'Soupe', ingredients: [{ item: 'Courgettes', quantity: '1kg' }, { item: 'Pomme de terre', quantity: '1' }, { item: 'Bouillon', quantity: '1L' }, { item: 'Fromage frais', quantity: '100g' }], steps: ['Cuire courgettes et pomme de terre.', 'Mixer.', 'Ajouter fromage frais.'] },
  { id: 'epic-99', name: 'Frittata Légumes', image: 'https://images.unsplash.com/photo-1732969331543-80e52902e0a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 25, servings: 6, difficulty: 'Facile', category: 'Italien', ingredients: [{ item: 'Œufs', quantity: '8' }, { item: 'Légumes', quantity: '400g' }, { item: 'Parmesan', quantity: '80g' }], steps: ['Faire revenir légumes.', 'Battre œufs et parmesan.', 'Verser sur légumes.', 'Cuire au four.'] },
  { id: 'epic-100', name: 'Sabayon au Champagne', image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080', prepTime: 15, cookTime: 10, servings: 4, difficulty: 'Moyen', category: 'Dessert', ingredients: [{ item: 'Jaunes d\'œufs', quantity: '6' }, { item: 'Sucre', quantity: '100g' }, { item: 'Champagne', quantity: '100ml' }], steps: ['Battre jaunes et sucre.', 'Ajouter champagne.', 'Cuire au bain-marie en fouettant.', 'Servir tiède.'] },
];
