// Collection supplémentaire de 60 recettes variées
import type { Recipe } from '../components/RecipesScreen';

export const extraRecipes: Recipe[] = [
  // ===== CUISINE DU MONDE =====
  {
    id: 'world-1',
    name: 'Couscous Royal',
    image: 'https://images.unsplash.com/photo-1645696329654-2a609cbea1f6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 90,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Maghrébin',
    ingredients: [
      { item: 'Semoule de couscous', quantity: '800g' },
      { item: 'Agneau', quantity: '500g' },
      { item: 'Poulet', quantity: '500g' },
      { item: 'Merguez', quantity: '8' },
      { item: 'Pois chiches', quantity: '400g' },
      { item: 'Carottes', quantity: '4' },
      { item: 'Navets', quantity: '3' },
      { item: 'Courgettes', quantity: '3' },
      { item: 'Ras el hanout', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Faire revenir les viandes avec le ras el hanout.',
      'Ajouter oignons et tomates.',
      'Mouiller d\'eau, ajouter pois chiches.',
      'Mijoter 1h.',
      'Ajouter tous les légumes.',
      'Cuire encore 30 min.',
      'Préparer la semoule à la vapeur.',
      'Servir avec harissa.',
    ],
  },
  {
    id: 'world-2',
    name: 'Chili Con Carne',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    difficulty: 'Facile',
    category: 'Mexicain',
    ingredients: [
      { item: 'Bœuf haché', quantity: '800g' },
      { item: 'Haricots rouges', quantity: '800g' },
      { item: 'Tomates concassées', quantity: '800g' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Poivrons rouges', quantity: '2' },
      { item: 'Piment', quantity: '2' },
      { item: 'Cumin', quantity: '2 c. à soupe' },
      { item: 'Paprika', quantity: '1 c. à soupe' },
    ],
    steps: [
      'Faire revenir les oignons et poivrons.',
      'Ajouter la viande hachée.',
      'Incorporer les épices.',
      'Ajouter tomates et haricots.',
      'Mijoter 45 minutes à feu doux.',
      'Rectifier l\'assaisonnement.',
      'Servir avec riz et crème fraîche.',
    ],
  },
  {
    id: 'world-3',
    name: 'Fajitas au Poulet',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Mexicain',
    ingredients: [
      { item: 'Poulet', quantity: '600g' },
      { item: 'Tortillas', quantity: '8' },
      { item: 'Poivrons', quantity: '3' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Guacamole', quantity: '200g' },
      { item: 'Crème fraîche', quantity: '150ml' },
      { item: 'Épices mexicaines', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Couper poulet et légumes en lanières.',
      'Faire mariner le poulet aux épices.',
      'Faire revenir à feu vif.',
      'Ajouter les légumes.',
      'Chauffer les tortillas.',
      'Servir avec guacamole et crème.',
    ],
  },
  {
    id: 'world-4',
    name: 'Bo Bun Vietnamien',
    image: 'https://images.unsplash.com/photo-1603073113631-e5ee98dd3a8e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 10,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Vermicelles de riz', quantity: '400g' },
      { item: 'Bœuf', quantity: '400g' },
      { item: 'Salade', quantity: '1' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Menthe fraîche', quantity: '1 bouquet' },
      { item: 'Cacahuètes', quantity: '100g' },
      { item: 'Sauce nuoc-mâm', quantity: '100ml' },
    ],
    steps: [
      'Faire mariner le bœuf.',
      'Cuire les vermicelles.',
      'Râper carottes et concombre.',
      'Faire griller le bœuf.',
      'Préparer la sauce nuoc-mâm.',
      'Assembler dans un bol.',
      'Parsemer de menthe et cacahuètes.',
    ],
  },
  {
    id: 'world-5',
    name: 'Nems au Porc',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 45,
    cookTime: 15,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Galettes de riz', quantity: '24' },
      { item: 'Porc haché', quantity: '400g' },
      { item: 'Vermicelles', quantity: '100g' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Pousses de soja', quantity: '150g' },
      { item: 'Champignons noirs', quantity: '50g' },
      { item: 'Sauce soja', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Réhydrater vermicelles et champignons.',
      'Mélanger tous les ingrédients de farce.',
      'Humidifier les galettes de riz.',
      'Garnir et rouler en cigares.',
      'Faire frire dans l\'huile chaude.',
      'Égoutter sur papier absorbant.',
      'Servir avec sauce aigre-douce.',
    ],
  },
  {
    id: 'world-6',
    name: 'Curry Vert Thaï',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Poulet', quantity: '600g' },
      { item: 'Pâte de curry vert', quantity: '3 c. à soupe' },
      { item: 'Lait de coco', quantity: '400ml' },
      { item: 'Aubergines thaï', quantity: '200g' },
      { item: 'Haricots verts', quantity: '150g' },
      { item: 'Basilic thaï', quantity: '1 bouquet' },
      { item: 'Sauce de poisson', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Faire revenir la pâte de curry.',
      'Ajouter le poulet coupé en morceaux.',
      'Verser le lait de coco.',
      'Incorporer les légumes.',
      'Mijoter 20 minutes.',
      'Ajouter basilic et sauce de poisson.',
      'Servir avec du riz jasmin.',
    ],
  },
  {
    id: 'world-7',
    name: 'Saumon Teriyaki',
    image: 'https://images.unsplash.com/photo-1599046792003-e1e6c40b2e6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Filets de saumon', quantity: '4' },
      { item: 'Sauce soja', quantity: '100ml' },
      { item: 'Mirin', quantity: '50ml' },
      { item: 'Sucre', quantity: '2 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Graines de sésame', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Mélanger sauce soja, mirin et sucre.',
      'Ajouter gingembre et ail râpés.',
      'Faire mariner le saumon 30 min.',
      'Griller le saumon à la poêle.',
      'Napper de sauce réduite.',
      'Parsemer de graines de sésame.',
      'Servir avec du riz et légumes vapeur.',
    ],
  },
  {
    id: 'world-8',
    name: 'Gyozas au Porc',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 60,
    cookTime: 15,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Pâte à gyozas', quantity: '40 feuilles' },
      { item: 'Porc haché', quantity: '400g' },
      { item: 'Chou chinois', quantity: '300g' },
      { item: 'Ciboule', quantity: '3' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Sauce soja', quantity: '3 c. à soupe' },
      { item: 'Huile de sésame', quantity: '1 c. à soupe' },
    ],
    steps: [
      'Hacher finement le chou et égoutter.',
      'Mélanger avec le porc et assaisonnements.',
      'Garnir les feuilles de pâte.',
      'Former des demi-lunes.',
      'Faire dorer à la poêle.',
      'Ajouter de l\'eau et couvrir.',
      'Cuire jusqu\'à évaporation.',
    ],
  },
  {
    id: 'world-9',
    name: 'Paella aux Fruits de Mer',
    image: 'https://images.unsplash.com/photo-1602755088318-39b7a7e6482a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 40,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Espagnol',
    ingredients: [
      { item: 'Riz bomba', quantity: '400g' },
      { item: 'Crevettes', quantity: '300g' },
      { item: 'Moules', quantity: '500g' },
      { item: 'Calamars', quantity: '300g' },
      { item: 'Safran', quantity: '1g' },
      { item: 'Bouillon de poisson', quantity: '1L' },
      { item: 'Petits pois', quantity: '150g' },
    ],
    steps: [
      'Faire revenir les fruits de mer.',
      'Ajouter le riz et le safran.',
      'Verser le bouillon chaud.',
      'Ne pas remuer.',
      'Cuire à feu moyen 20 minutes.',
      'Ajouter petits pois 5 min avant la fin.',
      'Laisser reposer 5 min avant de servir.',
    ],
  },
  {
    id: 'world-10',
    name: 'Fish and Chips',
    image: 'https://images.unsplash.com/photo-1579208570378-8c970854bc23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Britannique',
    ingredients: [
      { item: 'Cabillaud', quantity: '800g' },
      { item: 'Pommes de terre', quantity: '1kg' },
      { item: 'Farine', quantity: '200g' },
      { item: 'Bière blonde', quantity: '250ml' },
      { item: 'Levure chimique', quantity: '1 c. à café' },
      { item: 'Huile de friture', quantity: '2L' },
    ],
    steps: [
      'Préparer la pâte à beignet: farine, bière, levure.',
      'Couper les pommes de terre en gros bâtonnets.',
      'Frire les frites une première fois.',
      'Tremper le poisson dans la pâte.',
      'Frire dans l\'huile très chaude.',
      'Frire les frites une seconde fois.',
      'Servir avec sauce tartare.',
    ],
  },

  // ===== PLATS VÉGÉTARIENS AVANCÉS =====
  {
    id: 'veg-1',
    name: 'Burger Végétarien',
    image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pains burger', quantity: '4' },
      { item: 'Haricots noirs', quantity: '400g' },
      { item: 'Quinoa cuit', quantity: '150g' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Cumin', quantity: '1 c. à café' },
      { item: 'Cheddar', quantity: '4 tranches' },
      { item: 'Avocat', quantity: '2' },
    ],
    steps: [
      'Écraser les haricots.',
      'Mélanger avec quinoa, oignon et épices.',
      'Former 4 steaks.',
      'Cuire à la poêle 5 min de chaque côté.',
      'Ajouter le fromage en fin de cuisson.',
      'Toaster les pains.',
      'Assembler avec avocat et condiments.',
    ],
  },
  {
    id: 'veg-2',
    name: 'Tarte aux Légumes d\'Été',
    image: 'https://images.unsplash.com/photo-1627308595232-d0cd54b31a4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 40,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pâte feuilletée', quantity: '1' },
      { item: 'Courgettes', quantity: '2' },
      { item: 'Tomates', quantity: '4' },
      { item: 'Aubergine', quantity: '1' },
      { item: 'Chèvre frais', quantity: '150g' },
      { item: 'Herbes de Provence', quantity: '2 c. à soupe' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
    ],
    steps: [
      'Préchauffer le four à 200°C.',
      'Trancher tous les légumes.',
      'Étaler la pâte dans un moule.',
      'Disposer le chèvre sur le fond.',
      'Alterner les légumes en rosace.',
      'Arroser d\'huile et saupoudrer d\'herbes.',
      'Cuire 40 minutes.',
    ],
  },
  {
    id: 'veg-3',
    name: 'Falafels Maison',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pois chiches', quantity: '400g' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Persil', quantity: '1 bouquet' },
      { item: 'Coriandre', quantity: '1 bouquet' },
      { item: 'Cumin', quantity: '2 c. à café' },
      { item: 'Farine de pois chiche', quantity: '50g' },
    ],
    steps: [
      'Mixer pois chiches, oignon, ail et herbes.',
      'Ajouter cumin et farine.',
      'Former des boulettes.',
      'Réfrigérer 30 minutes.',
      'Frire dans l\'huile chaude.',
      'Égoutter sur papier absorbant.',
      'Servir avec sauce tahini.',
    ],
  },
  {
    id: 'veg-4',
    name: 'Aubergines à la Parmigiana',
    image: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 45,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Végétarien',
    ingredients: [
      { item: 'Aubergines', quantity: '3' },
      { item: 'Sauce tomate', quantity: '800g' },
      { item: 'Mozzarella', quantity: '400g' },
      { item: 'Parmesan', quantity: '150g' },
      { item: 'Basilic', quantity: '1 bouquet' },
      { item: 'Huile d\'olive', quantity: '100ml' },
    ],
    steps: [
      'Trancher et faire dégorger les aubergines.',
      'Les faire griller à l\'huile d\'olive.',
      'Dans un plat, alterner aubergines et sauce.',
      'Ajouter mozzarella et parmesan.',
      'Répéter les couches.',
      'Terminer par du fromage.',
      'Cuire au four à 180°C pendant 40 minutes.',
    ],
  },
  {
    id: 'veg-5',
    name: 'Taboulé Libanais',
    image: 'https://images.unsplash.com/photo-1637806930600-37fa8892069d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 0,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Boulgour fin', quantity: '150g' },
      { item: 'Persil plat', quantity: '2 bottes' },
      { item: 'Menthe fraîche', quantity: '1 bouquet' },
      { item: 'Tomates', quantity: '4' },
      { item: 'Oignons verts', quantity: '6' },
      { item: 'Citrons', quantity: '3' },
      { item: 'Huile d\'olive', quantity: '100ml' },
    ],
    steps: [
      'Faire tremper le boulgour 30 min.',
      'Hacher finement persil et menthe.',
      'Concasser les tomates.',
      'Émincer les oignons verts.',
      'Mélanger tous les ingrédients.',
      'Assaisonner avec citron et huile.',
      'Réfrigérer 1h avant de servir.',
    ],
  },

  // ===== PÂTES VARIÉES =====
  {
    id: 'pasta-1',
    name: 'Pâtes Bolognaise',
    image: 'https://images.unsplash.com/photo-1572441713132-c542fc4fe282?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes', quantity: '500g' },
      { item: 'Viande hachée', quantity: '600g' },
      { item: 'Tomates concassées', quantity: '800g' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Céleri', quantity: '2 branches' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Vin rouge', quantity: '100ml' },
      { item: 'Parmesan', quantity: '100g' },
    ],
    steps: [
      'Faire revenir oignon, carotte et céleri.',
      'Ajouter la viande hachée.',
      'Déglacer au vin rouge.',
      'Incorporer les tomates.',
      'Mijoter 45 minutes à feu doux.',
      'Cuire les pâtes al dente.',
      'Servir avec parmesan râpé.',
    ],
  },
  {
    id: 'pasta-2',
    name: 'Pâtes à la Puttanesca',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Spaghetti', quantity: '400g' },
      { item: 'Tomates cerises', quantity: '400g' },
      { item: 'Olives noires', quantity: '150g' },
      { item: 'Câpres', quantity: '3 c. à soupe' },
      { item: 'Anchois', quantity: '6 filets' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Piment', quantity: '1' },
    ],
    steps: [
      'Faire revenir ail et anchois.',
      'Ajouter tomates, olives et câpres.',
      'Incorporer le piment.',
      'Mijoter 15 minutes.',
      'Cuire les pâtes al dente.',
      'Mélanger avec la sauce.',
      'Servir immédiatement.',
    ],
  },
  {
    id: 'pasta-3',
    name: 'Pâtes Aglio e Olio',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 5,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Spaghetti', quantity: '400g' },
      { item: 'Ail', quantity: '6 gousses' },
      { item: 'Huile d\'olive', quantity: '100ml' },
      { item: 'Piment rouge', quantity: '1' },
      { item: 'Persil', quantity: '1 bouquet' },
      { item: 'Parmesan', quantity: '50g' },
    ],
    steps: [
      'Cuire les pâtes al dente.',
      'Faire revenir l\'ail dans l\'huile.',
      'Ajouter le piment émincé.',
      'Mélanger avec les pâtes et eau de cuisson.',
      'Parsemer de persil ciselé.',
      'Servir avec du parmesan.',
    ],
  },
  {
    id: 'pasta-4',
    name: 'Lasagnes à la Bolognaise',
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 50,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes à lasagne', quantity: '16 feuilles' },
      { item: 'Viande hachée', quantity: '800g' },
      { item: 'Sauce tomate', quantity: '800g' },
      { item: 'Béchamel', quantity: '800ml' },
      { item: 'Parmesan', quantity: '200g' },
      { item: 'Mozzarella', quantity: '200g' },
    ],
    steps: [
      'Préparer la sauce bolognaise.',
      'Préparer la béchamel.',
      'Dans un plat, alterner: bolognaise, pâtes, béchamel.',
      'Répéter 4 fois.',
      'Terminer par béchamel et fromages.',
      'Cuire au four à 180°C pendant 45 minutes.',
      'Laisser reposer 10 min avant de servir.',
    ],
  },

  // ===== VIANDES & POISSONS =====
  {
    id: 'meat-1',
    name: 'Magret de Canard',
    image: 'https://images.unsplash.com/photo-1626200419455-0348c232b193?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Magrets de canard', quantity: '2' },
      { item: 'Miel', quantity: '2 c. à soupe' },
      { item: 'Vinaigre balsamique', quantity: '3 c. à soupe' },
      { item: 'Thym', quantity: '2 branches' },
      { item: 'Sel et poivre', quantity: 'Au goût' },
    ],
    steps: [
      'Quadriller la peau des magrets.',
      'Assaisonner de sel et poivre.',
      'Cuire côté peau 8 minutes.',
      'Retourner et cuire 4 minutes.',
      'Dégazer avec miel et vinaigre.',
      'Laisser reposer 5 minutes.',
      'Trancher et servir avec la sauce.',
    ],
  },
  {
    id: 'meat-2',
    name: 'Osso Bucco',
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 150,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Jarret de veau', quantity: '1.5kg' },
      { item: 'Vin blanc', quantity: '300ml' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Bouillon de volaille', quantity: '500ml' },
      { item: 'Zeste de citron', quantity: '1' },
    ],
    steps: [
      'Fariner et faire dorer les morceaux de veau.',
      'Réserver.',
      'Faire revenir oignon et carottes.',
      'Déglacer au vin blanc.',
      'Ajouter tomates et bouillon.',
      'Remettre la viande.',
      'Mijoter 2h30 à feu doux.',
      'Servir avec gremolata (ail, persil, zeste de citron).',
    ],
  },
  {
    id: 'meat-3',
    name: 'Côte de Bœuf',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Côte de bœuf', quantity: '1.2kg' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Thym', quantity: '4 branches' },
      { item: 'Romarin', quantity: '2 branches' },
      { item: 'Ail', quantity: '4 gousses' },
      { item: 'Fleur de sel', quantity: 'Au goût' },
    ],
    steps: [
      'Sortir la viande 1h avant cuisson.',
      'Assaisonner généreusement.',
      'Saisir à feu vif 3 min de chaque côté.',
      'Ajouter beurre, thym, romarin et ail.',
      'Arroser régulièrement.',
      'Cuire au four à 200°C selon cuisson désirée.',
      'Laisser reposer 10 min avant de trancher.',
    ],
  },
  {
    id: 'fish-1',
    name: 'Bar en Croûte de Sel',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Facile',
    category: 'Poisson',
    ingredients: [
      { item: 'Bar entier', quantity: '1.5kg' },
      { item: 'Gros sel', quantity: '2kg' },
      { item: 'Blanc d\'œuf', quantity: '3' },
      { item: 'Thym', quantity: '4 branches' },
      { item: 'Fenouil', quantity: '1 bulbe' },
      { item: 'Citron', quantity: '2' },
    ],
    steps: [
      'Préchauffer le four à 200°C.',
      'Mélanger sel et blancs d\'œufs.',
      'Farcir le poisson de thym et fenouil.',
      'Étaler une couche de sel.',
      'Poser le poisson.',
      'Recouvrir entièrement de sel.',
      'Cuire 30 min.',
      'Casser la croûte et servir avec citron.',
    ],
  },
  {
    id: 'fish-2',
    name: 'Thon Mi-Cuit au Sésame',
    image: 'https://images.unsplash.com/photo-1632598838624-2fd25c41b7d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 5,
    servings: 4,
    difficulty: 'Facile',
    category: 'Poisson',
    ingredients: [
      { item: 'Thon rouge', quantity: '600g' },
      { item: 'Graines de sésame', quantity: '4 c. à soupe' },
      { item: 'Sauce soja', quantity: '3 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Huile de sésame', quantity: '2 c. à soupe' },
      { item: 'Wasabi', quantity: 'Pour servir' },
    ],
    steps: [
      'Rouler le thon dans les graines de sésame.',
      'Saisir à feu très vif 1 min de chaque côté.',
      'Le cœur doit rester cru.',
      'Laisser refroidir.',
      'Trancher finement.',
      'Servir avec sauce soja et wasabi.',
    ],
  },

  // ===== GRATINS & PLATS AU FOUR =====
  {
    id: 'gratin-1',
    name: 'Gratin de Courgettes',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Légumes',
    ingredients: [
      { item: 'Courgettes', quantity: '1kg' },
      { item: 'Crème fraîche', quantity: '300ml' },
      { item: 'Gruyère râpé', quantity: '200g' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Thym', quantity: '2 c. à café' },
    ],
    steps: [
      'Trancher les courgettes.',
      'Disposer dans un plat beurré.',
      'Mélanger crème, ail et thym.',
      'Verser sur les courgettes.',
      'Parsemer de gruyère.',
      'Cuire au four à 180°C pendant 40 minutes.',
    ],
  },
  {
    id: 'gratin-2',
    name: 'Gratin de Macaronis',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 6,
    difficulty: 'Facile',
    category: 'Pâtes',
    ingredients: [
      { item: 'Macaronis', quantity: '500g' },
      { item: 'Béchamel', quantity: '800ml' },
      { item: 'Jambon', quantity: '200g' },
      { item: 'Gruyère râpé', quantity: '200g' },
      { item: 'Muscade', quantity: '1 pincée' },
    ],
    steps: [
      'Cuire les macaronis al dente.',
      'Préparer la béchamel.',
      'Mélanger pâtes, béchamel et jambon.',
      'Verser dans un plat à gratin.',
      'Parsemer de gruyère.',
      'Cuire au four à 180°C pendant 25 minutes.',
    ],
  },
  {
    id: 'gratin-3',
    name: 'Gratin de Chou-Fleur',
    image: 'https://images.unsplash.com/photo-1568584711271-4fc47c6f81e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Légumes',
    ingredients: [
      { item: 'Chou-fleur', quantity: '1' },
      { item: 'Béchamel', quantity: '500ml' },
      { item: 'Gruyère râpé', quantity: '150g' },
      { item: 'Muscade', quantity: '1 pincée' },
      { item: 'Chapelure', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Cuire le chou-fleur à la vapeur.',
      'Disposer dans un plat à gratin.',
      'Napper de béchamel.',
      'Parsemer de gruyère et chapelure.',
      'Cuire au four à 200°C pendant 25 minutes.',
    ],
  },

  // ===== PLATS MIJOTÉS =====
  {
    id: 'stew-1',
    name: 'Daube Provençale',
    image: 'https://images.unsplash.com/photo-1548869206-93b036288d7e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 180,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Bœuf à braiser', quantity: '1.5kg' },
      { item: 'Vin rouge', quantity: '750ml' },
      { item: 'Carottes', quantity: '4' },
      { item: 'Oignons', quantity: '3' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Olives noires', quantity: '150g' },
      { item: 'Orange', quantity: '1 zeste' },
      { item: 'Bouquet garni', quantity: '1' },
    ],
    steps: [
      'Faire mariner la viande 24h dans le vin.',
      'Égoutter et faire dorer la viande.',
      'Faire revenir lardons et légumes.',
      'Ajouter la viande, le vin et le bouquet garni.',
      'Incorporer zeste d\'orange.',
      'Mijoter 3h à feu très doux.',
      'Ajouter les olives 15 min avant la fin.',
    ],
  },
  {
    id: 'stew-2',
    name: 'Navarin d\'Agneau',
    image: 'https://images.unsplash.com/photo-1600353068440-6361ef3a86e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 120,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Épaule d\'agneau', quantity: '1.2kg' },
      { item: 'Carottes nouvelles', quantity: '500g' },
      { item: 'Navets', quantity: '500g' },
      { item: 'Pommes de terre', quantity: '600g' },
      { item: 'Petits pois', quantity: '200g' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Bouquet garni', quantity: '1' },
    ],
    steps: [
      'Faire dorer les morceaux d\'agneau.',
      'Ajouter un peu de farine.',
      'Incorporer les tomates.',
      'Mouiller d\'eau, ajouter le bouquet garni.',
      'Mijoter 1h.',
      'Ajouter carottes et navets.',
      'Cuire encore 30 min.',
      'Ajouter pommes de terre et petits pois 20 min avant la fin.',
    ],
  },

  // ===== DESSERTS VARIÉS =====
  {
    id: 'dessert-1',
    name: 'Clafoutis aux Cerises',
    image: 'https://images.unsplash.com/photo-1565695472822-c7ba1e11c5c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 40,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Cerises', quantity: '600g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Lait', quantity: '300ml' },
      { item: 'Farine', quantity: '100g' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Beurre', quantity: '30g' },
      { item: 'Sucre vanillé', quantity: '1 sachet' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Beurrer un moule.',
      'Disposer les cerises.',
      'Battre œufs et sucre.',
      'Ajouter farine et lait.',
      'Verser sur les cerises.',
      'Cuire 40 minutes.',
    ],
  },
  {
    id: 'dessert-2',
    name: 'Panna Cotta',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 5,
    servings: 6,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Crème liquide', quantity: '500ml' },
      { item: 'Sucre', quantity: '80g' },
      { item: 'Gélatine', quantity: '3 feuilles' },
      { item: 'Gousse de vanille', quantity: '1' },
      { item: 'Coulis de fruits rouges', quantity: '200ml' },
    ],
    steps: [
      'Faire ramollir la gélatine dans l\'eau froide.',
      'Faire chauffer la crème avec sucre et vanille.',
      'Incorporer la gélatine essorée.',
      'Verser dans des verrines.',
      'Réfrigérer au moins 4h.',
      'Servir avec coulis de fruits rouges.',
    ],
  },
  {
    id: 'dessert-3',
    name: 'Brownies au Chocolat',
    image: 'https://images.unsplash.com/photo-1606312619070-d48b4f50a8e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 12,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Chocolat noir', quantity: '200g' },
      { item: 'Beurre', quantity: '150g' },
      { item: 'Sucre', quantity: '200g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Farine', quantity: '100g' },
      { item: 'Noix de pécan', quantity: '100g' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Faire fondre chocolat et beurre.',
      'Battre œufs et sucre.',
      'Incorporer le chocolat fondu.',
      'Ajouter farine et noix.',
      'Verser dans un moule.',
      'Cuire 25 min (le centre doit rester moelleux).',
    ],
  },
  {
    id: 'dessert-4',
    name: 'Cheesecake New-Yorkais',
    image: 'https://images.unsplash.com/photo-1533134486753-c833f0ed4866?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 60,
    servings: 10,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Biscuits digestive', quantity: '250g' },
      { item: 'Beurre fondu', quantity: '100g' },
      { item: 'Cream cheese', quantity: '800g' },
      { item: 'Sucre', quantity: '200g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Vanille', quantity: '2 c. à café' },
    ],
    steps: [
      'Émietter les biscuits et mélanger au beurre.',
      'Tasser dans le fond d\'un moule.',
      'Battre cream cheese et sucre.',
      'Incorporer œufs, crème et vanille.',
      'Verser sur la base.',
      'Cuire au four à 160°C pendant 1h.',
      'Laisser refroidir puis réfrigérer 6h.',
    ],
  },
  {
    id: 'dessert-5',
    name: 'Macarons Français',
    image: 'https://images.unsplash.com/photo-1571506165871-ee72a35bc9d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 60,
    cookTime: 15,
    servings: 30,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Poudre d\'amandes', quantity: '200g' },
      { item: 'Sucre glace', quantity: '200g' },
      { item: 'Blancs d\'œufs', quantity: '150g' },
      { item: 'Sucre', quantity: '50g' },
      { item: 'Colorants alimentaires', quantity: 'Au choix' },
      { item: 'Ganache', quantity: '200g' },
    ],
    steps: [
      'Tamiser poudre d\'amandes et sucre glace.',
      'Monter les blancs en neige avec le sucre.',
      'Incorporer délicatement le mélange d\'amandes.',
      'Dresser sur une plaque.',
      'Laisser croûter 30 min.',
      'Cuire à 150°C pendant 12 minutes.',
      'Garnir de ganache une fois refroidis.',
    ],
  },

  // ===== APÉRITIFS & ENTRÉES =====
  {
    id: 'starter-1',
    name: 'Houmous Maison',
    image: 'https://images.unsplash.com/photo-1588776814546-daab30f310ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pois chiches', quantity: '400g' },
      { item: 'Tahini', quantity: '4 c. à soupe' },
      { item: 'Citron', quantity: '2' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Cumin', quantity: '1 c. à café' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
      { item: 'Paprika', quantity: 'Pour décorer' },
    ],
    steps: [
      'Mixer pois chiches, tahini, jus de citron et ail.',
      'Ajouter cumin et huile d\'olive.',
      'Ajuster la consistance avec de l\'eau.',
      'Assaisonner de sel.',
      'Servir avec un filet d\'huile et paprika.',
      'Accompagner de pain pita.',
    ],
  },
  {
    id: 'starter-2',
    name: 'Verrines de Guacamole',
    image: 'https://images.unsplash.com/photo-1604908815541-ae5e2b7e4c2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 0,
    servings: 8,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Avocats', quantity: '4' },
      { item: 'Tomates', quantity: '2' },
      { item: 'Oignon rouge', quantity: '1' },
      { item: 'Citron vert', quantity: '2' },
      { item: 'Coriandre', quantity: '1 bouquet' },
      { item: 'Piment', quantity: '1' },
    ],
    steps: [
      'Écraser les avocats à la fourchette.',
      'Concasser les tomates.',
      'Émincer finement l\'oignon.',
      'Mélanger avec jus de citron.',
      'Ajouter coriandre et piment.',
      'Assaisonner de sel.',
      'Servir en verrines avec tortilla chips.',
    ],
  },
  {
    id: 'starter-3',
    name: 'Tartare de Saumon',
    image: 'https://images.unsplash.com/photo-1580217593608-61931cefc821?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Poisson',
    ingredients: [
      { item: 'Saumon frais', quantity: '400g' },
      { item: 'Avocat', quantity: '1' },
      { item: 'Échalotes', quantity: '2' },
      { item: 'Aneth', quantity: '1 bouquet' },
      { item: 'Citron', quantity: '2' },
      { item: 'Huile d\'olive', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Découper le saumon en petits dés.',
      'Couper l\'avocat en dés.',
      'Émincer finement les échalotes.',
      'Mélanger avec jus de citron et huile.',
      'Ciseler l\'aneth.',
      'Assaisonner de sel et poivre.',
      'Servir frais avec blinis ou toast.',
    ],
  },
  {
    id: 'starter-4',
    name: 'Foie Gras Poêlé',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 5,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Foie gras cru', quantity: '400g' },
      { item: 'Pain d\'épices', quantity: '4 tranches' },
      { item: 'Figues fraîches', quantity: '4' },
      { item: 'Vinaigre balsamique', quantity: '2 c. à soupe' },
      { item: 'Miel', quantity: '1 c. à soupe' },
      { item: 'Fleur de sel', quantity: 'Au goût' },
    ],
    steps: [
      'Trancher le foie gras en escalopes.',
      'Chauffer une poêle très chaude.',
      'Saisir le foie gras 1 min de chaque côté.',
      'Toaster le pain d\'épices.',
      'Couper les figues en quartiers.',
      'Préparer une réduction vinaigre-miel.',
      'Servir avec fleur de sel.',
    ],
  },
  {
    id: 'starter-5',
    name: 'Carpaccio de Bœuf',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Filet de bœuf', quantity: '400g' },
      { item: 'Roquette', quantity: '100g' },
      { item: 'Parmesan', quantity: '80g' },
      { item: 'Citron', quantity: '2' },
      { item: 'Huile d\'olive', quantity: '6 c. à soupe' },
      { item: 'Pignons de pin', quantity: '30g' },
    ],
    steps: [
      'Congeler le bœuf 30 min pour faciliter la découpe.',
      'Trancher très finement.',
      'Disposer sur des assiettes.',
      'Arroser de jus de citron et huile d\'olive.',
      'Parsemer de roquette et copeaux de parmesan.',
      'Ajouter les pignons grillés.',
      'Assaisonner de poivre du moulin.',
    ],
  },
];
