// Collection MEGA de 80 recettes populaires type Marmiton
import type { Recipe } from '../components/RecipesScreen';

export const megaRecipes: Recipe[] = [
  // ===== QUICHES & TARTES SALÉES =====
  {
    id: 'mega-1',
    name: 'Quiche aux Épinards et Chèvre',
    image: 'https://images.unsplash.com/photo-1565181782289-457ee028de39?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxxdWljaGUlMjBzcGluYWNofGVufDF8fHx8MTc2MjQzNzU1OHww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pâte brisée', quantity: '1' },
      { item: 'Épinards frais', quantity: '400g' },
      { item: 'Fromage de chèvre', quantity: '150g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Muscade', quantity: '1 pincée' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Faire revenir les épinards et l\'oignon.',
      'Étaler la pâte dans un moule.',
      'Battre œufs et crème avec muscade.',
      'Disposer épinards et chèvre sur la pâte.',
      'Verser l\'appareil à quiche.',
      'Cuire 40 minutes.',
    ],
  },
  {
    id: 'mega-2',
    name: 'Tarte aux Poireaux',
    image: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pâte feuilletée', quantity: '1' },
      { item: 'Poireaux', quantity: '4' },
      { item: 'Lardons', quantity: '150g' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Gruyère', quantity: '80g' },
    ],
    steps: [
      'Émincer et faire fondre les poireaux.',
      'Faire revenir les lardons.',
      'Mélanger crème et œufs.',
      'Étaler la pâte.',
      'Disposer poireaux et lardons.',
      'Verser la crème.',
      'Saupoudrer de gruyère et cuire 35 min.',
    ],
  },

  // ===== PLATS MIJOTÉS & CLASSIQUES =====
  {
    id: 'mega-3',
    name: 'Poulet Tikka Masala',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwdGlra2F8ZW58MXx8fHwxNzYyMzI4NzQzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 35,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Indien',
    ingredients: [
      { item: 'Poulet', quantity: '800g' },
      { item: 'Yaourt', quantity: '150g' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Crème liquide', quantity: '200ml' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Garam masala', quantity: '2 c. à soupe' },
      { item: 'Curcuma', quantity: '1 c. à café' },
      { item: 'Gingembre', quantity: '1 morceau' },
    ],
    steps: [
      'Faire mariner le poulet dans yaourt et épices 2h.',
      'Griller le poulet au four.',
      'Faire revenir oignons, gingembre et épices.',
      'Ajouter tomates et mijoter.',
      'Incorporer le poulet et la crème.',
      'Laisser mijoter 15 minutes.',
      'Servir avec riz basmati et naan.',
    ],
  },
  {
    id: 'mega-4',
    name: 'Bœuf Bourguignon Express',
    image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWVmJTIwc3Rld3xlbnwxfHx8fDE3NjI0MTY3NDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 25,
    cookTime: 90,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Bœuf à braiser', quantity: '1kg' },
      { item: 'Vin rouge', quantity: '500ml' },
      { item: 'Carottes', quantity: '3' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Lardons', quantity: '150g' },
      { item: 'Champignons', quantity: '250g' },
      { item: 'Bouquet garni', quantity: '1' },
      { item: 'Farine', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Faire dorer le bœuf.',
      'Ajouter carottes, oignons et lardons.',
      'Saupoudrer de farine.',
      'Mouiller au vin rouge.',
      'Ajouter bouquet garni.',
      'Mijoter 1h30.',
      'Ajouter champignons 20 min avant la fin.',
    ],
  },
  {
    id: 'mega-5',
    name: 'Hachis Parmentier',
    image: 'https://images.unsplash.com/photo-1753289595628-e3732ce60039?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaGVwaGVyZCUyMHBpZXxlbnwxfHx8fDE3NjI0Mzc0NDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Viande hachée', quantity: '600g' },
      { item: 'Pommes de terre', quantity: '1kg' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Lait', quantity: '150ml' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Gruyère râpé', quantity: '100g' },
      { item: 'Concentré de tomate', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Cuire et écraser les pommes de terre avec lait et beurre.',
      'Faire revenir oignons et viande.',
      'Ajouter concentré de tomate.',
      'Disposer la viande dans un plat.',
      'Recouvrir de purée.',
      'Parsemer de gruyère.',
      'Gratiner au four 25 minutes à 200°C.',
    ],
  },
  {
    id: 'mega-6',
    name: 'Poulet Basquaise',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 50,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Poulet', quantity: '1.2kg' },
      { item: 'Poivrons', quantity: '3' },
      { item: 'Tomates', quantity: '6' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Jambon de Bayonne', quantity: '150g' },
      { item: 'Vin blanc', quantity: '150ml' },
      { item: 'Piment d\'Espelette', quantity: '1 c. à café' },
    ],
    steps: [
      'Faire dorer les morceaux de poulet.',
      'Ajouter oignons et poivrons émincés.',
      'Incorporer tomates concassées et jambon.',
      'Déglacer au vin blanc.',
      'Ajouter piment d\'Espelette.',
      'Mijoter 40 minutes à couvert.',
      'Servir avec du riz.',
    ],
  },

  // ===== POISSONS =====
  {
    id: 'mega-7',
    name: 'Pavé de Saumon au Miel',
    image: 'https://images.unsplash.com/photo-1707576517985-a2e912cca325?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYWxtb24lMjBncmlsbGVkfGVufDF8fHx8MTc2MjQzNzU2MHww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Poisson',
    ingredients: [
      { item: 'Pavés de saumon', quantity: '4' },
      { item: 'Miel', quantity: '3 c. à soupe' },
      { item: 'Sauce soja', quantity: '2 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Citron', quantity: '1' },
      { item: 'Graines de sésame', quantity: '1 c. à soupe' },
    ],
    steps: [
      'Mélanger miel, sauce soja, gingembre râpé et jus de citron.',
      'Faire mariner le saumon 15 min.',
      'Cuire le saumon à la poêle 5 min de chaque côté.',
      'Napper de marinade réduite.',
      'Parsemer de graines de sésame.',
      'Servir avec riz et légumes vapeur.',
    ],
  },
  {
    id: 'mega-8',
    name: 'Fish Cakes',
    image: 'https://images.unsplash.com/photo-1579208570378-8c970854bc23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Poisson',
    ingredients: [
      { item: 'Cabillaud', quantity: '400g' },
      { item: 'Pommes de terre', quantity: '400g' },
      { item: 'Œuf', quantity: '1' },
      { item: 'Oignon vert', quantity: '3' },
      { item: 'Persil', quantity: '1 bouquet' },
      { item: 'Chapelure', quantity: '100g' },
      { item: 'Citron', quantity: '1' },
    ],
    steps: [
      'Cuire le poisson à la vapeur.',
      'Cuire et écraser les pommes de terre.',
      'Émietter le poisson.',
      'Mélanger avec purée, œuf, oignons et persil.',
      'Former des galettes.',
      'Paner dans la chapelure.',
      'Faire dorer à la poêle.',
    ],
  },
  {
    id: 'mega-9',
    name: 'Brandade de Morue',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 25,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Morue salée', quantity: '600g' },
      { item: 'Pommes de terre', quantity: '500g' },
      { item: 'Lait', quantity: '300ml' },
      { item: 'Huile d\'olive', quantity: '150ml' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Persil', quantity: '1 bouquet' },
    ],
    steps: [
      'Dessaler la morue 24h.',
      'Pocher la morue dans le lait.',
      'Cuire les pommes de terre.',
      'Émietter le poisson.',
      'Écraser avec pommes de terre et ail.',
      'Incorporer l\'huile en fouettant.',
      'Gratiner au four 15 minutes.',
    ],
  },

  // ===== PÂTES VARIÉES =====
  {
    id: 'mega-10',
    name: 'Pâtes au Pesto',
    image: 'https://images.unsplash.com/photo-1567608285969-48e4bbe0d399?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXN0YSUyMHBlc3RvfGVufDF8fHx8MTc2MjQyNTg3OHww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes', quantity: '400g' },
      { item: 'Basilic frais', quantity: '100g' },
      { item: 'Pignons de pin', quantity: '50g' },
      { item: 'Parmesan', quantity: '80g' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Huile d\'olive', quantity: '150ml' },
    ],
    steps: [
      'Mixer basilic, pignons, parmesan et ail.',
      'Incorporer l\'huile progressivement.',
      'Cuire les pâtes al dente.',
      'Mélanger avec le pesto.',
      'Ajouter un peu d\'eau de cuisson.',
      'Servir avec parmesan supplémentaire.',
    ],
  },
  {
    id: 'mega-11',
    name: 'Pâtes à la Norma',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes', quantity: '400g' },
      { item: 'Aubergines', quantity: '2' },
      { item: 'Tomates', quantity: '600g' },
      { item: 'Ricotta salée', quantity: '100g' },
      { item: 'Basilic', quantity: '1 bouquet' },
      { item: 'Ail', quantity: '2 gousses' },
    ],
    steps: [
      'Couper et faire dégorger les aubergines.',
      'Les faire frire.',
      'Préparer une sauce tomate à l\'ail.',
      'Cuire les pâtes.',
      'Mélanger avec sauce et aubergines.',
      'Parsemer de ricotta et basilic.',
    ],
  },
  {
    id: 'mega-12',
    name: 'One Pot Pasta',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Spaghetti', quantity: '400g' },
      { item: 'Tomates cerises', quantity: '300g' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Basilic', quantity: '1 bouquet' },
      { item: 'Bouillon', quantity: '750ml' },
      { item: 'Parmesan', quantity: '80g' },
    ],
    steps: [
      'Mettre tous les ingrédients dans une casserole.',
      'Casser les pâtes en deux.',
      'Couvrir de bouillon.',
      'Cuire 12 minutes en remuant.',
      'L\'eau doit être absorbée.',
      'Ajouter parmesan et basilic.',
      'Servir immédiatement.',
    ],
  },

  // ===== PIZZAS & TARTES FLAMBÉES =====
  {
    id: 'mega-13',
    name: 'Pizza Pepperoni',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaXp6YSUyMHBlcHBlcm9uaXxlbnwxfHx8fDE3NjIzNzM5ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 90,
    cookTime: 12,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pâte à pizza', quantity: '1' },
      { item: 'Sauce tomate', quantity: '200g' },
      { item: 'Mozzarella', quantity: '250g' },
      { item: 'Pepperoni', quantity: '150g' },
      { item: 'Origan', quantity: '1 c. à café' },
    ],
    steps: [
      'Étaler la pâte finement.',
      'Napper de sauce tomate.',
      'Ajouter mozzarella et pepperoni.',
      'Saupoudrer d\'origan.',
      'Cuire au four très chaud 12 minutes.',
      'Servir immédiatement.',
    ],
  },
  {
    id: 'mega-14',
    name: 'Tarte Flambée',
    image: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pâte à pain', quantity: '400g' },
      { item: 'Crème fraîche épaisse', quantity: '200g' },
      { item: 'Oignons', quantity: '3' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Fromage blanc', quantity: '100g' },
    ],
    steps: [
      'Étaler la pâte très finement.',
      'Mélanger crème fraîche et fromage blanc.',
      'Étaler sur la pâte.',
      'Disposer oignons émincés et lardons.',
      'Cuire au four très chaud 8-10 minutes.',
      'Servir immédiatement.',
    ],
  },
  {
    id: 'mega-15',
    name: 'Pizza Reine',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 90,
    cookTime: 12,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pâte à pizza', quantity: '1' },
      { item: 'Sauce tomate', quantity: '200g' },
      { item: 'Mozzarella', quantity: '250g' },
      { item: 'Jambon', quantity: '150g' },
      { item: 'Champignons', quantity: '150g' },
    ],
    steps: [
      'Étaler la pâte.',
      'Napper de sauce tomate.',
      'Ajouter mozzarella, jambon et champignons.',
      'Cuire au four à 250°C pendant 12 minutes.',
      'Servir chaud.',
    ],
  },

  // ===== SOUPES & VELOUTÉS =====
  {
    id: 'mega-16',
    name: 'Soupe de Lentilles Corail',
    image: 'https://images.unsplash.com/photo-1683743127028-7389d247337b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb3VwJTIwbGVudGlsfGVufDF8fHx8MTc2MjQzNzU2Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: 'Facile',
    category: 'Soupe',
    ingredients: [
      { item: 'Lentilles corail', quantity: '300g' },
      { item: 'Carottes', quantity: '3' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Lait de coco', quantity: '200ml' },
      { item: 'Curry', quantity: '2 c. à soupe' },
      { item: 'Bouillon de légumes', quantity: '1L' },
      { item: 'Cumin', quantity: '1 c. à café' },
    ],
    steps: [
      'Faire revenir oignon et carottes.',
      'Ajouter curry et cumin.',
      'Incorporer lentilles et bouillon.',
      'Cuire 25 minutes.',
      'Mixer finement.',
      'Ajouter le lait de coco.',
      'Servir avec coriandre fraîche.',
    ],
  },
  {
    id: 'mega-17',
    name: 'Gazpacho Andalou',
    image: 'https://images.unsplash.com/photo-1662469853918-c615ffb1e030?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYXpwYWNobyUyMHNvdXB8ZW58MXx8fHwxNzYyNDM3NTY1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 0,
    servings: 6,
    difficulty: 'Facile',
    category: 'Espagnol',
    ingredients: [
      { item: 'Tomates', quantity: '1kg' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Poivron rouge', quantity: '1' },
      { item: 'Oignon rouge', quantity: '1' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Vinaigre de Xérès', quantity: '2 c. à soupe' },
      { item: 'Huile d\'olive', quantity: '100ml' },
      { item: 'Pain rassis', quantity: '100g' },
    ],
    steps: [
      'Faire tremper le pain.',
      'Mixer tous les légumes avec pain, ail et vinaigre.',
      'Incorporer l\'huile progressivement.',
      'Assaisonner de sel et poivre.',
      'Réfrigérer au moins 2h.',
      'Servir très frais.',
      'Accompagner de croûtons.',
    ],
  },
  {
    id: 'mega-18',
    name: 'Velouté de Champignons',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: 'Facile',
    category: 'Soupe',
    ingredients: [
      { item: 'Champignons de Paris', quantity: '600g' },
      { item: 'Pomme de terre', quantity: '1' },
      { item: 'Échalotes', quantity: '2' },
      { item: 'Bouillon de volaille', quantity: '1L' },
      { item: 'Crème liquide', quantity: '150ml' },
      { item: 'Beurre', quantity: '30g' },
    ],
    steps: [
      'Émincer champignons et échalotes.',
      'Faire revenir dans le beurre.',
      'Ajouter pomme de terre coupée.',
      'Mouiller avec le bouillon.',
      'Cuire 25 minutes.',
      'Mixer finement.',
      'Incorporer la crème et servir.',
    ],
  },

  // ===== RISOTTOS =====
  {
    id: 'mega-19',
    name: 'Risotto aux Cèpes',
    image: 'https://images.unsplash.com/photo-1723476657955-7c2ad073f6c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyaXNvdHRvJTIwbXVzaHJvb218ZW58MXx8fHwxNzYyNDM3NTYzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Riz arborio', quantity: '320g' },
      { item: 'Cèpes séchés', quantity: '50g' },
      { item: 'Champignons frais', quantity: '200g' },
      { item: 'Bouillon de volaille', quantity: '1.5L' },
      { item: 'Vin blanc', quantity: '100ml' },
      { item: 'Parmesan', quantity: '80g' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Échalote', quantity: '1' },
    ],
    steps: [
      'Réhydrater les cèpes.',
      'Faire chauffer le bouillon.',
      'Faire revenir l\'échalote.',
      'Ajouter le riz et nacrer.',
      'Déglacer au vin blanc.',
      'Ajouter bouillon louche par louche.',
      'Incorporer champignons, beurre et parmesan.',
    ],
  },
  {
    id: 'mega-20',
    name: 'Risotto aux Asperges',
    image: 'https://images.unsplash.com/photo-1476124369491-f117991cdc65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Riz arborio', quantity: '320g' },
      { item: 'Asperges vertes', quantity: '500g' },
      { item: 'Bouillon de légumes', quantity: '1.5L' },
      { item: 'Vin blanc', quantity: '100ml' },
      { item: 'Parmesan', quantity: '80g' },
      { item: 'Beurre', quantity: '50g' },
    ],
    steps: [
      'Couper les asperges, garder les pointes.',
      'Cuire les tiges dans le bouillon.',
      'Faire revenir le riz.',
      'Déglacer au vin blanc.',
      'Ajouter bouillon louche par louche.',
      'Ajouter les pointes 5 min avant la fin.',
      'Terminer avec beurre et parmesan.',
    ],
  },

  // ===== VIANDES RÔTIES =====
  {
    id: 'mega-21',
    name: 'Côtelettes d\'Agneau',
    image: 'https://images.unsplash.com/photo-1692106914421-e04e1066bd62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYW1iJTIwY2hvcHN8ZW58MXx8fHwxNzYyNDEzNTE4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 12,
    servings: 4,
    difficulty: 'Facile',
    category: 'Viande',
    ingredients: [
      { item: 'Côtelettes d\'agneau', quantity: '8' },
      { item: 'Romarin', quantity: '4 branches' },
      { item: 'Ail', quantity: '4 gousses' },
      { item: 'Huile d\'olive', quantity: '3 c. à soupe' },
      { item: 'Fleur de sel', quantity: 'Au goût' },
    ],
    steps: [
      'Faire mariner les côtelettes avec romarin et ail.',
      'Chauffer une poêle très chaude.',
      'Saisir 3 min de chaque côté.',
      'Assaisonner de fleur de sel.',
      'Laisser reposer 5 minutes.',
      'Servir avec légumes grillés.',
    ],
  },
  {
    id: 'mega-22',
    name: 'Rôti de Porc au Lait',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 90,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Viande',
    ingredients: [
      { item: 'Rôti de porc', quantity: '1kg' },
      { item: 'Lait', quantity: '1L' },
      { item: 'Ail', quantity: '1 tête' },
      { item: 'Sauge', quantity: '6 feuilles' },
      { item: 'Beurre', quantity: '30g' },
      { item: 'Citron', quantity: '1 zeste' },
    ],
    steps: [
      'Faire dorer le rôti dans le beurre.',
      'Ajouter ail, sauge et zeste de citron.',
      'Verser le lait chaud.',
      'Couvrir et cuire au four à 160°C pendant 1h30.',
      'Le lait doit cailler et former une sauce.',
      'Trancher et servir avec la sauce.',
    ],
  },

  // ===== DESSERTS POPULAIRES =====
  {
    id: 'mega-23',
    name: 'Crumble aux Pommes',
    image: 'https://images.unsplash.com/photo-1706799419621-14d7f424de83?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcnVtYmxlJTIwYXBwbGV8ZW58MXx8fHwxNzYyNDM3NTU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pommes', quantity: '6' },
      { item: 'Farine', quantity: '150g' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Sucre roux', quantity: '100g' },
      { item: 'Cannelle', quantity: '1 c. à café' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Éplucher et couper les pommes.',
      'Les disposer dans un plat.',
      'Mélanger farine, beurre et sucre du bout des doigts.',
      'Répartir sur les pommes.',
      'Saupoudrer de cannelle.',
      'Cuire 35 minutes.',
    ],
  },
  {
    id: 'mega-24',
    name: 'Tiramisu Classique',
    image: 'https://images.unsplash.com/photo-1714385905983-6f8e06fffae1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aXJhbWlzdSUyMGRlc3NlcnR8ZW58MXx8fHwxNzYyMzYxNjUzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Mascarpone', quantity: '500g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Biscuits à la cuillère', quantity: '250g' },
      { item: 'Café fort', quantity: '300ml' },
      { item: 'Cacao en poudre', quantity: '30g' },
      { item: 'Amaretto', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Séparer blancs et jaunes d\'œufs.',
      'Battre jaunes avec le sucre.',
      'Incorporer le mascarpone.',
      'Monter les blancs en neige et incorporer.',
      'Tremper les biscuits dans le café.',
      'Alterner biscuits et crème.',
      'Saupoudrer de cacao et réfrigérer 4h.',
    ],
  },
  {
    id: 'mega-25',
    name: 'Gâteau au Chocolat Fondant',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaG9jb2xhdGUlMjBjYWtlfGVufDF8fHx8MTc2MjQwMjYwNHww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Chocolat noir', quantity: '200g' },
      { item: 'Beurre', quantity: '150g' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Farine', quantity: '80g' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Faire fondre chocolat et beurre.',
      'Battre œufs et sucre.',
      'Incorporer le chocolat fondu.',
      'Ajouter la farine.',
      'Verser dans un moule beurré.',
      'Cuire 25 minutes.',
    ],
  },
  {
    id: 'mega-26',
    name: 'Tarte aux Fraises',
    image: 'https://images.unsplash.com/photo-1560529666-317819712619?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YXJ0JTIwc3RyYXdiZXJyeXxlbnwxfHx8fDE3NjI0Mzc1NjN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 25,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte sablée', quantity: '1' },
      { item: 'Fraises', quantity: '500g' },
      { item: 'Crème pâtissière', quantity: '400ml' },
      { item: 'Nappage neutre', quantity: '100g' },
    ],
    steps: [
      'Cuire la pâte à blanc 20 minutes.',
      'Laisser refroidir.',
      'Étaler la crème pâtissière.',
      'Disposer les fraises.',
      'Faire chauffer le nappage.',
      'Badigeonner les fraises.',
      'Réfrigérer 1h avant de servir.',
    ],
  },
  {
    id: 'mega-27',
    name: 'Flan Pâtissier',
    image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 45,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte brisée', quantity: '1' },
      { item: 'Lait', quantity: '1L' },
      { item: 'Œufs', quantity: '6' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Maïzena', quantity: '100g' },
      { item: 'Vanille', quantity: '1 gousse' },
    ],
    steps: [
      'Étaler la pâte dans un moule.',
      'Faire bouillir le lait avec la vanille.',
      'Battre œufs, sucre et maïzena.',
      'Verser le lait chaud progressivement.',
      'Verser dans le moule.',
      'Cuire au four à 180°C pendant 45 minutes.',
      'Laisser refroidir complètement.',
    ],
  },

  // ===== PETITS-DÉJEUNERS =====
  {
    id: 'mega-28',
    name: 'Pain Perdu',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVuY2glMjB0b2FzdHxlbnwxfHx8fDE3NjIzNzM5OTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Brunch',
    ingredients: [
      { item: 'Pain de mie', quantity: '8 tranches' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Lait', quantity: '200ml' },
      { item: 'Sucre', quantity: '50g' },
      { item: 'Vanille', quantity: '1 c. à café' },
      { item: 'Beurre', quantity: '30g' },
    ],
    steps: [
      'Battre œufs, lait, sucre et vanille.',
      'Tremper les tranches de pain.',
      'Faire dorer dans le beurre.',
      'Servir chaud avec sucre ou sirop d\'érable.',
    ],
  },
  {
    id: 'mega-29',
    name: 'Croissants Maison',
    image: 'https://images.unsplash.com/photo-1618667060775-1fe102237f94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9pc3NhbnQlMjBicmVha2Zhc3R8ZW58MXx8fHwxNzYyNDM3NTY0fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 180,
    cookTime: 15,
    servings: 12,
    difficulty: 'Difficile',
    category: 'Brunch',
    ingredients: [
      { item: 'Farine', quantity: '500g' },
      { item: 'Beurre', quantity: '250g' },
      { item: 'Lait', quantity: '250ml' },
      { item: 'Sucre', quantity: '50g' },
      { item: 'Levure boulangère', quantity: '15g' },
      { item: 'Sel', quantity: '10g' },
      { item: 'Jaune d\'œuf', quantity: '1' },
    ],
    steps: [
      'Préparer la détrempe: farine, lait, levure, sucre, sel.',
      'Laisser lever 1h.',
      'Incorporer le beurre en pliant.',
      'Faire 3 tours simples avec repos.',
      'Étaler et découper des triangles.',
      'Rouler en croissants.',
      'Laisser lever 2h, dorer et cuire 15 min à 200°C.',
    ],
  },
  {
    id: 'mega-30',
    name: 'Omelette au Fromage',
    image: 'https://images.unsplash.com/photo-1732969331543-80e52902e0a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvbWVsZXR0ZSUyMGNoZWVzZXxlbnwxfHx8fDE3NjI0Mzc1NjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    difficulty: 'Facile',
    category: 'Brunch',
    ingredients: [
      { item: 'Œufs', quantity: '6' },
      { item: 'Gruyère râpé', quantity: '80g' },
      { item: 'Beurre', quantity: '20g' },
      { item: 'Lait', quantity: '2 c. à soupe' },
      { item: 'Ciboulette', quantity: '1 c. à soupe' },
    ],
    steps: [
      'Battre les œufs avec le lait.',
      'Faire fondre le beurre.',
      'Verser les œufs.',
      'Ajouter le fromage quand ça commence à prendre.',
      'Plier en deux.',
      'Servir immédiatement avec ciboulette.',
    ],
  },
  {
    id: 'mega-31',
    name: 'Crêpes au Nutella',
    image: 'https://images.unsplash.com/photo-1695518069327-60d7601794a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmVwZSUyMG51dGVsbGF8ZW58MXx8fHwxNzYyNDM3NTY1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '250g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Lait', quantity: '500ml' },
      { item: 'Sucre', quantity: '2 c. à soupe' },
      { item: 'Beurre fondu', quantity: '50g' },
      { item: 'Nutella', quantity: '200g' },
    ],
    steps: [
      'Mélanger farine, œufs et sucre.',
      'Ajouter lait et beurre fondu.',
      'Laisser reposer 1h.',
      'Cuire des crêpes fines.',
      'Tartiner de Nutella.',
      'Plier en quatre et servir.',
    ],
  },

  // ===== APÉRITIFS & ENTRÉES =====
  {
    id: 'mega-32',
    name: 'Bruschetta Tomate Basilic',
    image: 'https://images.unsplash.com/photo-1630230596557-ad07b433f5c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicnVzY2hldHRhJTIwdG9tYXRvfGVufDF8fHx8MTc2MjM5MjEwMnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 5,
    servings: 6,
    difficulty: 'Facile',
    category: 'Apéritif',
    ingredients: [
      { item: 'Pain de campagne', quantity: '1' },
      { item: 'Tomates', quantity: '6' },
      { item: 'Basilic frais', quantity: '1 bouquet' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Huile d\'olive', quantity: '6 c. à soupe' },
      { item: 'Vinaigre balsamique', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Couper le pain en tranches.',
      'Griller au four.',
      'Frotter avec l\'ail.',
      'Concasser les tomates.',
      'Mélanger avec basilic, huile et vinaigre.',
      'Disposer sur les tranches de pain.',
      'Servir immédiatement.',
    ],
  },
  {
    id: 'mega-33',
    name: 'Cake Salé Olives Jambon',
    image: 'https://images.unsplash.com/photo-1587740896339-96a76170508d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 45,
    servings: 8,
    difficulty: 'Facile',
    category: 'Apéritif',
    ingredients: [
      { item: 'Farine', quantity: '200g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Lait', quantity: '100ml' },
      { item: 'Huile', quantity: '100ml' },
      { item: 'Levure', quantity: '1 sachet' },
      { item: 'Jambon', quantity: '150g' },
      { item: 'Olives', quantity: '100g' },
      { item: 'Gruyère', quantity: '100g' },
    ],
    steps: [
      'Mélanger farine et levure.',
      'Battre œufs, lait et huile.',
      'Incorporer aux ingrédients secs.',
      'Ajouter jambon, olives et gruyère.',
      'Verser dans un moule.',
      'Cuire à 180°C pendant 45 minutes.',
      'Laisser refroidir avant de démouler.',
    ],
  },
  {
    id: 'mega-34',
    name: 'Mini-Quiches Apéritives',
    image: 'https://images.unsplash.com/photo-1565181782289-457ee028de39?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 20,
    servings: 12,
    difficulty: 'Facile',
    category: 'Apéritif',
    ingredients: [
      { item: 'Pâte feuilletée', quantity: '1' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Crème fraîche', quantity: '150ml' },
      { item: 'Lardons', quantity: '100g' },
      { item: 'Gruyère', quantity: '60g' },
    ],
    steps: [
      'Découper des cercles de pâte.',
      'Les disposer dans des moules à muffins.',
      'Faire revenir les lardons.',
      'Battre œufs et crème.',
      'Garnir les fonds avec lardons et gruyère.',
      'Verser l\'appareil.',
      'Cuire 20 minutes à 180°C.',
    ],
  },

  // ===== PLATS VÉGÉTARIENS SUPPLÉMENTAIRES =====
  {
    id: 'mega-35',
    name: 'Chili Végétarien',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Haricots rouges', quantity: '800g' },
      { item: 'Haricots noirs', quantity: '400g' },
      { item: 'Tomates concassées', quantity: '800g' },
      { item: 'Maïs', quantity: '200g' },
      { item: 'Poivrons', quantity: '2' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Cumin', quantity: '2 c. à soupe' },
      { item: 'Piment', quantity: '1 c. à café' },
    ],
    steps: [
      'Faire revenir oignons et poivrons.',
      'Ajouter les épices.',
      'Incorporer tomates et haricots.',
      'Ajouter le maïs.',
      'Mijoter 30 minutes.',
      'Rectifier l\'assaisonnement.',
      'Servir avec riz et crème fraîche.',
    ],
  },
  {
    id: 'mega-36',
    name: 'Courgettes Farcies Végétariennes',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 40,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Végétarien',
    ingredients: [
      { item: 'Courgettes', quantity: '4' },
      { item: 'Quinoa', quantity: '150g' },
      { item: 'Tomates', quantity: '3' },
      { item: 'Feta', quantity: '150g' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Herbes de Provence', quantity: '1 c. à soupe' },
    ],
    steps: [
      'Couper les courgettes en deux et évider.',
      'Cuire le quinoa.',
      'Faire revenir oignon et chair des courgettes.',
      'Mélanger avec quinoa, tomates et feta.',
      'Farcir les courgettes.',
      'Cuire au four 40 minutes à 180°C.',
      'Servir chaud.',
    ],
  },
  {
    id: 'mega-37',
    name: 'Curry de Pois Chiches',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pois chiches', quantity: '800g' },
      { item: 'Lait de coco', quantity: '400ml' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Épinards', quantity: '200g' },
      { item: 'Curry', quantity: '3 c. à soupe' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Ail', quantity: '2 gousses' },
    ],
    steps: [
      'Faire revenir oignon et ail.',
      'Ajouter le curry.',
      'Incorporer pois chiches et tomates.',
      'Verser le lait de coco.',
      'Mijoter 20 minutes.',
      'Ajouter les épinards en fin de cuisson.',
      'Servir avec naan ou riz.',
    ],
  },

  // ===== PLATS D'ÉTÉ =====
  {
    id: 'mega-38',
    name: 'Salade de Pâtes',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 10,
    servings: 6,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Pâtes courtes', quantity: '400g' },
      { item: 'Tomates cerises', quantity: '300g' },
      { item: 'Mozzarella', quantity: '250g' },
      { item: 'Basilic', quantity: '1 bouquet' },
      { item: 'Pesto', quantity: '4 c. à soupe' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
    ],
    steps: [
      'Cuire les pâtes al dente.',
      'Rincer à l\'eau froide.',
      'Couper tomates et mozzarella.',
      'Mélanger avec pâtes, pesto et huile.',
      'Ajouter le basilic ciselé.',
      'Réfrigérer avant de servir.',
    ],
  },
  {
    id: 'mega-39',
    name: 'Wraps au Poulet',
    image: 'https://images.unsplash.com/photo-1626200419455-0348c232b193?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Rapide',
    ingredients: [
      { item: 'Tortillas', quantity: '4' },
      { item: 'Poulet', quantity: '400g' },
      { item: 'Salade', quantity: '1' },
      { item: 'Tomates', quantity: '2' },
      { item: 'Sauce caesar', quantity: '100ml' },
      { item: 'Parmesan', quantity: '50g' },
    ],
    steps: [
      'Faire griller le poulet.',
      'Trancher finement.',
      'Chauffer les tortillas.',
      'Garnir de salade, tomates et poulet.',
      'Ajouter sauce et parmesan.',
      'Rouler fermement.',
      'Couper en deux et servir.',
    ],
  },
  {
    id: 'mega-40',
    name: 'Pan Bagnat',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pain rond', quantity: '4' },
      { item: 'Thon', quantity: '200g' },
      { item: 'Tomates', quantity: '3' },
      { item: 'Œufs durs', quantity: '4' },
      { item: 'Olives noires', quantity: '100g' },
      { item: 'Poivrons grillés', quantity: '2' },
      { item: 'Anchois', quantity: '8 filets' },
      { item: 'Huile d\'olive', quantity: '6 c. à soupe' },
    ],
    steps: [
      'Couper les pains en deux.',
      'Les arroser d\'huile d\'olive.',
      'Frotter avec de l\'ail.',
      'Garnir de tomates, œufs, thon.',
      'Ajouter olives, poivrons et anchois.',
      'Refermer et presser.',
      'Emballer et réfrigérer 2h.',
    ],
  },

  // ===== PLATS RÉCONFORTANTS =====
  {
    id: 'mega-41',
    name: 'Soupe à l\'Oignon',
    image: 'https://images.unsplash.com/photo-1549203438-a7696aed4dac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 50,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Oignons', quantity: '1kg' },
      { item: 'Bouillon de bœuf', quantity: '1.5L' },
      { item: 'Vin blanc', quantity: '150ml' },
      { item: 'Pain', quantity: '12 tranches' },
      { item: 'Gruyère', quantity: '200g' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Thym', quantity: '2 branches' },
    ],
    steps: [
      'Émincer finement les oignons.',
      'Les faire caraméliser 30 min dans le beurre.',
      'Déglacer au vin blanc.',
      'Ajouter bouillon et thym.',
      'Mijoter 20 minutes.',
      'Verser dans des bols.',
      'Ajouter pain et gruyère, gratiner.',
    ],
  },
  {
    id: 'mega-42',
    name: 'Fondue Savoyarde',
    image: 'https://images.unsplash.com/photo-1612392062798-2dd90f5e4b22?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Comté', quantity: '400g' },
      { item: 'Beaufort', quantity: '400g' },
      { item: 'Emmental', quantity: '200g' },
      { item: 'Vin blanc', quantity: '400ml' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Kirsch', quantity: '4 cl' },
      { item: 'Pain', quantity: '1kg' },
      { item: 'Maïzena', quantity: '1 c. à soupe' },
    ],
    steps: [
      'Frotter le caquelon avec l\'ail.',
      'Faire chauffer le vin blanc.',
      'Ajouter les fromages râpés progressivement.',
      'Mélanger constamment.',
      'Délayer la maïzena dans le kirsch.',
      'Incorporer à la fondue.',
      'Servir avec des cubes de pain.',
    ],
  },

  // ===== PLATS INTERNATIONAUX SUPPLÉMENTAIRES =====
  {
    id: 'mega-43',
    name: 'Poulet à l\'Ananas',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Poulet', quantity: '600g' },
      { item: 'Ananas', quantity: '400g' },
      { item: 'Poivron', quantity: '1' },
      { item: 'Sauce soja', quantity: '3 c. à soupe' },
      { item: 'Vinaigre', quantity: '2 c. à soupe' },
      { item: 'Sucre', quantity: '2 c. à soupe' },
      { item: 'Ketchup', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Couper le poulet en morceaux.',
      'Faire revenir à feu vif.',
      'Ajouter poivron et ananas.',
      'Mélanger sauce soja, vinaigre, sucre et ketchup.',
      'Verser dans la poêle.',
      'Cuire 15 minutes.',
      'Servir avec du riz.',
    ],
  },
  {
    id: 'mega-44',
    name: 'Tortilla Espagnole',
    image: 'https://images.unsplash.com/photo-1732969331543-80e52902e0a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Espagnol',
    ingredients: [
      { item: 'Pommes de terre', quantity: '800g' },
      { item: 'Œufs', quantity: '8' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Huile d\'olive', quantity: '200ml' },
    ],
    steps: [
      'Éplucher et trancher finement les pommes de terre.',
      'Les faire confire dans l\'huile 15 min.',
      'Égoutter.',
      'Battre les œufs.',
      'Mélanger avec pommes de terre et oignons.',
      'Cuire dans une poêle 10 min de chaque côté.',
      'Servir tiède ou froid.',
    ],
  },
  {
    id: 'mega-45',
    name: 'Pad See Ew',
    image: 'https://images.unsplash.com/photo-1718964313403-2db158f67844?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Nouilles de riz larges', quantity: '400g' },
      { item: 'Poulet', quantity: '400g' },
      { item: 'Brocoli chinois', quantity: '200g' },
      { item: 'Œuf', quantity: '2' },
      { item: 'Sauce soja noire', quantity: '3 c. à soupe' },
      { item: 'Sauce d\'huître', quantity: '2 c. à soupe' },
      { item: 'Ail', quantity: '3 gousses' },
    ],
    steps: [
      'Faire tremper les nouilles.',
      'Faire revenir l\'ail.',
      'Ajouter le poulet.',
      'Pousser sur le côté, brouiller les œufs.',
      'Ajouter nouilles et légumes.',
      'Incorporer les sauces.',
      'Faire sauter à feu vif 5 minutes.',
    ],
  },

  // ===== PLATS DE FÊTES =====
  {
    id: 'mega-46',
    name: 'Chapon Farci',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 120,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Fêtes',
    ingredients: [
      { item: 'Chapon', quantity: '3kg' },
      { item: 'Chair à saucisse', quantity: '300g' },
      { item: 'Marrons', quantity: '200g' },
      { item: 'Foie gras', quantity: '100g' },
      { item: 'Cognac', quantity: '50ml' },
      { item: 'Pain de mie', quantity: '100g' },
      { item: 'Beurre', quantity: '50g' },
    ],
    steps: [
      'Préparer la farce avec chair, marrons, foie gras.',
      'Farcir le chapon.',
      'Ficeler.',
      'Badigeonner de beurre.',
      'Cuire au four à 180°C pendant 2h.',
      'Arroser régulièrement.',
      'Servir avec marrons et légumes.',
    ],
  },
  {
    id: 'mega-47',
    name: 'Saumon en Croûte',
    image: 'https://images.unsplash.com/photo-1707576517985-a2e912cca325?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 35,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Fêtes',
    ingredients: [
      { item: 'Filet de saumon', quantity: '1kg' },
      { item: 'Pâte feuilletée', quantity: '2' },
      { item: 'Épinards', quantity: '400g' },
      { item: 'Ricotta', quantity: '200g' },
      { item: 'Aneth', quantity: '1 bouquet' },
      { item: 'Jaune d\'œuf', quantity: '1' },
    ],
    steps: [
      'Faire revenir les épinards.',
      'Mélanger avec ricotta et aneth.',
      'Étaler une pâte.',
      'Disposer la moitié du saumon.',
      'Ajouter la farce aux épinards.',
      'Couvrir avec le reste du saumon.',
      'Refermer avec la seconde pâte et dorer.',
      'Cuire 35 minutes à 180°C.',
    ],
  },
  {
    id: 'mega-48',
    name: 'Bûche de Noël',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 60,
    cookTime: 12,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Œufs', quantity: '6' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Farine', quantity: '100g' },
      { item: 'Cacao', quantity: '30g' },
      { item: 'Crème au beurre', quantity: '400g' },
      { item: 'Chocolat noir', quantity: '200g' },
    ],
    steps: [
      'Battre œufs et sucre.',
      'Incorporer farine et cacao.',
      'Étaler sur une plaque et cuire 12 min.',
      'Rouler dans un torchon.',
      'Préparer la crème au beurre au chocolat.',
      'Dérouler, garnir et rouler.',
      'Glacer et décorer.',
    ],
  },

  // ===== PLATS MINCEUR =====
  {
    id: 'mega-49',
    name: 'Salade Quinoa Avocat',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Quinoa', quantity: '250g' },
      { item: 'Avocat', quantity: '2' },
      { item: 'Tomates cerises', quantity: '200g' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Feta', quantity: '150g' },
      { item: 'Citron', quantity: '2' },
      { item: 'Menthe', quantity: '1 bouquet' },
    ],
    steps: [
      'Cuire le quinoa.',
      'Laisser refroidir.',
      'Couper avocat, tomates et concombre.',
      'Mélanger avec le quinoa.',
      'Émietter la feta.',
      'Assaisonner avec jus de citron.',
      'Parsemer de menthe fraîche.',
    ],
  },
  {
    id: 'mega-50',
    name: 'Papillotes de Poisson',
    image: 'https://images.unsplash.com/photo-1707576517985-a2e912cca325?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Poisson',
    ingredients: [
      { item: 'Filets de poisson blanc', quantity: '4' },
      { item: 'Courgettes', quantity: '2' },
      { item: 'Tomates cerises', quantity: '200g' },
      { item: 'Citron', quantity: '2' },
      { item: 'Herbes de Provence', quantity: '2 c. à café' },
      { item: 'Huile d\'olive', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Préchauffer le four à 200°C.',
      'Découper 4 grands carrés de papier sulfurisé.',
      'Disposer légumes émincés.',
      'Ajouter le poisson.',
      'Arroser de citron et huile.',
      'Parsemer d\'herbes.',
      'Fermer les papillotes et cuire 20 min.',
    ],
  },

  // ===== 30 RECETTES SUPPLÉMENTAIRES RAPIDES =====
  {
    id: 'mega-51',
    name: 'Poulet Mariné au Citron',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Volaille',
    ingredients: [
      { item: 'Escalopes de poulet', quantity: '4' },
      { item: 'Citron', quantity: '2' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Thym', quantity: '2 branches' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
    ],
    steps: [
      'Mélanger jus de citron, ail haché, thym et huile.',
      'Faire mariner le poulet 2h.',
      'Faire griller à la poêle.',
      'Servir avec légumes verts.',
    ],
  },
  {
    id: 'mega-52',
    name: 'Gratin de Pâtes',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 6,
    difficulty: 'Facile',
    category: 'Pâtes',
    ingredients: [
      { item: 'Pâtes', quantity: '500g' },
      { item: 'Béchamel', quantity: '600ml' },
      { item: 'Jambon', quantity: '200g' },
      { item: 'Gruyère', quantity: '200g' },
    ],
    steps: [
      'Cuire les pâtes.',
      'Mélanger avec béchamel et jambon.',
      'Verser dans un plat.',
      'Parsemer de gruyère.',
      'Gratiner 25 min.',
    ],
  },
  {
    id: 'mega-53',
    name: 'Poêlée de Légumes',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Courgettes', quantity: '2' },
      { item: 'Poivrons', quantity: '2' },
      { item: 'Aubergine', quantity: '1' },
      { item: 'Tomates', quantity: '3' },
      { item: 'Ail', quantity: '2 gousses' },
    ],
    steps: [
      'Couper tous les légumes.',
      'Faire revenir à feu vif.',
      'Assaisonner.',
      'Servir chaud.',
    ],
  },
  {
    id: 'mega-54',
    name: 'Crêpes Salées Complètes',
    image: 'https://images.unsplash.com/photo-1695518069327-60d7601794a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Farine de sarrasin', quantity: '250g' },
      { item: 'Œufs', quantity: '8' },
      { item: 'Jambon', quantity: '8 tranches' },
      { item: 'Gruyère', quantity: '200g' },
    ],
    steps: [
      'Préparer la pâte à crêpes.',
      'Cuire les galettes.',
      'Garnir de jambon, œuf et gruyère.',
      'Plier et servir.',
    ],
  },
  {
    id: 'mega-55',
    name: 'Salade Grecque',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Tomates', quantity: '4' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Feta', quantity: '200g' },
      { item: 'Olives noires', quantity: '100g' },
      { item: 'Oignon rouge', quantity: '1' },
    ],
    steps: [
      'Couper tous les légumes.',
      'Émietter la feta.',
      'Assaisonner d\'huile d\'olive.',
      'Servir frais.',
    ],
  },
  {
    id: 'mega-56',
    name: 'Riz Cantonais',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Riz cuit', quantity: '600g' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Petits pois', quantity: '150g' },
      { item: 'Jambon', quantity: '150g' },
      { item: 'Sauce soja', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Brouiller les œufs.',
      'Faire sauter le riz.',
      'Ajouter légumes et jambon.',
      'Assaisonner de sauce soja.',
    ],
  },
  {
    id: 'mega-57',
    name: 'Tarte Fine aux Tomates',
    image: 'https://images.unsplash.com/photo-1627308595232-d0cd54b31a4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pâte feuilletée', quantity: '1' },
      { item: 'Tomates', quantity: '6' },
      { item: 'Moutarde', quantity: '2 c. à soupe' },
      { item: 'Herbes de Provence', quantity: '1 c. à soupe' },
      { item: 'Huile d\'olive', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Étaler la pâte.',
      'Badigeonner de moutarde.',
      'Disposer les tomates tranchées.',
      'Arroser d\'huile.',
      'Cuire 25 min à 200°C.',
    ],
  },
  {
    id: 'mega-58',
    name: 'Pâtes aux Légumes Grillés',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pâtes', quantity: '400g' },
      { item: 'Courgettes', quantity: '2' },
      { item: 'Aubergine', quantity: '1' },
      { item: 'Poivrons', quantity: '2' },
      { item: 'Parmesan', quantity: '80g' },
    ],
    steps: [
      'Griller les légumes.',
      'Cuire les pâtes.',
      'Mélanger ensemble.',
      'Parsemer de parmesan.',
    ],
  },
  {
    id: 'mega-59',
    name: 'Poulet Grillé BBQ',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'Facile',
    category: 'Volaille',
    ingredients: [
      { item: 'Cuisses de poulet', quantity: '8' },
      { item: 'Sauce BBQ', quantity: '200ml' },
      { item: 'Miel', quantity: '2 c. à soupe' },
      { item: 'Paprika', quantity: '1 c. à café' },
    ],
    steps: [
      'Mélanger sauce BBQ et miel.',
      'Badigeonner le poulet.',
      'Griller au four 30 min.',
      'Servir avec frites.',
    ],
  },
  {
    id: 'mega-60',
    name: 'Soupe de Poisson',
    image: 'https://images.unsplash.com/photo-1621339881990-c94ba5cf98fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 35,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Soupe',
    ingredients: [
      { item: 'Poissons mélangés', quantity: '1kg' },
      { item: 'Tomates', quantity: '4' },
      { item: 'Fenouil', quantity: '1' },
      { item: 'Safran', quantity: '1 pincée' },
      { item: 'Rouille', quantity: 'Pour servir' },
    ],
    steps: [
      'Faire revenir légumes.',
      'Ajouter poissons et safran.',
      'Couvrir d\'eau.',
      'Cuire 30 min et mixer.',
      'Servir avec rouille.',
    ],
  },
  {
    id: 'mega-61',
    name: 'Bœuf Sauté aux Oignons',
    image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Viande',
    ingredients: [
      { item: 'Bœuf émincé', quantity: '600g' },
      { item: 'Oignons', quantity: '3' },
      { item: 'Sauce soja', quantity: '3 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
    ],
    steps: [
      'Faire sauter le bœuf à feu vif.',
      'Ajouter oignons et gingembre.',
      'Assaisonner de sauce soja.',
      'Servir avec riz.',
    ],
  },
  {
    id: 'mega-62',
    name: 'Galettes de Pommes de Terre',
    image: 'https://images.unsplash.com/photo-1753289595628-e3732ce60039?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Accompagnement',
    ingredients: [
      { item: 'Pommes de terre', quantity: '800g' },
      { item: 'Œuf', quantity: '1' },
      { item: 'Farine', quantity: '3 c. à soupe' },
      { item: 'Oignon', quantity: '1' },
    ],
    steps: [
      'Râper les pommes de terre.',
      'Mélanger avec œuf et farine.',
      'Former des galettes.',
      'Faire dorer à la poêle.',
    ],
  },
  {
    id: 'mega-63',
    name: 'Salade de Lentilles',
    image: 'https://images.unsplash.com/photo-1683743127028-7389d247337b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Lentilles vertes', quantity: '300g' },
      { item: 'Tomates', quantity: '2' },
      { item: 'Oignon rouge', quantity: '1' },
      { item: 'Persil', quantity: '1 bouquet' },
      { item: 'Vinaigrette', quantity: '6 c. à soupe' },
    ],
    steps: [
      'Cuire les lentilles.',
      'Laisser refroidir.',
      'Ajouter tomates et oignon.',
      'Assaisonner de vinaigrette.',
    ],
  },
  {
    id: 'mega-64',
    name: 'Pâtes Arrabiata',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Penne', quantity: '400g' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Piment', quantity: '2' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
    ],
    steps: [
      'Faire revenir ail et piment.',
      'Ajouter les tomates.',
      'Mijoter 15 min.',
      'Cuire les pâtes et mélanger.',
    ],
  },
  {
    id: 'mega-65',
    name: 'Poulet Curry Coco',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Poulet', quantity: '600g' },
      { item: 'Lait de coco', quantity: '400ml' },
      { item: 'Curry', quantity: '3 c. à soupe' },
      { item: 'Oignon', quantity: '1' },
    ],
    steps: [
      'Faire revenir poulet et oignon.',
      'Ajouter curry.',
      'Verser lait de coco.',
      'Mijoter 20 min.',
    ],
  },
  {
    id: 'mega-66',
    name: 'Cake aux Olives',
    image: 'https://images.unsplash.com/photo-1587740896339-96a76170508d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 40,
    servings: 8,
    difficulty: 'Facile',
    category: 'Apéritif',
    ingredients: [
      { item: 'Farine', quantity: '200g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Huile', quantity: '100ml' },
      { item: 'Olives', quantity: '150g' },
      { item: 'Gruyère', quantity: '100g' },
    ],
    steps: [
      'Mélanger tous les ingrédients.',
      'Verser dans un moule.',
      'Cuire 40 min à 180°C.',
      'Servir tiède ou froid.',
    ],
  },
  {
    id: 'mega-67',
    name: 'Pizza Végétarienne',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 90,
    cookTime: 12,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pâte à pizza', quantity: '1' },
      { item: 'Sauce tomate', quantity: '200g' },
      { item: 'Mozzarella', quantity: '250g' },
      { item: 'Légumes variés', quantity: '400g' },
    ],
    steps: [
      'Étaler la pâte.',
      'Napper de sauce.',
      'Ajouter légumes et mozzarella.',
      'Cuire 12 min à 250°C.',
    ],
  },
  {
    id: 'mega-68',
    name: 'Nouilles Sautées',
    image: 'https://images.unsplash.com/photo-1718964313403-2db158f67844?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Nouilles chinoises', quantity: '400g' },
      { item: 'Légumes', quantity: '300g' },
      { item: 'Sauce soja', quantity: '4 c. à soupe' },
      { item: 'Huile de sésame', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Cuire les nouilles.',
      'Faire sauter les légumes.',
      'Ajouter nouilles et sauces.',
      'Servir chaud.',
    ],
  },
  {
    id: 'mega-69',
    name: 'Gratin de Légumes',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Courgettes', quantity: '3' },
      { item: 'Aubergines', quantity: '2' },
      { item: 'Tomates', quantity: '4' },
      { item: 'Béchamel', quantity: '500ml' },
      { item: 'Gruyère', quantity: '150g' },
    ],
    steps: [
      'Trancher tous les légumes.',
      'Disposer en couches.',
      'Napper de béchamel.',
      'Parsemer de gruyère.',
      'Gratiner 40 min.',
    ],
  },
  {
    id: 'mega-70',
    name: 'Boulettes de Viande',
    image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Viande',
    ingredients: [
      { item: 'Viande hachée', quantity: '500g' },
      { item: 'Œuf', quantity: '1' },
      { item: 'Chapelure', quantity: '50g' },
      { item: 'Herbes', quantity: '2 c. à soupe' },
      { item: 'Sauce tomate', quantity: '400g' },
    ],
    steps: [
      'Mélanger viande, œuf, chapelure et herbes.',
      'Former des boulettes.',
      'Les faire dorer.',
      'Mijoter dans la sauce tomate 20 min.',
    ],
  },
  {
    id: 'mega-71',
    name: 'Salade de Riz',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 6,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Riz', quantity: '300g' },
      { item: 'Thon', quantity: '200g' },
      { item: 'Tomates', quantity: '3' },
      { item: 'Maïs', quantity: '150g' },
      { item: 'Vinaigrette', quantity: '6 c. à soupe' },
    ],
    steps: [
      'Cuire le riz.',
      'Laisser refroidir.',
      'Ajouter tous les ingrédients.',
      'Assaisonner de vinaigrette.',
    ],
  },
  {
    id: 'mega-72',
    name: 'Omelette aux Champignons',
    image: 'https://images.unsplash.com/photo-1732969331543-80e52902e0a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: 'Facile',
    category: 'Œufs',
    ingredients: [
      { item: 'Œufs', quantity: '6' },
      { item: 'Champignons', quantity: '200g' },
      { item: 'Persil', quantity: '1 bouquet' },
      { item: 'Beurre', quantity: '20g' },
    ],
    steps: [
      'Faire revenir les champignons.',
      'Battre les œufs.',
      'Cuire l\'omelette.',
      'Garnir de champignons et plier.',
    ],
  },
  {
    id: 'mega-73',
    name: 'Soupe de Carottes',
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: 'Facile',
    category: 'Soupe',
    ingredients: [
      { item: 'Carottes', quantity: '1kg' },
      { item: 'Pomme de terre', quantity: '1' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Bouillon', quantity: '1.5L' },
      { item: 'Crème', quantity: '100ml' },
    ],
    steps: [
      'Éplucher et couper les légumes.',
      'Cuire dans le bouillon 25 min.',
      'Mixer finement.',
      'Ajouter la crème et servir.',
    ],
  },
  {
    id: 'mega-74',
    name: 'Tarte aux Champignons',
    image: 'https://images.unsplash.com/photo-1627308595232-d0cd54b31a4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pâte brisée', quantity: '1' },
      { item: 'Champignons', quantity: '500g' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Persil', quantity: '1 bouquet' },
    ],
    steps: [
      'Faire revenir les champignons.',
      'Mélanger crème et œufs.',
      'Disposer champignons sur la pâte.',
      'Verser l\'appareil.',
      'Cuire 35 min.',
    ],
  },
  {
    id: 'mega-75',
    name: 'Poulet Rôti Simple',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 60,
    servings: 4,
    difficulty: 'Facile',
    category: 'Volaille',
    ingredients: [
      { item: 'Poulet entier', quantity: '1.5kg' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Herbes', quantity: '2 c. à soupe' },
      { item: 'Citron', quantity: '1' },
    ],
    steps: [
      'Badigeonner le poulet de beurre.',
      'Farcir d\'herbes et citron.',
      'Rôtir 1h à 200°C.',
      'Arroser régulièrement.',
    ],
  },
  {
    id: 'mega-76',
    name: 'Endives au Jambon',
    image: 'https://images.unsplash.com/photo-1753289595628-e3732ce60039?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Endives', quantity: '8' },
      { item: 'Jambon', quantity: '8 tranches' },
      { item: 'Béchamel', quantity: '500ml' },
      { item: 'Gruyère', quantity: '100g' },
    ],
    steps: [
      'Cuire les endives.',
      'Les enrouler dans le jambon.',
      'Napper de béchamel.',
      'Parsemer de gruyère.',
      'Gratiner 25 min.',
    ],
  },
  {
    id: 'mega-77',
    name: 'Taboulé Oriental',
    image: 'https://images.unsplash.com/photo-1637806930600-37fa8892069d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 0,
    servings: 6,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Boulgour', quantity: '200g' },
      { item: 'Tomates', quantity: '4' },
      { item: 'Persil', quantity: '2 bottes' },
      { item: 'Menthe', quantity: '1 bouquet' },
      { item: 'Citron', quantity: '2' },
    ],
    steps: [
      'Faire gonfler le boulgour.',
      'Hacher persil et menthe.',
      'Concasser les tomates.',
      'Mélanger et assaisonner.',
    ],
  },
  {
    id: 'mega-78',
    name: 'Pâtes aux Fruits de Mer',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Poisson',
    ingredients: [
      { item: 'Spaghetti', quantity: '400g' },
      { item: 'Fruits de mer', quantity: '600g' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Vin blanc', quantity: '100ml' },
      { item: 'Persil', quantity: '1 bouquet' },
    ],
    steps: [
      'Cuire les pâtes.',
      'Faire revenir ail et fruits de mer.',
      'Déglacer au vin blanc.',
      'Mélanger avec les pâtes.',
      'Parsemer de persil.',
    ],
  },
  {
    id: 'mega-79',
    name: 'Gratin de Brocoli',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Brocoli', quantity: '800g' },
      { item: 'Béchamel', quantity: '400ml' },
      { item: 'Gruyère', quantity: '150g' },
    ],
    steps: [
      'Cuire le brocoli à la vapeur.',
      'Disposer dans un plat.',
      'Napper de béchamel.',
      'Parsemer de gruyère.',
      'Gratiner 25 min.',
    ],
  },
  {
    id: 'mega-80',
    name: 'Croque-Madame',
    image: 'https://images.unsplash.com/photo-1531664412848-9610afed156c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 12,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pain de mie', quantity: '8 tranches' },
      { item: 'Jambon', quantity: '4 tranches' },
      { item: 'Gruyère', quantity: '150g' },
      { item: 'Béchamel', quantity: '200ml' },
      { item: 'Œufs', quantity: '4' },
    ],
    steps: [
      'Préparer des croque-monsieur.',
      'Napper de béchamel.',
      'Gratiner.',
      'Ajouter un œuf au plat dessus.',
      'Servir immédiatement.',
    ],
  },
];
