// Collection massive de recettes supplémentaires
import type { Recipe } from '../components/RecipesScreen';

export const moreRecipes: Recipe[] = [
  // ===== CLASSIQUES FRANÇAIS AVANCÉS =====
  {
    id: 'extra-1',
    name: 'Ratatouille Niçoise',
    image: 'https://images.unsplash.com/photo-1707508466860-0dffe9e5e333?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyYXRhdG91aWxsZSUyMGZyZW5jaHxlbnwxfHx8fDE3NjI0MzAwMjB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 25,
    cookTime: 40,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Aubergines', quantity: '2' },
      { item: 'Courgettes', quantity: '3' },
      { item: 'Poivrons rouges', quantity: '2' },
      { item: 'Tomates', quantity: '6' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Ail', quantity: '4 gousses' },
      { item: 'Huile d\'olive', quantity: '100ml' },
      { item: 'Herbes de Provence', quantity: '2 c. à café' },
      { item: 'Thym frais', quantity: '2 branches' },
    ],
    steps: [
      'Couper tous les légumes en dés réguliers.',
      'Faire revenir les oignons et l\'ail dans l\'huile.',
      'Ajouter les aubergines, cuire 10 minutes.',
      'Incorporer courgettes et poivrons, cuire 10 minutes.',
      'Ajouter les tomates et les herbes.',
      'Mijoter à feu doux 30 minutes.',
      'Servir chaud ou tiède avec du basilic frais.',
    ],
  },
  {
    id: 'extra-2',
    name: 'Bœuf Bourguignon',
    image: 'https://images.unsplash.com/photo-1548869206-93b036288d7e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWVmJTIwYm91cmd1aWdub258ZW58MXx8fHwxNzYyNDIyNzY5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 180,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Français',
    ingredients: [
      { item: 'Bœuf à braiser', quantity: '1.5kg' },
      { item: 'Vin rouge', quantity: '750ml' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Carottes', quantity: '4' },
      { item: 'Oignons', quantity: '3' },
      { item: 'Champignons', quantity: '300g' },
      { item: 'Bouquet garni', quantity: '1' },
      { item: 'Farine', quantity: '3 c. à soupe' },
      { item: 'Beurre', quantity: '50g' },
    ],
    steps: [
      'Faire mariner le bœuf 24h dans le vin avec le bouquet garni.',
      'Égoutter et sécher la viande, la fariner.',
      'Faire revenir les lardons et réserver.',
      'Dorer la viande dans le beurre.',
      'Ajouter carottes et oignons, faire colorer.',
      'Mouiller avec le vin de marinade, ajouter le bouquet.',
      'Cuire au four à 160°C pendant 3h.',
      'Ajouter les champignons 30 min avant la fin.',
    ],
  },
  {
    id: 'extra-3',
    name: 'Tarte Tatin',
    image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YXJ0ZSUyMHRhdGlufGVufDF8fHx8MTc2MjQzMDAyMXww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 35,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Pommes', quantity: '8' },
      { item: 'Pâte feuilletée', quantity: '1' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Beurre', quantity: '80g' },
      { item: 'Cannelle', quantity: '1 c. à café' },
    ],
    steps: [
      'Faire un caramel avec le sucre dans une poêle.',
      'Ajouter le beurre et mélanger.',
      'Disposer les pommes coupées en quartiers.',
      'Cuire 15 min pour caraméliser les pommes.',
      'Couvrir avec la pâte feuilletée.',
      'Cuire au four à 200°C pendant 25 minutes.',
      'Démouler à l\'envers et servir tiède.',
    ],
  },
  {
    id: 'extra-4',
    name: 'Quiche Lorraine',
    image: 'https://images.unsplash.com/photo-1650844010413-3f24dc1c182b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxxdWljaGUlMjBsb3JyYWluZXxlbnwxfHx8fDE3NjI0MzAwMjF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pâte brisée', quantity: '1' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Lait', quantity: '100ml' },
      { item: 'Gruyère râpé', quantity: '100g' },
      { item: 'Muscade', quantity: '1 pincée' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Étaler la pâte dans un moule à tarte.',
      'Faire revenir les lardons sans matière grasse.',
      'Battre les œufs avec la crème et le lait.',
      'Ajouter le gruyère et la muscade.',
      'Disposer les lardons sur la pâte.',
      'Verser l\'appareil et cuire 35 minutes.',
    ],
  },
  {
    id: 'extra-5',
    name: 'Bouillabaisse Marseillaise',
    image: 'https://images.unsplash.com/photo-1621339881990-c94ba5cf98fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib3VpbGxhYmFpc3NlJTIwc291cHxlbnwxfHx8fDE3NjI0MzAwMjF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 40,
    cookTime: 45,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Français',
    ingredients: [
      { item: 'Poissons mélangés', quantity: '2kg' },
      { item: 'Tomates', quantity: '4' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Fenouil', quantity: '1 bulbe' },
      { item: 'Ail', quantity: '6 gousses' },
      { item: 'Safran', quantity: '1g' },
      { item: 'Huile d\'olive', quantity: '100ml' },
      { item: 'Vin blanc', quantity: '200ml' },
      { item: 'Bouquet garni', quantity: '1' },
    ],
    steps: [
      'Nettoyer et couper les poissons.',
      'Faire revenir oignons, fenouil et ail dans l\'huile.',
      'Ajouter les tomates concassées.',
      'Incorporer le vin blanc et le safran.',
      'Ajouter le bouquet garni et les poissons.',
      'Couvrir d\'eau, porter à ébullition.',
      'Cuire 20 minutes à feu vif.',
      'Servir avec de la rouille et des croûtons.',
    ],
  },
  {
    id: 'extra-6',
    name: 'Confit de Canard',
    image: 'https://images.unsplash.com/photo-1642231877874-ce3e205f39c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkdWNrJTIwY29uZml0fGVufDF8fHx8MTc2MjQzMDAyMnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 120,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Cuisses de canard', quantity: '4' },
      { item: 'Graisse de canard', quantity: '500g' },
      { item: 'Gros sel', quantity: '100g' },
      { item: 'Thym', quantity: '4 branches' },
      { item: 'Laurier', quantity: '2 feuilles' },
      { item: 'Ail', quantity: '4 gousses' },
      { item: 'Poivre', quantity: '1 c. à café' },
    ],
    steps: [
      'Frotter les cuisses avec le sel, thym et laurier.',
      'Laisser mariner 12h au frais.',
      'Rincer et sécher les cuisses.',
      'Les plonger dans la graisse fondue.',
      'Cuire au four à 150°C pendant 2h.',
      'Laisser refroidir dans la graisse.',
      'Au moment de servir, faire dorer à la poêle.',
    ],
  },
  {
    id: 'extra-7',
    name: 'Cassoulet',
    image: 'https://images.unsplash.com/photo-1612504258838-fbf14fe4437d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYXNzb3VsZXQlMjBiZWFuc3xlbnwxfHx8fDE3NjI0MzAwMjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 240,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Français',
    ingredients: [
      { item: 'Haricots blancs', quantity: '800g' },
      { item: 'Confit de canard', quantity: '4 cuisses' },
      { item: 'Saucisse de Toulouse', quantity: '400g' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Tomates', quantity: '400g' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Ail', quantity: '6 gousses' },
      { item: 'Bouquet garni', quantity: '1' },
    ],
    steps: [
      'Faire tremper les haricots 12h.',
      'Les cuire 1h avec le bouquet garni.',
      'Faire revenir oignons, ail et lardons.',
      'Ajouter les tomates et cuire 10 min.',
      'Dans une cocotte, alterner haricots et viandes.',
      'Mouiller avec le jus de cuisson des haricots.',
      'Cuire au four à 150°C pendant 3h.',
      'Briser la croûte 3 fois pendant la cuisson.',
    ],
  },
  {
    id: 'extra-8',
    name: 'Croque-Monsieur',
    image: 'https://images.unsplash.com/photo-1531664412848-9610afed156c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9xdWUlMjBtb25zaWV1cnxlbnwxfHx8fDE3NjI0MzAwMjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pain de mie', quantity: '8 tranches' },
      { item: 'Jambon blanc', quantity: '8 tranches' },
      { item: 'Gruyère râpé', quantity: '200g' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Farine', quantity: '30g' },
      { item: 'Lait', quantity: '300ml' },
      { item: 'Muscade', quantity: '1 pincée' },
    ],
    steps: [
      'Préparer une béchamel avec beurre, farine et lait.',
      'Assaisonner avec sel, poivre et muscade.',
      'Beurrer les tranches de pain.',
      'Garnir avec jambon et gruyère.',
      'Recouvrir d\'une tranche de pain.',
      'Napper de béchamel et de gruyère.',
      'Gratiner au four à 200°C pendant 10 minutes.',
    ],
  },
  {
    id: 'extra-9',
    name: 'Steak Tartare',
    image: 'https://images.unsplash.com/photo-1571513062809-2ac71eab2656?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGVhayUyMHRhcnRhcmV8ZW58MXx8fHwxNzYyNDMwMDI1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 0,
    servings: 2,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Bœuf haché', quantity: '400g' },
      { item: 'Jaunes d\'œufs', quantity: '2' },
      { item: 'Câpres', quantity: '2 c. à soupe' },
      { item: 'Cornichons', quantity: '4' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Moutarde', quantity: '1 c. à soupe' },
      { item: 'Sauce Worcestershire', quantity: '1 c. à café' },
      { item: 'Tabasco', quantity: 'Quelques gouttes' },
    ],
    steps: [
      'Hacher finement oignons, câpres et cornichons.',
      'Mélanger avec la viande.',
      'Incorporer moutarde, Worcestershire et Tabasco.',
      'Former 2 steaks.',
      'Faire un puits au centre.',
      'Y déposer un jaune d\'œuf.',
      'Servir immédiatement avec des frites.',
    ],
  },
  {
    id: 'extra-10',
    name: 'Pot-au-Feu',
    image: 'https://images.unsplash.com/photo-1754462529584-a36c94600a07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3QlMjBhdSUyMGZldXxlbnwxfHx8fDE3NjI0MzAwMjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 180,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Bœuf à bouillir', quantity: '1.5kg' },
      { item: 'Os à moelle', quantity: '4' },
      { item: 'Carottes', quantity: '8' },
      { item: 'Poireaux', quantity: '4' },
      { item: 'Navets', quantity: '4' },
      { item: 'Pommes de terre', quantity: '8' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Bouquet garni', quantity: '1' },
      { item: 'Clous de girofle', quantity: '3' },
    ],
    steps: [
      'Porter 3L d\'eau à ébullition.',
      'Plonger la viande et les os.',
      'Écumer régulièrement.',
      'Ajouter oignons piqués de clous de girofle.',
      'Incorporer le bouquet garni.',
      'Laisser mijoter 2h30.',
      'Ajouter les légumes 45 min avant la fin.',
      'Servir avec cornichons, moutarde et gros sel.',
    ],
  },
  {
    id: 'extra-11',
    name: 'Blanquette de Veau',
    image: 'https://images.unsplash.com/photo-1733700469173-15d46efc2c09?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibGFucXVldHRlJTIwdmVhbHxlbnwxfHx8fDE3NjI0MzAwMjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 25,
    cookTime: 120,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Veau à blanquette', quantity: '1.2kg' },
      { item: 'Carottes', quantity: '3' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Champignons', quantity: '300g' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Jaunes d\'œufs', quantity: '2' },
      { item: 'Citron', quantity: '1' },
      { item: 'Bouquet garni', quantity: '1' },
    ],
    steps: [
      'Faire blanchir le veau 5 minutes à l\'eau bouillante.',
      'Dans une cocotte, couvrir d\'eau froide.',
      'Ajouter carottes, oignons et bouquet garni.',
      'Cuire à feu doux pendant 1h30.',
      'Ajouter les champignons 20 min avant la fin.',
      'Mélanger jaunes d\'œufs et crème.',
      'Lier la sauce hors du feu.',
      'Ajouter le jus de citron et servir.',
    ],
  },
  {
    id: 'extra-12',
    name: 'Moules Marinières',
    image: 'https://images.unsplash.com/photo-1690521320157-0dc0d5f76269?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3VsZXMlMjBtYXJpbmllcmV8ZW58MXx8fHwxNzYyNDMwMDI1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Moules', quantity: '2kg' },
      { item: 'Vin blanc sec', quantity: '300ml' },
      { item: 'Échalotes', quantity: '4' },
      { item: 'Persil', quantity: '1 bouquet' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Poivre', quantity: '1 c. à café' },
    ],
    steps: [
      'Gratter et laver les moules.',
      'Émincer finement les échalotes et l\'ail.',
      'Faire suer dans le beurre.',
      'Ajouter le vin blanc et porter à ébullition.',
      'Incorporer les moules, couvrir.',
      'Cuire 8 minutes en remuant.',
      'Parsemer de persil ciselé et servir.',
    ],
  },
  {
    id: 'extra-13',
    name: 'Gratin Dauphinois',
    image: 'https://images.unsplash.com/photo-1684950888991-224571bf3910?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmF0aW4lMjBkYXVwaGlub2lzfGVufDF8fHx8MTc2MjQzMDAyNXww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pommes de terre', quantity: '1.5kg' },
      { item: 'Crème liquide', quantity: '400ml' },
      { item: 'Lait', quantity: '200ml' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Beurre', quantity: '30g' },
      { item: 'Muscade', quantity: '1 pincée' },
      { item: 'Sel et poivre', quantity: 'Au goût' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Éplucher et trancher finement les pommes de terre.',
      'Frotter le plat avec l\'ail et le beurrer.',
      'Disposer les pommes de terre en couches.',
      'Mélanger crème, lait, muscade, sel et poivre.',
      'Verser sur les pommes de terre.',
      'Cuire au four 1h jusqu\'à dorure.',
    ],
  },

  // ===== CUISINE ASIATIQUE =====
  {
    id: 'extra-14',
    name: 'Ramen Japonais',
    image: 'https://images.unsplash.com/photo-1625189657893-f8fd7b45a901?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyYW1lbiUyMGphcGFuZXNlfGVufDF8fHx8MTc2MjQzMDAyNXww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Nouilles ramen', quantity: '400g' },
      { item: 'Bouillon de poulet', quantity: '1.5L' },
      { item: 'Porc', quantity: '300g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Champignons shiitake', quantity: '8' },
      { item: 'Pousses de bambou', quantity: '100g' },
      { item: 'Sauce soja', quantity: '4 c. à soupe' },
      { item: 'Miso', quantity: '2 c. à soupe' },
      { item: 'Oignons verts', quantity: '3' },
    ],
    steps: [
      'Faire mariner le porc dans la sauce soja.',
      'Cuire les œufs mollets 6 minutes.',
      'Porter le bouillon à ébullition.',
      'Incorporer le miso.',
      'Cuire les nouilles selon le paquet.',
      'Griller le porc et le trancher.',
      'Assembler: nouilles, bouillon, porc, œufs et garnitures.',
    ],
  },
  {
    id: 'extra-15',
    name: 'Plateau de Sushis',
    image: 'https://images.unsplash.com/photo-1625937751876-4515cd8e78bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXNoaSUyMHBsYXR0ZXJ8ZW58MXx8fHwxNzYyMzkwMzM5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 60,
    cookTime: 20,
    servings: 4,
    difficulty: 'Difficile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Riz à sushi', quantity: '500g' },
      { item: 'Vinaigre de riz', quantity: '100ml' },
      { item: 'Saumon', quantity: '200g' },
      { item: 'Thon', quantity: '200g' },
      { item: 'Avocat', quantity: '2' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Algues nori', quantity: '10 feuilles' },
      { item: 'Wasabi', quantity: 'Au goût' },
      { item: 'Sauce soja', quantity: '100ml' },
    ],
    steps: [
      'Cuire le riz et l\'assaisonner au vinaigre.',
      'Laisser refroidir complètement.',
      'Découper le poisson en lamelles.',
      'Préparer les légumes en bâtonnets.',
      'Étaler le riz sur les feuilles de nori.',
      'Garnir et rouler les makis.',
      'Trancher en morceaux réguliers.',
      'Servir avec wasabi, gingembre et sauce soja.',
    ],
  },
  {
    id: 'extra-16',
    name: 'Pad Thaï',
    image: 'https://images.unsplash.com/photo-1718964313403-2db158f67844?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWQlMjB0aGFpJTIwbm9vZGxlc3xlbnwxfHx8fDE3NjI0MDIwMzZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Nouilles de riz', quantity: '400g' },
      { item: 'Crevettes', quantity: '300g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Tofu', quantity: '200g' },
      { item: 'Pousses de soja', quantity: '150g' },
      { item: 'Cacahuètes', quantity: '100g' },
      { item: 'Sauce de poisson', quantity: '3 c. à soupe' },
      { item: 'Sucre de palme', quantity: '2 c. à soupe' },
      { item: 'Citron vert', quantity: '2' },
    ],
    steps: [
      'Faire tremper les nouilles 30 minutes.',
      'Égoutter et réserver.',
      'Faire revenir les crevettes et le tofu.',
      'Pousser sur le côté, brouiller les œufs.',
      'Ajouter les nouilles et la sauce.',
      'Incorporer les pousses de soja.',
      'Servir avec cacahuètes et citron vert.',
    ],
  },
  {
    id: 'extra-17',
    name: 'Poulet au Beurre Indien',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXR0ZXIlMjBjaGlja2VufGVufDF8fHx8MTc2MjQzMDAyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 40,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Poulet', quantity: '800g' },
      { item: 'Yaourt nature', quantity: '200g' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Crème liquide', quantity: '200ml' },
      { item: 'Beurre', quantity: '80g' },
      { item: 'Garam masala', quantity: '2 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Ail', quantity: '4 gousses' },
      { item: 'Piment', quantity: '1' },
    ],
    steps: [
      'Faire mariner le poulet dans yaourt et épices 2h.',
      'Faire griller le poulet au four.',
      'Dans une poêle, faire fondre le beurre.',
      'Ajouter gingembre, ail et piment.',
      'Incorporer les tomates et mijoter 15 min.',
      'Ajouter le poulet et la crème.',
      'Laisser mijoter 20 minutes.',
      'Servir avec du riz basmati.',
    ],
  },

  // ===== CUISINE MÉDITERRANÉENNE =====
  {
    id: 'extra-18',
    name: 'Paella Valenciana',
    image: 'https://images.unsplash.com/photo-1602755088318-39b7a7e6482a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWVsbGElMjBzcGFuaXNofGVufDF8fHx8MTc2MjQzMDAyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 45,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Méditerranéen',
    ingredients: [
      { item: 'Riz bomba', quantity: '500g' },
      { item: 'Poulet', quantity: '500g' },
      { item: 'Crevettes', quantity: '400g' },
      { item: 'Moules', quantity: '500g' },
      { item: 'Tomates', quantity: '3' },
      { item: 'Poivrons', quantity: '2' },
      { item: 'Petits pois', quantity: '200g' },
      { item: 'Safran', quantity: '1g' },
      { item: 'Bouillon de poulet', quantity: '1.5L' },
    ],
    steps: [
      'Faire revenir le poulet dans l\'huile.',
      'Ajouter les poivrons et tomates.',
      'Incorporer le riz et le safran.',
      'Verser le bouillon chaud.',
      'Ne pas remuer pendant la cuisson.',
      'Ajouter fruits de mer 10 min avant la fin.',
      'Laisser reposer 5 min avant de servir.',
    ],
  },
  {
    id: 'extra-19',
    name: 'Tacos Mexicains',
    image: 'https://images.unsplash.com/photo-1546853846-53490ede35b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YWNvcyUyMG1leGljYW58ZW58MXx8fHwxNzYyNDE5NDk3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 25,
    cookTime: 20,
    servings: 6,
    difficulty: 'Facile',
    category: 'Mexicain',
    ingredients: [
      { item: 'Tortillas', quantity: '12' },
      { item: 'Viande hachée', quantity: '600g' },
      { item: 'Haricots rouges', quantity: '400g' },
      { item: 'Tomates', quantity: '3' },
      { item: 'Avocat', quantity: '2' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Coriandre', quantity: '1 bouquet' },
      { item: 'Épices mexicaines', quantity: '2 c. à soupe' },
      { item: 'Crème fraîche', quantity: '150ml' },
    ],
    steps: [
      'Faire revenir la viande avec les épices.',
      'Chauffer les haricots.',
      'Concasser les tomates.',
      'Préparer le guacamole avec les avocats.',
      'Chauffer les tortillas.',
      'Garnir avec viande, haricots et condiments.',
      'Servir avec citron vert et piment.',
    ],
  },

  // ===== PLATS VÉGÉTARIENS =====
  {
    id: 'extra-20',
    name: 'Buddha Bowl Complet',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 30,
    servings: 4,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Quinoa', quantity: '300g' },
      { item: 'Pois chiches', quantity: '400g' },
      { item: 'Patates douces', quantity: '2' },
      { item: 'Avocat', quantity: '2' },
      { item: 'Chou kale', quantity: '200g' },
      { item: 'Graines de courge', quantity: '50g' },
      { item: 'Tahini', quantity: '4 c. à soupe' },
      { item: 'Citron', quantity: '2' },
    ],
    steps: [
      'Cuire le quinoa selon les instructions.',
      'Rôtir les patates douces au four 25 min.',
      'Griller les pois chiches aux épices.',
      'Masser le kale avec huile d\'olive.',
      'Préparer la sauce tahini-citron.',
      'Assembler dans un bol tous les ingrédients.',
      'Parsemer de graines et arroser de sauce.',
    ],
  },
  {
    id: 'extra-21',
    name: 'Lasagnes aux Légumes',
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 45,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pâtes à lasagne', quantity: '16 feuilles' },
      { item: 'Aubergines', quantity: '2' },
      { item: 'Courgettes', quantity: '3' },
      { item: 'Épinards', quantity: '400g' },
      { item: 'Ricotta', quantity: '500g' },
      { item: 'Mozzarella', quantity: '300g' },
      { item: 'Sauce tomate', quantity: '800g' },
      { item: 'Parmesan', quantity: '100g' },
    ],
    steps: [
      'Trancher et griller aubergines et courgettes.',
      'Faire revenir les épinards.',
      'Mélanger ricotta, épinards et assaisonnements.',
      'Dans un plat, alterner: sauce, pâtes, légumes, ricotta.',
      'Répéter 4 fois.',
      'Terminer par mozzarella et parmesan.',
      'Cuire au four à 180°C pendant 45 minutes.',
    ],
  },
  {
    id: 'extra-22',
    name: 'Curry de Légumes',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pois chiches', quantity: '400g' },
      { item: 'Patates douces', quantity: '2' },
      { item: 'Épinards', quantity: '200g' },
      { item: 'Lait de coco', quantity: '400ml' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Curry en poudre', quantity: '3 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Ail', quantity: '3 gousses' },
    ],
    steps: [
      'Couper les patates douces en dés.',
      'Faire revenir ail et gingembre.',
      'Ajouter le curry et faire torréfier.',
      'Incorporer les patates douces.',
      'Ajouter pois chiches et tomates.',
      'Verser le lait de coco.',
      'Mijoter 25 min, ajouter les épinards.',
      'Servir avec du riz basmati.',
    ],
  },

  // ===== DESSERTS =====
  {
    id: 'extra-23',
    name: 'Tarte au Citron Meringuée',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 35,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte sablée', quantity: '1' },
      { item: 'Citrons', quantity: '5' },
      { item: 'Œufs', quantity: '6' },
      { item: 'Sucre', quantity: '250g' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Maïzena', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Cuire la pâte à blanc 15 minutes.',
      'Préparer la crème au citron: jus, zestes, œufs, sucre.',
      'Cuire au bain-marie en remuant.',
      'Incorporer le beurre hors du feu.',
      'Verser dans le fond de tarte.',
      'Monter les blancs en neige avec le sucre.',
      'Dresser la meringue sur la crème.',
      'Dorer au four 10 minutes à 180°C.',
    ],
  },
  {
    id: 'extra-24',
    name: 'Mousse au Chocolat',
    image: 'https://images.unsplash.com/photo-1541599468348-e96984315921?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 5,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Chocolat noir', quantity: '200g' },
      { item: 'Œufs', quantity: '6' },
      { item: 'Sucre', quantity: '50g' },
      { item: 'Sel', quantity: '1 pincée' },
    ],
    steps: [
      'Faire fondre le chocolat au bain-marie.',
      'Séparer les blancs des jaunes.',
      'Incorporer les jaunes au chocolat fondu.',
      'Monter les blancs en neige ferme avec le sel.',
      'Ajouter le sucre progressivement.',
      'Incorporer délicatement au chocolat.',
      'Répartir dans des verrines.',
      'Réfrigérer au moins 3 heures.',
    ],
  },
  {
    id: 'extra-25',
    name: 'Crème Brûlée',
    image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Crème liquide', quantity: '500ml' },
      { item: 'Jaunes d\'œufs', quantity: '6' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Gousse de vanille', quantity: '1' },
      { item: 'Cassonade', quantity: '6 c. à soupe' },
    ],
    steps: [
      'Faire infuser la vanille dans la crème chaude.',
      'Blanchir les jaunes avec le sucre.',
      'Incorporer la crème tiède.',
      'Verser dans des ramequins.',
      'Cuire au bain-marie au four 35 min à 150°C.',
      'Laisser refroidir puis réfrigérer 4h.',
      'Saupoudrer de cassonade.',
      'Caraméliser au chalumeau.',
    ],
  },
  {
    id: 'extra-26',
    name: 'Profiteroles',
    image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 45,
    cookTime: 30,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Eau', quantity: '250ml' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Farine', quantity: '150g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Glace vanille', quantity: '500ml' },
      { item: 'Chocolat noir', quantity: '200g' },
      { item: 'Crème liquide', quantity: '100ml' },
    ],
    steps: [
      'Préparer la pâte à choux: eau, beurre, farine.',
      'Incorporer les œufs un par un.',
      'Former des petits choux sur la plaque.',
      'Cuire 25 min à 180°C.',
      'Laisser refroidir complètement.',
      'Garnir de glace vanille.',
      'Préparer la sauce chocolat.',
      'Servir avec la sauce chaude.',
    ],
  },
  {
    id: 'extra-27',
    name: 'Fondant au Chocolat',
    image: 'https://images.unsplash.com/photo-1606312619070-d48b4f50a8e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 12,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Chocolat noir', quantity: '200g' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Farine', quantity: '50g' },
    ],
    steps: [
      'Préchauffer le four à 200°C.',
      'Faire fondre chocolat et beurre.',
      'Fouetter œufs et sucre.',
      'Incorporer le chocolat fondu.',
      'Ajouter la farine tamisée.',
      'Beurrer et fariner les moules.',
      'Verser la pâte et cuire 12 minutes.',
      'Démouler tiède et servir immédiatement.',
    ],
  },

  // ===== BRUNCH & PETIT-DÉJEUNER =====
  {
    id: 'extra-28',
    name: 'Pancakes Américains',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Brunch',
    ingredients: [
      { item: 'Farine', quantity: '250g' },
      { item: 'Lait', quantity: '300ml' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Sucre', quantity: '2 c. à soupe' },
      { item: 'Levure chimique', quantity: '1 sachet' },
      { item: 'Beurre fondu', quantity: '50g' },
      { item: 'Sirop d\'érable', quantity: 'Pour servir' },
    ],
    steps: [
      'Mélanger farine, sucre et levure.',
      'Battre œufs et lait.',
      'Incorporer au mélange sec.',
      'Ajouter le beurre fondu.',
      'Laisser reposer 10 minutes.',
      'Cuire dans une poêle chaude.',
      'Servir avec sirop d\'érable et fruits.',
    ],
  },
  {
    id: 'extra-29',
    name: 'Œufs Bénédicte',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c582?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Brunch',
    ingredients: [
      { item: 'Muffins anglais', quantity: '4' },
      { item: 'Œufs', quantity: '8' },
      { item: 'Jambon', quantity: '8 tranches' },
      { item: 'Jaunes d\'œufs', quantity: '3' },
      { item: 'Beurre clarifié', quantity: '150g' },
      { item: 'Citron', quantity: '1' },
      { item: 'Ciboulette', quantity: '1 bouquet' },
    ],
    steps: [
      'Préparer la sauce hollandaise au bain-marie.',
      'Pocher les œufs dans de l\'eau vinaigrée.',
      'Toaster les muffins.',
      'Faire griller le jambon.',
      'Assembler: muffin, jambon, œuf poché.',
      'Napper de sauce hollandaise.',
      'Parsemer de ciboulette.',
    ],
  },
  {
    id: 'extra-30',
    name: 'Granola Maison',
    image: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 30,
    servings: 10,
    difficulty: 'Facile',
    category: 'Brunch',
    ingredients: [
      { item: 'Flocons d\'avoine', quantity: '400g' },
      { item: 'Miel', quantity: '100ml' },
      { item: 'Huile de coco', quantity: '50ml' },
      { item: 'Amandes', quantity: '100g' },
      { item: 'Noix de cajou', quantity: '100g' },
      { item: 'Graines de courge', quantity: '50g' },
      { item: 'Cranberries', quantity: '100g' },
      { item: 'Cannelle', quantity: '1 c. à café' },
    ],
    steps: [
      'Préchauffer le four à 160°C.',
      'Mélanger flocons, fruits secs et graines.',
      'Faire chauffer miel et huile de coco.',
      'Verser sur le mélange sec.',
      'Ajouter la cannelle.',
      'Étaler sur une plaque.',
      'Cuire 30 min en remuant toutes les 10 min.',
      'Ajouter les cranberries après cuisson.',
    ],
  },

  // ===== PIZZAS =====
  {
    id: 'extra-31',
    name: 'Pizza Margherita',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 90,
    cookTime: 12,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Farine', quantity: '500g' },
      { item: 'Eau tiède', quantity: '300ml' },
      { item: 'Levure boulangère', quantity: '7g' },
      { item: 'Sauce tomate', quantity: '300g' },
      { item: 'Mozzarella', quantity: '400g' },
      { item: 'Basilic frais', quantity: '1 bouquet' },
      { item: 'Huile d\'olive', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Préparer la pâte: farine, eau, levure, sel.',
      'Pétrir 10 minutes.',
      'Laisser lever 1h à température ambiante.',
      'Étaler la pâte finement.',
      'Étaler la sauce tomate.',
      'Ajouter la mozzarella en morceaux.',
      'Cuire au four très chaud (250°C) 12 minutes.',
      'Parsemer de basilic frais.',
    ],
  },
  {
    id: 'extra-32',
    name: 'Pizza Quatre Fromages',
    image: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 90,
    cookTime: 12,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pâte à pizza', quantity: '1' },
      { item: 'Mozzarella', quantity: '150g' },
      { item: 'Gorgonzola', quantity: '100g' },
      { item: 'Parmesan', quantity: '50g' },
      { item: 'Emmental', quantity: '100g' },
      { item: 'Crème fraîche', quantity: '100ml' },
      { item: 'Origan', quantity: '1 c. à café' },
    ],
    steps: [
      'Étaler la pâte à pizza.',
      'Badigeonner de crème fraîche.',
      'Répartir les 4 fromages.',
      'Saupoudrer d\'origan.',
      'Cuire au four à 250°C pendant 12 minutes.',
      'Servir immédiatement.',
    ],
  },

  // ===== SALADES =====
  {
    id: 'extra-33',
    name: 'Salade César',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Laitue romaine', quantity: '2' },
      { item: 'Poulet', quantity: '300g' },
      { item: 'Parmesan', quantity: '100g' },
      { item: 'Croûtons', quantity: '100g' },
      { item: 'Anchois', quantity: '6 filets' },
      { item: 'Jaune d\'œuf', quantity: '1' },
      { item: 'Moutarde', quantity: '1 c. à café' },
      { item: 'Huile d\'olive', quantity: '100ml' },
    ],
    steps: [
      'Griller le poulet et le trancher.',
      'Préparer la sauce: jaune, anchois, moutarde, huile.',
      'Laver et essorer la laitue.',
      'Mélanger avec la sauce.',
      'Ajouter poulet, croûtons et parmesan.',
      'Servir immédiatement.',
    ],
  },
  {
    id: 'extra-34',
    name: 'Salade Niçoise',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Thon en conserve', quantity: '300g' },
      { item: 'Tomates', quantity: '4' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Haricots verts', quantity: '200g' },
      { item: 'Pommes de terre', quantity: '4' },
      { item: 'Olives noires', quantity: '100g' },
      { item: 'Anchois', quantity: '8 filets' },
      { item: 'Huile d\'olive', quantity: '6 c. à soupe' },
    ],
    steps: [
      'Cuire les œufs durs 10 minutes.',
      'Cuire haricots verts et pommes de terre.',
      'Couper les tomates en quartiers.',
      'Émietter le thon.',
      'Disposer tous les ingrédients dans un plat.',
      'Assaisonner d\'huile d\'olive et vinaigre.',
      'Servir frais.',
    ],
  },

  // ===== SOUPES =====
  {
    id: 'extra-35',
    name: 'Soupe Minestrone',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Soupe',
    ingredients: [
      { item: 'Haricots blancs', quantity: '200g' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Courgettes', quantity: '2' },
      { item: 'Tomates', quantity: '400g' },
      { item: 'Pâtes courtes', quantity: '100g' },
      { item: 'Basilic', quantity: '1 bouquet' },
      { item: 'Parmesan', quantity: '50g' },
      { item: 'Bouillon de légumes', quantity: '1.5L' },
    ],
    steps: [
      'Faire revenir oignons et ail.',
      'Ajouter carottes et courgettes en dés.',
      'Incorporer les tomates et le bouillon.',
      'Ajouter les haricots.',
      'Mijoter 30 minutes.',
      'Ajouter les pâtes 10 min avant la fin.',
      'Servir avec basilic et parmesan.',
    ],
  },
  {
    id: 'extra-36',
    name: 'Velouté de Butternut',
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Soupe',
    ingredients: [
      { item: 'Courge butternut', quantity: '1kg' },
      { item: 'Pommes de terre', quantity: '2' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Bouillon de légumes', quantity: '1L' },
      { item: 'Crème liquide', quantity: '100ml' },
      { item: 'Muscade', quantity: '1 pincée' },
      { item: 'Graines de courge', quantity: '50g' },
    ],
    steps: [
      'Éplucher et couper la courge en dés.',
      'Faire revenir l\'oignon émincé.',
      'Ajouter courge et pommes de terre.',
      'Mouiller avec le bouillon.',
      'Cuire 30 minutes.',
      'Mixer finement.',
      'Incorporer la crème et la muscade.',
      'Servir avec des graines torréfiées.',
    ],
  },

  // ===== PLATS RAPIDES =====
  {
    id: 'extra-37',
    name: 'Wok de Légumes',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Brocoli', quantity: '300g' },
      { item: 'Poivrons', quantity: '2' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Pousses de soja', quantity: '150g' },
      { item: 'Sauce soja', quantity: '4 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Huile de sésame', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Couper tous les légumes en julienne.',
      'Chauffer le wok très chaud.',
      'Faire sauter ail et gingembre.',
      'Ajouter les légumes par ordre de fermeté.',
      'Cuire à feu vif en remuant.',
      'Ajouter sauce soja et huile de sésame.',
      'Servir immédiatement avec du riz.',
    ],
  },
  {
    id: 'extra-38',
    name: 'Risotto aux Champignons',
    image: 'https://images.unsplash.com/photo-1476124369491-f117991cdc65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Riz arborio', quantity: '320g' },
      { item: 'Champignons', quantity: '400g' },
      { item: 'Bouillon de volaille', quantity: '1.5L' },
      { item: 'Vin blanc', quantity: '100ml' },
      { item: 'Parmesan', quantity: '80g' },
      { item: 'Beurre', quantity: '60g' },
      { item: 'Échalotes', quantity: '2' },
    ],
    steps: [
      'Faire chauffer le bouillon.',
      'Faire revenir les échalotes.',
      'Ajouter le riz et nacrer.',
      'Déglacer au vin blanc.',
      'Ajouter le bouillon louche par louche.',
      'Incorporer les champignons poêlés.',
      'Terminer avec beurre et parmesan.',
    ],
  },

  // ===== PLATS D'HIVER =====
  {
    id: 'extra-39',
    name: 'Tartiflette Savoyarde',
    image: 'https://images.unsplash.com/photo-1599474924187-334a4ae5bd3c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pommes de terre', quantity: '1.5kg' },
      { item: 'Reblochon', quantity: '1' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Vin blanc', quantity: '150ml' },
      { item: 'Crème fraîche', quantity: '200ml' },
    ],
    steps: [
      'Cuire les pommes de terre avec la peau.',
      'Les trancher en rondelles.',
      'Faire revenir oignons et lardons.',
      'Dans un plat, alterner pommes de terre et lardons.',
      'Arroser de vin blanc et crème.',
      'Couper le reblochon en deux et disposer sur le dessus.',
      'Cuire au four à 200°C pendant 30 minutes.',
    ],
  },
  {
    id: 'extra-40',
    name: 'Raclette',
    image: 'https://images.unsplash.com/photo-1612392062798-2dd90f5e4b22?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 60,
    servings: 8,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Fromage à raclette', quantity: '1.5kg' },
      { item: 'Pommes de terre', quantity: '2kg' },
      { item: 'Charcuterie', quantity: '500g' },
      { item: 'Cornichons', quantity: '200g' },
      { item: 'Oignons au vinaigre', quantity: '150g' },
    ],
    steps: [
      'Cuire les pommes de terre en robe des champs.',
      'Trancher le fromage.',
      'Disposer la charcuterie sur un plateau.',
      'Préparer cornichons et oignons.',
      'Faire fondre le fromage dans les poêlons.',
      'Racler sur les pommes de terre.',
      'Déguster avec la charcuterie et accompagnements.',
    ],
  },
];
