// Base de données complète de recettes en français
import type { Recipe } from '../components/RecipesScreen';

export const frenchRecipes: Recipe[] = [
  // ===== RECETTES FRANÇAISES =====
  {
    id: 'fr-1',
    name: 'Pâtes Carbonara',
    image: 'https://images.unsplash.com/photo-1588013273468-315fd88ea34c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXN0YSUyMGNhcmJvbmFyYXxlbnwxfHx8fDE3NjA4OTc2NDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes', quantity: '400g' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Parmesan', quantity: '100g' },
      { item: 'Poivre', quantity: 'Au goût' },
    ],
    steps: [
      'Faire cuire les pâtes dans de l\'eau salée bouillante selon les instructions du paquet.',
      'Pendant ce temps, faire revenir les lardons dans une poêle sans matière grasse.',
      'Battre les œufs avec le parmesan râpé dans un bol.',
      'Égoutter les pâtes et les remettre dans la casserole hors du feu.',
      'Ajouter les lardons et le mélange œufs-parmesan, mélanger rapidement.',
      'Servir immédiatement avec du poivre fraîchement moulu.',
    ],
  },
  {
    id: 'fr-2',
    name: 'Poulet Rôti aux Légumes',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyb2FzdCUyMGNoaWNrZW58ZW58MXx8fHwxNzYwOTI1NTMyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Poulet entier', quantity: '1.5kg' },
      { item: 'Carottes', quantity: '4' },
      { item: 'Pommes de terre', quantity: '6' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Huile d\'olive', quantity: '3 c. à soupe' },
      { item: 'Herbes de Provence', quantity: '2 c. à café' },
      { item: 'Sel et poivre', quantity: 'Au goût' },
    ],
    steps: [
      'Préchauffer le four à 200°C.',
      'Laver et couper les légumes en gros morceaux.',
      'Placer le poulet dans un plat à four et l\'entourer de légumes.',
      'Arroser d\'huile d\'olive, saler, poivrer et saupoudrer d\'herbes.',
      'Enfourner pour 60 minutes en arrosant régulièrement.',
      'Vérifier la cuisson : le jus doit être clair.',
      'Laisser reposer 10 minutes avant de découper.',
    ],
  },
  {
    id: 'fr-3',
    name: 'Quiche Lorraine',
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxxdWljaGV8ZW58MXx8fHwxNzYwOTI1NTMyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pâte brisée', quantity: '1' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Lait', quantity: '100ml' },
      { item: 'Fromage râpé', quantity: '100g' },
      { item: 'Sel et poivre', quantity: 'Au goût' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Étaler la pâte dans un moule à tarte et piquer le fond.',
      'Faire revenir les lardons dans une poêle.',
      'Battre les œufs avec la crème et le lait, saler et poivrer.',
      'Répartir les lardons sur la pâte.',
      'Verser le mélange œufs-crème et parsemer de fromage.',
      'Enfourner 35 minutes jusqu\'à ce que la quiche soit dorée.',
    ],
  },
  {
    id: 'fr-4',
    name: 'Ratatouille Provençale',
    image: 'https://images.unsplash.com/photo-1572441713132-c542fc4fe282?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyYXRhdG91aWxsZXxlbnwxfHx8fDE3NjA5MjU1MzJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Aubergines', quantity: '2' },
      { item: 'Courgettes', quantity: '2' },
      { item: 'Poivrons', quantity: '2' },
      { item: 'Tomates', quantity: '4' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
      { item: 'Herbes de Provence', quantity: '1 c. à café' },
    ],
    steps: [
      'Laver et couper tous les légumes en dés.',
      'Faire revenir l\'oignon et l\'ail dans l\'huile d\'olive.',
      'Ajouter les aubergines et faire cuire 5 minutes.',
      'Ajouter les courgettes et les poivrons, cuire 5 minutes.',
      'Incorporer les tomates et les herbes.',
      'Couvrir et laisser mijoter 30 minutes à feu doux.',
      'Ajuster l\'assaisonnement et servir chaud ou froid.',
    ],
  },
  {
    id: 'fr-5',
    name: 'Blanquette de Veau',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGV3fGVufDF8fHx8MTc2MDkyNTUzMnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Français',
    ingredients: [
      { item: 'Veau', quantity: '1kg' },
      { item: 'Carottes', quantity: '3' },
      { item: 'Champignons', quantity: '250g' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Bouillon de volaille', quantity: '1L' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Citron', quantity: '1' },
    ],
    steps: [
      'Couper le veau en morceaux et blanchir 5 minutes.',
      'Dans une cocotte, mettre le veau, les carottes et l\'oignon.',
      'Couvrir de bouillon et cuire 1h30 à feu doux.',
      'Ajouter les champignons 15 minutes avant la fin.',
      'Mélanger les jaunes d\'œufs avec la crème et le jus de citron.',
      'Retirer la viande et les légumes, filtrer le bouillon.',
      'Incorporer le mélange œufs-crème hors du feu.',
      'Remettre viande et légumes, réchauffer sans bouillir.',
    ],
  },
  {
    id: 'fr-6',
    name: 'Gratin Dauphinois',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c647?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3RhdG8lMjBncmF0aW58ZW58MXx8fHwxNzYwOTI1NTMyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pommes de terre', quantity: '1kg' },
      { item: 'Lait', quantity: '500ml' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Beurre', quantity: '30g' },
      { item: 'Sel et poivre', quantity: 'Au goût' },
      { item: 'Noix de muscade', quantity: '1 pincée' },
    ],
    steps: [
      'Préchauffer le four à 160°C.',
      'Éplucher et couper les pommes de terre en fines rondelles.',
      'Frotter un plat à gratin avec l\'ail et le beurrer.',
      'Disposer les pommes de terre en couches.',
      'Mélanger le lait et la crème, saler, poivrer, ajouter la muscade.',
      'Verser sur les pommes de terre.',
      'Enfourner 60 minutes jusqu\'à obtenir une belle croûte dorée.',
    ],
  },
  {
    id: 'fr-7',
    name: 'Bœuf Bourguignon',
    image: 'https://images.unsplash.com/photo-1600659811958-1cb6f598b6f5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWVmJTIwc3Rld3xlbnwxfHx8fDE3NjA5MjU1MzJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 180,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Français',
    ingredients: [
      { item: 'Bœuf à braiser', quantity: '1.2kg' },
      { item: 'Vin rouge', quantity: '750ml' },
      { item: 'Lardons', quantity: '150g' },
      { item: 'Carottes', quantity: '4' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Champignons', quantity: '250g' },
      { item: 'Bouquet garni', quantity: '1' },
      { item: 'Farine', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Couper le bœuf en cubes et le faire mariner dans le vin rouge 2h.',
      'Faire revenir les lardons puis réserver.',
      'Faire dorer les morceaux de bœuf égouttés et farinés.',
      'Ajouter les carottes et oignons coupés.',
      'Verser la marinade et ajouter le bouquet garni.',
      'Couvrir et laisser mijoter 3h à feu très doux.',
      'Ajouter les champignons 30 minutes avant la fin.',
      'Servir avec des pommes de terre ou des pâtes fraîches.',
    ],
  },
  {
    id: 'fr-8',
    name: 'Soupe à l\'Oignon Gratinée',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvbmlvbiUyMHNvdXB8ZW58MXx8fHwxNzYwOTI1NTMyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Oignon', quantity: '6' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Bouillon de bœuf', quantity: '1.5L' },
      { item: 'Vin blanc', quantity: '100ml' },
      { item: 'Pain', quantity: '8 tranches' },
      { item: 'Fromage râpé', quantity: '200g' },
      { item: 'Sel et poivre', quantity: 'Au goût' },
    ],
    steps: [
      'Émincer finement les oignons.',
      'Faire fondre le beurre et y faire caraméliser les oignons 30 min.',
      'Ajouter le vin blanc et laisser réduire.',
      'Verser le bouillon, saler, poivrer et cuire 15 minutes.',
      'Préchauffer le grill du four.',
      'Répartir la soupe dans des bols allant au four.',
      'Déposer une tranche de pain et couvrir de fromage.',
      'Gratiner au four 5 minutes jusqu\'à ce que le fromage soit doré.',
    ],
  },
  {
    id: 'fr-9',
    name: 'Tartiflette',
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YXJ0aWZsZXR0ZXxlbnwxfHx8fDE3NjA5MjU1MzJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pommes de terre', quantity: '1kg' },
      { item: 'Reblochon', quantity: '1' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Vin blanc', quantity: '10cl' },
      { item: 'Crème fraîche', quantity: '100ml' },
      { item: 'Sel et poivre', quantity: 'Au goût' },
    ],
    steps: [
      'Faire cuire les pommes de terre à l\'eau avec leur peau.',
      'Pendant ce temps, faire revenir les lardons et les oignons.',
      'Éplucher et couper les pommes de terre en rondelles.',
      'Dans un plat à gratin, alterner pommes de terre et lardons-oignons.',
      'Arroser de vin blanc et de crème.',
      'Couper le reblochon en deux et le poser sur le dessus.',
      'Enfourner à 200°C pendant 30 minutes.',
    ],
  },
  {
    id: 'fr-10',
    name: 'Coq au Vin',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyfHxjaGlja2VuJTIwd2luZXxlbnwxfHx8fDE3NjA5MjU1MzJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 120,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Français',
    ingredients: [
      { item: 'Poulet', quantity: '1.5kg' },
      { item: 'Vin rouge', quantity: '750ml' },
      { item: 'Lardons', quantity: '150g' },
      { item: 'Champignons', quantity: '250g' },
      { item: 'Oignon', quantity: '12 petits' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Bouquet garni', quantity: '1' },
      { item: 'Farine', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Découper le poulet en morceaux.',
      'Faire revenir les lardons puis réserver.',
      'Faire dorer les morceaux de poulet et réserver.',
      'Faire revenir les oignons et l\'ail.',
      'Saupoudrer de farine et mélanger.',
      'Remettre le poulet, ajouter le vin et le bouquet garni.',
      'Couvrir et laisser mijoter 2h à feu doux.',
      'Ajouter les champignons 30 minutes avant la fin.',
    ],
  },
  
  // ===== RECETTES ITALIENNES =====
  {
    id: 'it-1',
    name: 'Pizza Margherita',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaXp6YSUyMG1hcmdoZXJpdGF8ZW58MXx8fHwxNzYyMzcyNDU4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Farine', quantity: '500g' },
      { item: 'Levure', quantity: '1 sachet' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Mozzarella', quantity: '250g' },
      { item: 'Basilic frais', quantity: '1 bouquet' },
      { item: 'Huile d\'olive', quantity: '3 c. à soupe' },
      { item: 'Sel', quantity: 'Au goût' },
    ],
    steps: [
      'Préparer la pâte : mélanger farine, levure, eau tiède et sel.',
      'Pétrir 10 minutes et laisser lever 1h.',
      'Étaler la pâte sur une plaque huilée.',
      'Étaler les tomates concassées sur la pâte.',
      'Ajouter la mozzarella coupée en morceaux.',
      'Enfourner à 240°C pendant 12-15 minutes.',
      'Ajouter le basilic frais et un filet d\'huile d\'olive avant de servir.',
    ],
  },
  {
    id: 'it-2',
    name: 'Lasagnes Bolognaise',
    image: 'https://images.unsplash.com/photo-1709429790175-b02bb1b19207?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXNhZ25hfGVufDF8fHx8MTc2MjQyNTQxNnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 45,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes à lasagnes', quantity: '12 feuilles' },
      { item: 'Viande hachée', quantity: '500g' },
      { item: 'Tomates concassées', quantity: '800g' },
      { item: 'Béchamel', quantity: '500ml' },
      { item: 'Parmesan', quantity: '100g' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Huile d\'olive', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Faire revenir l\'oignon et l\'ail dans l\'huile d\'olive.',
      'Ajouter la viande hachée et faire cuire.',
      'Incorporer les tomates concassées et laisser mijoter 20 min.',
      'Dans un plat, alterner couches de pâtes, sauce bolognaise et béchamel.',
      'Terminer par une couche de béchamel et saupoudrer de parmesan.',
      'Enfourner à 180°C pendant 45 minutes.',
      'Laisser reposer 10 minutes avant de servir.',
    ],
  },
  {
    id: 'it-3',
    name: 'Risotto aux Champignons',
    image: 'https://images.unsplash.com/photo-1637361874063-e5e415d7bcf7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyaXNvdHRvfGVufDF8fHx8MTc2MjQyNTQxNnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Riz arborio', quantity: '300g' },
      { item: 'Champignons', quantity: '300g' },
      { item: 'Bouillon de légumes', quantity: '1L' },
      { item: 'Vin blanc', quantity: '150ml' },
      { item: 'Parmesan', quantity: '80g' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Huile d\'olive', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Faire revenir l\'oignon émincé dans l\'huile et le beurre.',
      'Ajouter les champignons et faire cuire 5 minutes.',
      'Incorporer le riz et nacrer 2 minutes.',
      'Verser le vin blanc et laisser évaporer.',
      'Ajouter le bouillon louche par louche en remuant constamment.',
      'Cuire environ 18 minutes jusqu\'à ce que le riz soit crémeux.',
      'Incorporer le parmesan et le reste du beurre hors du feu.',
      'Servir immédiatement.',
    ],
  },
  {
    id: 'it-4',
    name: 'Tiramisu',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aXJhbWlzdXxlbnwxfHx8fDE3NjI0MjU0MjJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Mascarpone', quantity: '500g' },
      { item: 'Œufs', quantity: '6' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Biscuits à la cuillère', quantity: '30' },
      { item: 'Café fort', quantity: '300ml' },
      { item: 'Cacao en poudre', quantity: '2 c. à soupe' },
      { item: 'Amaretto', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Séparer les blancs des jaunes d\'œufs.',
      'Fouetter les jaunes avec le sucre jusqu\'à blanchiment.',
      'Incorporer le mascarpone au mélange.',
      'Monter les blancs en neige et les incorporer délicatement.',
      'Préparer le café et y ajouter l\'amaretto.',
      'Tremper rapidement les biscuits dans le café.',
      'Alterner couches de biscuits et crème au mascarpone.',
      'Réfrigérer 4h minimum et saupoudrer de cacao avant de servir.',
    ],
  },
  {
    id: 'it-5',
    name: 'Osso Buco',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGV3fGVufDF8fHx8MTc2MDkyNTUzMnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 120,
    servings: 4,
    difficulty: 'Difficile',
    category: 'Italien',
    ingredients: [
      { item: 'Jarret de veau', quantity: '4 tranches' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Vin blanc', quantity: '200ml' },
      { item: 'Bouillon de bœuf', quantity: '300ml' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Céleri', quantity: '2 branches' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Ail', quantity: '3 gousses' },
    ],
    steps: [
      'Ficeler les tranches de jarret pour maintenir la viande.',
      'Fariner et faire dorer la viande dans une cocotte.',
      'Ajouter les légumes coupés en brunoise.',
      'Verser le vin blanc et laisser réduire.',
      'Ajouter les tomates et le bouillon.',
      'Couvrir et laisser mijoter 2h à feu doux.',
      'Préparer la gremolata : persil, ail et zeste de citron.',
      'Servir l\'osso buco avec la gremolata et un risotto milanais.',
    ],
  },

  // ===== RECETTES ASIATIQUES =====
  {
    id: 'as-1',
    name: 'Pad Thaï',
    image: 'https://images.unsplash.com/photo-1637806930600-37fa8892069d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWQlMjB0aGFpfGVufDF8fHx8MTc2MjMxNzY5Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Nouilles de riz', quantity: '300g' },
      { item: 'Crevettes', quantity: '300g' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Germes de soja', quantity: '100g' },
      { item: 'Cacahuètes', quantity: '50g' },
      { item: 'Sauce de poisson', quantity: '3 c. à soupe' },
      { item: 'Sauce soja', quantity: '2 c. à soupe' },
      { item: 'Citron vert', quantity: '2' },
    ],
    steps: [
      'Faire tremper les nouilles dans l\'eau chaude 10 minutes.',
      'Faire revenir les crevettes dans un wok avec de l\'huile.',
      'Pousser sur le côté et casser les œufs, brouiller rapidement.',
      'Ajouter les nouilles égouttées.',
      'Verser les sauces et mélanger vivement.',
      'Ajouter les germes de soja et cacahuètes concassées.',
      'Servir avec des quartiers de citron vert.',
    ],
  },
  {
    id: 'as-2',
    name: 'Sushi Variés',
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXNoaXxlbnwxfHx8fDE3NjI0MjU0MTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 60,
    cookTime: 20,
    servings: 4,
    difficulty: 'Difficile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Riz à sushi', quantity: '400g' },
      { item: 'Vinaigre de riz', quantity: '60ml' },
      { item: 'Saumon frais', quantity: '200g' },
      { item: 'Thon frais', quantity: '200g' },
      { item: 'Avocat', quantity: '2' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Algues nori', quantity: '10 feuilles' },
      { item: 'Wasabi', quantity: 'Au goût' },
    ],
    steps: [
      'Cuire le riz selon les instructions et le mélanger avec le vinaigre.',
      'Laisser refroidir le riz à température ambiante.',
      'Couper le poisson en fines lamelles.',
      'Placer une feuille de nori sur le tapis de bambou.',
      'Étaler une fine couche de riz sur le nori.',
      'Disposer les garnitures au centre.',
      'Rouler fermement en utilisant le tapis.',
      'Couper en tranches et servir avec sauce soja et wasabi.',
    ],
  },
  {
    id: 'as-3',
    name: 'Ramen Japonais',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyYW1lbiUyMG5vb2RsZXN8ZW58MXx8fHwxNzYyNDE3MjYyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Nouilles ramen', quantity: '400g' },
      { item: 'Porc', quantity: '400g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Bouillon de poulet', quantity: '1.5L' },
      { item: 'Sauce soja', quantity: '4 c. à soupe' },
      { item: 'Miso', quantity: '2 c. à soupe' },
      { item: 'Oignon nouveau', quantity: '4' },
      { item: 'Champignons', quantity: '200g' },
    ],
    steps: [
      'Faire cuire le porc mariné dans la sauce soja 30 minutes.',
      'Préparer les œufs mollets (6 minutes) et les mariner.',
      'Préparer le bouillon avec miso et sauce soja.',
      'Cuire les nouilles selon les instructions.',
      'Faire sauter les champignons.',
      'Répartir les nouilles dans les bols.',
      'Verser le bouillon chaud.',
      'Garnir de porc tranché, œuf coupé en deux, champignons et oignons.',
    ],
  },
  {
    id: 'as-4',
    name: 'Nems aux Légumes',
    image: 'https://images.unsplash.com/photo-1695712641569-05eee7b37b6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcHJpbmclMjByb2xsc3xlbnwxfHx8fDE3NjI0MDAyNzN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 20,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Galettes de riz', quantity: '12' },
      { item: 'Chou chinois', quantity: '200g' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Vermicelles de riz', quantity: '100g' },
      { item: 'Porc haché', quantity: '200g' },
      { item: 'Crevettes', quantity: '150g' },
      { item: 'Sauce soja', quantity: '2 c. à soupe' },
      { item: 'Huile pour friture', quantity: '1L' },
    ],
    steps: [
      'Faire tremper les vermicelles 10 minutes et les égoutter.',
      'Faire revenir le porc haché avec les légumes coupés.',
      'Ajouter les vermicelles et la sauce soja.',
      'Laisser refroidir la farce.',
      'Humidifier les galettes de riz.',
      'Déposer la farce au centre et rouler fermement.',
      'Faire frire les nems jusqu\'à ce qu\'ils soient dorés.',
      'Servir avec sauce nuoc-mâm.',
    ],
  },

  // ===== RECETTES MEXICAINES =====
  {
    id: 'mx-1',
    name: 'Tacos au Bœuf',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YWNvc3xlbnwxfHx8fDE3NjIzNzAxMDJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Mexicain',
    ingredients: [
      { item: 'Tortillas', quantity: '8' },
      { item: 'Bœuf haché', quantity: '500g' },
      { item: 'Tomates', quantity: '3' },
      { item: 'Laitue', quantity: '1' },
      { item: 'Fromage râpé', quantity: '150g' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Épices mexicaines', quantity: '2 c. à soupe' },
      { item: 'Crème aigre', quantity: '200ml' },
    ],
    steps: [
      'Faire revenir l\'oignon émincé.',
      'Ajouter le bœuf haché et les épices.',
      'Cuire jusqu\'à ce que la viande soit bien dorée.',
      'Réchauffer les tortillas.',
      'Couper les tomates et la laitue.',
      'Garnir chaque tortilla de viande.',
      'Ajouter laitue, tomates, fromage et crème.',
      'Plier et servir immédiatement.',
    ],
  },
  {
    id: 'mx-2',
    name: 'Guacamole Maison',
    image: 'https://images.unsplash.com/photo-1595016111459-799a195e7452?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxndWFjYW1vbGV8ZW58MXx8fHwxNzYyNDI1NDE5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Mexicain',
    ingredients: [
      { item: 'Avocats', quantity: '3' },
      { item: 'Tomate', quantity: '1' },
      { item: 'Oignon rouge', quantity: '1/2' },
      { item: 'Citron vert', quantity: '2' },
      { item: 'Coriandre fraîche', quantity: '1 bouquet' },
      { item: 'Piment jalapeño', quantity: '1' },
      { item: 'Sel', quantity: 'Au goût' },
    ],
    steps: [
      'Couper les avocats en deux et retirer les noyaux.',
      'Écraser la chair à la fourchette.',
      'Hacher finement l\'oignon, la tomate, le piment et la coriandre.',
      'Mélanger tous les ingrédients avec l\'avocat.',
      'Presser les citrons verts et ajouter le jus.',
      'Saler et mélanger.',
      'Servir immédiatement avec des chips de maïs.',
    ],
  },
  {
    id: 'mx-3',
    name: 'Fajitas au Poulet',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YWNvc3xlbnwxfHx8fDE3NjIzNzAxMDJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Mexicain',
    ingredients: [
      { item: 'Poulet', quantity: '500g' },
      { item: 'Poivrons', quantity: '3 (rouge, vert, jaune)' },
      { item: 'Oignon', quantity: '2' },
      { item: 'Tortillas', quantity: '8' },
      { item: 'Épices fajitas', quantity: '2 c. à soupe' },
      { item: 'Citron vert', quantity: '2' },
      { item: 'Huile d\'olive', quantity: '3 c. à soupe' },
      { item: 'Crème aigre', quantity: '200ml' },
    ],
    steps: [
      'Couper le poulet en lanières et mariner avec épices et citron.',
      'Émincer les poivrons et les oignons.',
      'Faire revenir le poulet dans l\'huile chaude.',
      'Ajouter les légumes et cuire 10 minutes.',
      'Réchauffer les tortillas.',
      'Servir les légumes et le poulet dans les tortillas.',
      'Accompagner de crème aigre et guacamole.',
    ],
  },

  // ===== RECETTES AMÉRICAINES =====
  {
    id: 'us-1',
    name: 'Burger Classique',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW1idXJnZXJ8ZW58MXx8fHwxNzYyNDI1NDE5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Américain',
    ingredients: [
      { item: 'Bœuf haché', quantity: '600g' },
      { item: 'Pains à burger', quantity: '4' },
      { item: 'Cheddar', quantity: '4 tranches' },
      { item: 'Tomate', quantity: '2' },
      { item: 'Laitue', quantity: '4 feuilles' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Cornichons', quantity: '8' },
      { item: 'Sauce burger', quantity: '4 c. à soupe' },
    ],
    steps: [
      'Former 4 steaks avec le bœuf haché, saler et poivrer.',
      'Faire cuire les steaks 3-4 minutes de chaque côté.',
      'Ajouter le fromage 1 minute avant la fin.',
      'Griller légèrement les pains.',
      'Tartiner les pains de sauce.',
      'Assembler : salade, steak, tomate, oignon, cornichons.',
      'Servir avec des frites.',
    ],
  },
  {
    id: 'us-2',
    name: 'Pancakes Américains',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYW5jYWtlc3xlbnwxfHx8fDE3NjI0MjU0MjR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Américain',
    ingredients: [
      { item: 'Farine', quantity: '250g' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Lait', quantity: '300ml' },
      { item: 'Sucre', quantity: '30g' },
      { item: 'Levure chimique', quantity: '2 c. à café' },
      { item: 'Beurre', quantity: '40g' },
      { item: 'Sirop d\'érable', quantity: '200ml' },
      { item: 'Sel', quantity: '1 pincée' },
    ],
    steps: [
      'Mélanger la farine, sucre, levure et sel.',
      'Battre les œufs avec le lait.',
      'Incorporer les ingrédients secs aux liquides.',
      'Ajouter le beurre fondu.',
      'Laisser reposer 5 minutes.',
      'Cuire des louches de pâte dans une poêle beurrée.',
      'Servir empilés avec sirop d\'érable et fruits.',
    ],
  },
  {
    id: 'us-3',
    name: 'Brownies au Chocolat',
    image: 'https://images.unsplash.com/photo-1636743715220-d8f8dd900b87?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicm93bmllc3xlbnwxfHx8fDE3NjI0MjU0MjR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 12,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Chocolat noir', quantity: '200g' },
      { item: 'Beurre', quantity: '150g' },
      { item: 'Sucre', quantity: '200g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Farine', quantity: '100g' },
      { item: 'Cacao en poudre', quantity: '30g' },
      { item: 'Sel', quantity: '1 pincée' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Faire fondre le chocolat et le beurre au bain-marie.',
      'Battre les œufs avec le sucre.',
      'Incorporer le chocolat fondu.',
      'Ajouter la farine, le cacao et le sel.',
      'Verser dans un moule beurré.',
      'Enfourner 25 minutes (le centre doit rester fondant).',
      'Laisser refroidir avant de découper.',
    ],
  },

  // ===== RECETTES MÉDITERRANÉENNES =====
  {
    id: 'md-1',
    name: 'Salade César',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYWVzYXIlMjBzYWxhZHxlbnwxfHx8fDE3NjIzMzQwMjd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Méditerranéen',
    ingredients: [
      { item: 'Laitue romaine', quantity: '2' },
      { item: 'Poulet', quantity: '300g' },
      { item: 'Parmesan', quantity: '100g' },
      { item: 'Croûtons', quantity: '100g' },
      { item: 'Œuf', quantity: '1' },
      { item: 'Anchois', quantity: '4 filets' },
      { item: 'Citron', quantity: '1' },
      { item: 'Huile d\'olive', quantity: '100ml' },
    ],
    steps: [
      'Faire griller le poulet et le couper en lamelles.',
      'Laver et couper la laitue en morceaux.',
      'Préparer la sauce : mixer jaune d\'œuf, anchois, citron et huile.',
      'Ajouter le parmesan râpé à la sauce.',
      'Mélanger la laitue avec la sauce.',
      'Ajouter le poulet et les croûtons.',
      'Servir avec du parmesan en copeaux.',
    ],
  },
  {
    id: 'md-2',
    name: 'Paella Valenciana',
    image: 'https://images.unsplash.com/photo-1650964807311-970cb88d347c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWVsbGF8ZW58MXx8fHwxNzYyNDI1NDIxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Méditerranéen',
    ingredients: [
      { item: 'Riz', quantity: '400g' },
      { item: 'Poulet', quantity: '400g' },
      { item: 'Crevettes', quantity: '300g' },
      { item: 'Moules', quantity: '500g' },
      { item: 'Poivron rouge', quantity: '1' },
      { item: 'Petits pois', quantity: '150g' },
      { item: 'Safran', quantity: '1 pincée' },
      { item: 'Bouillon de poulet', quantity: '1L' },
    ],
    steps: [
      'Faire revenir le poulet coupé en morceaux.',
      'Ajouter le poivron émincé.',
      'Incorporer le riz et le faire nacrer.',
      'Ajouter le safran et le bouillon chaud.',
      'Laisser cuire 15 minutes sans remuer.',
      'Ajouter les crevettes, moules et petits pois.',
      'Poursuivre la cuisson 10 minutes.',
      'Laisser reposer 5 minutes avant de servir.',
    ],
  },
  {
    id: 'md-3',
    name: 'Falafels aux Pois Chiches',
    image: 'https://images.unsplash.com/photo-1593001872095-7d5b3868fb1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYWxhZmVsfGVufDF8fHx8MTc2MjQyNTQyMnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Méditerranéen',
    ingredients: [
      { item: 'Pois chiches', quantity: '400g (cuits)' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Persil', quantity: '1 bouquet' },
      { item: 'Coriandre', quantity: '1 bouquet' },
      { item: 'Cumin', quantity: '1 c. à café' },
      { item: 'Farine', quantity: '50g' },
      { item: 'Huile pour friture', quantity: '1L' },
    ],
    steps: [
      'Mixer les pois chiches avec oignon et ail.',
      'Ajouter persil, coriandre, cumin et farine.',
      'Mélanger jusqu\'à obtenir une pâte homogène.',
      'Former des boulettes avec les mains mouillées.',
      'Faire frire dans l\'huile chaude 4-5 minutes.',
      'Égoutter sur du papier absorbant.',
      'Servir avec sauce tahini et salade.',
    ],
  },

  // ===== DESSERTS SUPPLÉMENTAIRES =====
  {
    id: 'ds-1',
    name: 'Crêpes Suzette',
    image: 'https://images.unsplash.com/photo-1519676867240-f9f3f182631c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmVwZXN8ZW58MXx8fHwxNzYwOTI1NTMyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 20,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '250g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Lait', quantity: '500ml' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Sucre', quantity: '80g' },
      { item: 'Orange', quantity: '3' },
      { item: 'Grand Marnier', quantity: '50ml' },
    ],
    steps: [
      'Préparer la pâte à crêpes : mélanger farine, œufs et lait.',
      'Laisser reposer 30 minutes.',
      'Faire cuire les crêpes dans une poêle beurrée.',
      'Préparer le beurre d\'orange : mélanger beurre, sucre et zeste d\'orange.',
      'Dans une poêle, faire fondre le beurre d\'orange avec le jus d\'orange.',
      'Plier les crêpes en quatre et les passer dans la sauce.',
      'Flamber avec le Grand Marnier et servir immédiatement.',
    ],
  },
  {
    id: 'ds-2',
    name: 'Tarte Tatin',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcHBsZSUyMHRhcnR8ZW58MXx8fHwxNzYwOTI1NTMyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 40,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Pommes', quantity: '8' },
      { item: 'Pâte feuilletée', quantity: '1' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Vanille', quantity: '1 gousse' },
    ],
    steps: [
      'Éplucher et couper les pommes en quartiers.',
      'Dans un moule, faire un caramel avec le beurre et le sucre.',
      'Disposer les pommes serrées sur le caramel.',
      'Ajouter les graines de vanille.',
      'Cuire 20 minutes à feu moyen.',
      'Couvrir avec la pâte feuilletée en rentrant les bords.',
      'Enfourner à 180°C pendant 20 minutes.',
      'Démouler sur un plat en retournant rapidement.',
    ],
  },
  {
    id: 'ds-3',
    name: 'Clafoutis aux Cerises',
    image: 'https://images.unsplash.com/photo-1565299543923-37dd37887442?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGVycnklMjBkZXNzZXJ0fGVufDF8fHx8MTc2MDkyNTUzMnww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Cerises', quantity: '500g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Farine', quantity: '100g' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Lait', quantity: '300ml' },
      { item: 'Beurre', quantity: '30g' },
      { item: 'Vanille', quantity: '1 c. à café' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Laver et dénoyauter les cerises (ou garder les noyaux).',
      'Beurrer un plat à gratin et y disposer les cerises.',
      'Battre les œufs avec le sucre et la vanille.',
      'Ajouter la farine puis le lait progressivement.',
      'Verser la pâte sur les cerises.',
      'Enfourner 40 minutes jusqu\'à ce que le clafoutis soit doré.',
      'Saupoudrer de sucre glace avant de servir tiède.',
    ],
  },
  {
    id: 'ds-4',
    name: 'Gâteau au Chocolat Fondant',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaG9jb2xhdGUlMjBjYWtlfGVufDF8fHx8MTc2MjQwMjYwNHww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Chocolat noir', quantity: '200g' },
      { item: 'Beurre', quantity: '200g' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Farine', quantity: '80g' },
      { item: 'Sel', quantity: '1 pincée' },
    ],
    steps: [
      'Préchauffer le four à 180°C.',
      'Faire fondre le chocolat et le beurre au bain-marie.',
      'Battre les œufs avec le sucre jusqu\'à blanchiment.',
      'Incorporer le chocolat fondu.',
      'Ajouter la farine et le sel tamisés.',
      'Verser dans un moule beurré et fariné.',
      'Enfourner 25 minutes (le cœur doit rester coulant).',
      'Laisser tiédir avant de démouler.',
    ],
  },
  {
    id: 'ds-5',
    name: 'Cheesecake New-Yorkais',
    image: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGVlc2VjYWtlfGVufDF8fHx8MTc2MjQyNTQyNHww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 30,
    cookTime: 60,
    servings: 10,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Biscuits digestifs', quantity: '250g' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Fromage frais', quantity: '600g' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Vanille', quantity: '1 c. à café' },
      { item: 'Citron', quantity: '1' },
    ],
    steps: [
      'Écraser les biscuits et mélanger avec le beurre fondu.',
      'Tasser au fond d\'un moule à charnière.',
      'Battre le fromage avec le sucre.',
      'Ajouter les œufs un par un, puis la crème.',
      'Incorporer vanille et zeste de citron.',
      'Verser sur la base de biscuits.',
      'Enfourner à 160°C pendant 60 minutes.',
      'Laisser refroidir puis réfrigérer 4h minimum.',
    ],
  },

  // ===== SOUPES ET ENTRÉES =====
  {
    id: 'sp-1',
    name: 'Gazpacho Andalou',
    image: 'https://images.unsplash.com/photo-1529566186297-155c18f9a434?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYXpwYWNob3xlbnwxfHx8fDE3NjI0MjU0MjR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Méditerranéen',
    ingredients: [
      { item: 'Tomates', quantity: '1kg' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Poivron rouge', quantity: '1' },
      { item: 'Oignon rouge', quantity: '1/2' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Pain', quantity: '100g' },
      { item: 'Vinaigre de xérès', quantity: '2 c. à soupe' },
      { item: 'Huile d\'olive', quantity: '100ml' },
    ],
    steps: [
      'Faire tremper le pain dans de l\'eau.',
      'Couper tous les légumes en morceaux.',
      'Mixer tous les ingrédients ensemble.',
      'Ajouter le vinaigre et l\'huile d\'olive.',
      'Ajuster l\'assaisonnement.',
      'Réfrigérer au moins 2h.',
      'Servir bien frais avec des croûtons.',
    ],
  },
  {
    id: 'sp-2',
    name: 'Soupe Tom Yum',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aGFpJTIwc291cHxlbnwxfHx8fDE3NjI0MjU0MjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Bouillon de poulet', quantity: '1L' },
      { item: 'Crevettes', quantity: '300g' },
      { item: 'Champignons', quantity: '200g' },
      { item: 'Tomate', quantity: '2' },
      { item: 'Citronnelle', quantity: '2 tiges' },
      { item: 'Gingembre', quantity: '30g' },
      { item: 'Piment', quantity: '2' },
      { item: 'Citron vert', quantity: '2' },
    ],
    steps: [
      'Porter le bouillon à ébullition avec citronnelle et gingembre.',
      'Ajouter les champignons et tomates coupées.',
      'Cuire 10 minutes à feu moyen.',
      'Ajouter les crevettes et le piment.',
      'Cuire 5 minutes supplémentaires.',
      'Presser les citrons verts.',
      'Retirer la citronnelle avant de servir.',
    ],
  },
  {
    id: 'sp-3',
    name: 'Wok de Légumes',
    image: 'https://images.unsplash.com/photo-1464500650248-1a4b45debb9f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2ZWdldGFibGUlMjBzdGlyJTIwZnJ5fGVufDF8fHx8MTc2MjMyODcyOHww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Brocoli', quantity: '200g' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Poivron', quantity: '2' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Sauce soja', quantity: '4 c. à soupe' },
      { item: 'Gingembre', quantity: '20g' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Huile de sésame', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Couper tous les légumes en julienne.',
      'Faire chauffer le wok à feu très vif.',
      'Ajouter l\'huile, ail et gingembre.',
      'Faire sauter les légumes 5-7 minutes.',
      'Ajouter la sauce soja.',
      'Mélanger constamment.',
      'Servir immédiatement avec du riz.',
    ],
  },
  {
    id: 'sp-4',
    name: 'Saumon Teriyaki',
    image: 'https://images.unsplash.com/photo-1700706259342-3b4f681f9bfe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYWxtb24lMjB0ZXJpeWFraXxlbnwxfHx8fDE3NjIzNDMwODB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Pavés de saumon', quantity: '4' },
      { item: 'Sauce soja', quantity: '100ml' },
      { item: 'Mirin', quantity: '50ml' },
      { item: 'Sucre', quantity: '2 c. à soupe' },
      { item: 'Gingembre', quantity: '20g' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Sésame', quantity: '2 c. à soupe' },
      { item: 'Oignon nouveau', quantity: '2' },
    ],
    steps: [
      'Préparer la marinade : mélanger sauce soja, mirin, sucre, gingembre et ail.',
      'Mariner le saumon 30 minutes.',
      'Faire cuire le saumon à la poêle 4 minutes de chaque côté.',
      'Verser le reste de marinade dans la poêle.',
      'Laisser réduire jusqu\'à obtenir une sauce épaisse.',
      'Napper le saumon de sauce.',
      'Parsemer de sésame et oignon nouveau.',
      'Servir avec du riz blanc.',
    ],
  },
  {
    id: 'sp-5',
    name: 'Pain Perdu',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVuY2glMjB0b2FzdHxlbnwxfHx8fDE3NjIzNzM5OTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pain rassis', quantity: '8 tranches' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Lait', quantity: '200ml' },
      { item: 'Sucre', quantity: '50g' },
      { item: 'Vanille', quantity: '1 c. à café' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Cannelle', quantity: '1 c. à café' },
    ],
    steps: [
      'Battre les œufs avec le lait, sucre et vanille.',
      'Tremper les tranches de pain dans le mélange.',
      'Faire fondre le beurre dans une poêle.',
      'Faire dorer les tranches 2-3 minutes de chaque côté.',
      'Saupoudrer de sucre et cannelle.',
      'Servir chaud avec sirop d\'érable ou confiture.',
    ],
  },

  // ===== NOUVELLES RECETTES =====
  {
    id: 'new-1',
    name: 'Salade Grecque',
    image: 'https://images.unsplash.com/photo-1606735584785-1848fdcaea57?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmVlayUyMHNhbGFkfGVufDF8fHx8MTc2MjQxOTQyNHww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Méditerranéen',
    ingredients: [
      { item: 'Tomates', quantity: '4' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Poivron vert', quantity: '1' },
      { item: 'Oignon rouge', quantity: '1' },
      { item: 'Feta', quantity: '200g' },
      { item: 'Olives noires', quantity: '100g' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
      { item: 'Origan', quantity: '1 c. à café' },
    ],
    steps: [
      'Couper les tomates, concombre et poivron en morceaux.',
      'Émincer finement l\'oignon rouge.',
      'Disposer tous les légumes dans un saladier.',
      'Ajouter les olives noires et la feta en cubes.',
      'Arroser d\'huile d\'olive.',
      'Saupoudrer d\'origan.',
      'Servir frais sans mélanger.',
    ],
  },
  {
    id: 'new-2',
    name: 'Houmous Maison',
    image: 'https://images.unsplash.com/photo-1637949385162-e416fb15b2ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxodW1tdXN8ZW58MXx8fHwxNzYyNDI1ODc3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 0,
    servings: 6,
    difficulty: 'Facile',
    category: 'Méditerranéen',
    ingredients: [
      { item: 'Pois chiches', quantity: '400g (en conserve)' },
      { item: 'Tahini', quantity: '3 c. à soupe' },
      { item: 'Citron', quantity: '2' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Cumin', quantity: '1 c. à café' },
      { item: 'Huile d\'olive', quantity: '3 c. à soupe' },
      { item: 'Sel', quantity: 'Au goût' },
    ],
    steps: [
      'Égoutter les pois chiches en gardant le jus.',
      'Mixer les pois chiches avec l\'ail et le citron.',
      'Ajouter le tahini et le cumin.',
      'Mixer en ajoutant progressivement le jus des pois chiches.',
      'Ajuster la texture avec de l\'eau si nécessaire.',
      'Saler et ajouter l\'huile d\'olive.',
      'Servir avec paprika et pain pita.',
    ],
  },
  {
    id: 'new-3',
    name: 'Curry de Poulet',
    image: 'https://images.unsplash.com/photo-1631292784640-2b24be784d5d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwY3Vycnl8ZW58MXx8fHwxNzYyNDA5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Poulet', quantity: '600g' },
      { item: 'Lait de coco', quantity: '400ml' },
      { item: 'Curry en poudre', quantity: '2 c. à soupe' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Tomates', quantity: '2' },
      { item: 'Gingembre', quantity: '20g' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Coriandre', quantity: '1 bouquet' },
    ],
    steps: [
      'Couper le poulet en morceaux.',
      'Faire revenir l\'oignon, l\'ail et le gingembre.',
      'Ajouter le curry et faire revenir 1 minute.',
      'Incorporer le poulet et faire dorer.',
      'Ajouter les tomates coupées et le lait de coco.',
      'Laisser mijoter 25 minutes à feu doux.',
      'Parsemer de coriandre fraîche.',
      'Servir avec du riz basmati.',
    ],
  },
  {
    id: 'new-4',
    name: 'Tacos au Poisson',
    image: 'https://images.unsplash.com/photo-1604467715878-83e57e8bc129?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaXNoJTIwdGFjb3N8ZW58MXx8fHwxNzYyMzY2MDgwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Mexicain',
    ingredients: [
      { item: 'Filets de poisson blanc', quantity: '500g' },
      { item: 'Tortillas', quantity: '8' },
      { item: 'Chou blanc', quantity: '200g' },
      { item: 'Avocat', quantity: '2' },
      { item: 'Citron vert', quantity: '3' },
      { item: 'Crème aigre', quantity: '150ml' },
      { item: 'Coriandre', quantity: '1 bouquet' },
      { item: 'Paprika', quantity: '1 c. à café' },
    ],
    steps: [
      'Couper le poisson en morceaux et assaisonner de paprika.',
      'Faire griller le poisson 3-4 minutes de chaque côté.',
      'Émincer finement le chou.',
      'Préparer la sauce : mélanger crème, citron vert et coriandre.',
      'Réchauffer les tortillas.',
      'Garnir avec chou, poisson et avocat tranché.',
      'Arroser de sauce et ajouter du citron vert.',
    ],
  },
  {
    id: 'new-5',
    name: 'Ailes de Poulet BBQ',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwd2luZ3N8ZW58MXx8fHwxNzYyMzc0NDIxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: 'Facile',
    category: 'Américain',
    ingredients: [
      { item: 'Ailes de poulet', quantity: '1kg' },
      { item: 'Sauce BBQ', quantity: '200ml' },
      { item: 'Miel', quantity: '2 c. à soupe' },
      { item: 'Sauce soja', quantity: '2 c. à soupe' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Paprika', quantity: '1 c. à café' },
      { item: 'Sel et poivre', quantity: 'Au goût' },
    ],
    steps: [
      'Préchauffer le four à 200°C.',
      'Mélanger sauce BBQ, miel, sauce soja et ail écrasé.',
      'Assaisonner les ailes de sel, poivre et paprika.',
      'Disposer les ailes sur une plaque.',
      'Badigeonner de sauce.',
      'Enfourner 30-35 minutes en retournant à mi-cuisson.',
      'Servir chaud avec sauce ranch.',
    ],
  },
  {
    id: 'new-6',
    name: 'Pâtes au Pesto',
    image: 'https://images.unsplash.com/photo-1567608285969-48e4bbe0d399?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXN0YSUyMHBlc3RvfGVufDF8fHx8MTc2MjQyNTg3OHww&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 12,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes', quantity: '400g' },
      { item: 'Basilic frais', quantity: '100g' },
      { item: 'Pignons de pin', quantity: '50g' },
      { item: 'Parmesan', quantity: '80g' },
      { item: 'Ail', quantity: '2 gousses' },
      { item: 'Huile d\'olive', quantity: '150ml' },
      { item: 'Sel', quantity: 'Au goût' },
    ],
    steps: [
      'Mixer le basilic, pignons, ail et parmesan.',
      'Ajouter l\'huile d\'olive progressivement en mixant.',
      'Saler et ajuster la consistance.',
      'Faire cuire les pâtes al dente.',
      'Égoutter les pâtes en gardant un peu d\'eau de cuisson.',
      'Mélanger les pâtes avec le pesto.',
      'Ajouter un peu d\'eau de cuisson si nécessaire.',
      'Servir avec du parmesan râpé.',
    ],
  },
  {
    id: 'new-26',
    name: 'Pancakes Américains',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYW5jYWtlc3xlbnwxfHx8fDE3NjI0MjU0MjR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Américain',
    ingredients: [
      { item: 'Farine', quantity: '250g' },
      { item: 'Lait', quantity: '300ml' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Sucre', quantity: '30g' },
      { item: 'Levure chimique', quantity: '1 sachet' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Sirop d\'érable', quantity: 'Au goût' },
    ],
    steps: [
      'Mélanger farine, sucre et levure.',
      'Battre les œufs avec le lait.',
      'Incorporer au mélange sec.',
      'Faire fondre le beurre et ajouter.',
      'Laisser reposer 10 minutes.',
      'Cuire dans une poêle chaude.',
      'Empiler et servir avec sirop d\'érable.',
    ],
  },
];
