// Collection SUPER de 100 recettes supplémentaires !
import type { Recipe } from '../components/RecipesScreen';

export const superRecipes: Recipe[] = [
  // ===== VIANDES VARIÉES =====
  {
    id: 'super-1',
    name: 'Poulet Yassa',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 120,
    cookTime: 45,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Africain',
    ingredients: [
      { item: 'Poulet', quantity: '1.5kg' },
      { item: 'Oignons', quantity: '6' },
      { item: 'Citrons', quantity: '4' },
      { item: 'Moutarde', quantity: '3 c. à soupe' },
      { item: 'Olives', quantity: '150g' },
    ],
    steps: [
      'Faire mariner le poulet 2h dans citron et oignons.',
      'Faire revenir les oignons.',
      'Ajouter le poulet mariné.',
      'Incorporer moutarde et olives.',
      'Mijoter 45 minutes.',
    ],
  },
  {
    id: 'super-2',
    name: 'Escalope Milanaise',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Escalopes de veau', quantity: '4' },
      { item: 'Chapelure', quantity: '150g' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Parmesan', quantity: '50g' },
      { item: 'Citron', quantity: '1' },
    ],
    steps: [
      'Battre les œufs.',
      'Mélanger chapelure et parmesan.',
      'Paner les escalopes.',
      'Faire dorer à la poêle.',
      'Servir avec citron.',
    ],
  },
  {
    id: 'super-3',
    name: 'Boulettes Suédoises',
    image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Scandinave',
    ingredients: [
      { item: 'Viande hachée', quantity: '500g' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Bouillon', quantity: '300ml' },
      { item: 'Confiture airelles', quantity: '100g' },
      { item: 'Chapelure', quantity: '50g' },
    ],
    steps: [
      'Former des boulettes.',
      'Les faire dorer.',
      'Préparer une sauce crème-bouillon.',
      'Mijoter les boulettes dans la sauce.',
      'Servir avec confiture.',
    ],
  },
  {
    id: 'super-4',
    name: 'Travers de Porc BBQ',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 120,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Américain',
    ingredients: [
      { item: 'Travers de porc', quantity: '1.5kg' },
      { item: 'Sauce BBQ', quantity: '300ml' },
      { item: 'Miel', quantity: '3 c. à soupe' },
      { item: 'Paprika', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Assaisonner les travers.',
      'Cuire au four 2h à 150°C.',
      'Badigeonner de sauce BBQ.',
      'Griller 10 min à haute température.',
    ],
  },
  {
    id: 'super-5',
    name: 'Saltimbocca Romana',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Escalopes de veau', quantity: '8' },
      { item: 'Jambon cru', quantity: '8 tranches' },
      { item: 'Sauge', quantity: '16 feuilles' },
      { item: 'Vin blanc', quantity: '100ml' },
    ],
    steps: [
      'Placer jambon et sauge sur les escalopes.',
      'Fixer avec cure-dents.',
      'Faire dorer rapidement.',
      'Déglacer au vin blanc.',
      'Servir immédiatement.',
    ],
  },

  // ===== PLATS VÉGÉTARIENS =====
  {
    id: 'super-6',
    name: 'Dahl de Lentilles',
    image: 'https://images.unsplash.com/photo-1683743127028-7389d247337b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: 'Facile',
    category: 'Indien',
    ingredients: [
      { item: 'Lentilles corail', quantity: '400g' },
      { item: 'Lait de coco', quantity: '400ml' },
      { item: 'Tomates', quantity: '400g' },
      { item: 'Curry', quantity: '2 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
    ],
    steps: [
      'Faire revenir oignon et gingembre.',
      'Ajouter curry et lentilles.',
      'Verser lait de coco et tomates.',
      'Cuire 25 minutes.',
      'Servir avec riz et naan.',
    ],
  },
  {
    id: 'super-7',
    name: 'Gratin de Potiron',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Potiron', quantity: '1kg' },
      { item: 'Crème fraîche', quantity: '300ml' },
      { item: 'Gruyère', quantity: '200g' },
      { item: 'Muscade', quantity: '1 pincée' },
    ],
    steps: [
      'Couper le potiron en dés.',
      'Le faire cuire légèrement.',
      'Disposer dans un plat.',
      'Napper de crème.',
      'Parsemer de gruyère et cuire 35 min.',
    ],
  },
  {
    id: 'super-8',
    name: 'Tarte Poireaux Chèvre',
    image: 'https://images.unsplash.com/photo-1627308595232-d0cd54b31a4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pâte brisée', quantity: '1' },
      { item: 'Poireaux', quantity: '3' },
      { item: 'Chèvre', quantity: '150g' },
      { item: 'Crème', quantity: '150ml' },
      { item: 'Œufs', quantity: '2' },
    ],
    steps: [
      'Faire fondre les poireaux.',
      'Battre œufs et crème.',
      'Disposer poireaux et chèvre sur la pâte.',
      'Verser l\'appareil.',
      'Cuire 35 min.',
    ],
  },
  {
    id: 'super-9',
    name: 'Soupe au Pistou',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 40,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Haricots blancs', quantity: '300g' },
      { item: 'Légumes variés', quantity: '800g' },
      { item: 'Basilic', quantity: '2 bottes' },
      { item: 'Parmesan', quantity: '100g' },
      { item: 'Ail', quantity: '4 gousses' },
    ],
    steps: [
      'Cuire légumes et haricots dans un bouillon.',
      'Préparer le pistou: basilic, ail, parmesan.',
      'Servir la soupe avec le pistou.',
    ],
  },
  {
    id: 'super-10',
    name: 'Polenta Crémeuse',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Polenta', quantity: '250g' },
      { item: 'Bouillon', quantity: '1L' },
      { item: 'Parmesan', quantity: '100g' },
      { item: 'Beurre', quantity: '50g' },
    ],
    steps: [
      'Porter le bouillon à ébullition.',
      'Verser la polenta en pluie.',
      'Cuire 20 min en remuant.',
      'Incorporer beurre et parmesan.',
    ],
  },

  // ===== POISSONS & FRUITS DE MER =====
  {
    id: 'super-11',
    name: 'Crevettes Sautées à l\'Ail',
    image: 'https://images.unsplash.com/photo-1633504581786-316c8002b1b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 8,
    servings: 4,
    difficulty: 'Facile',
    category: 'Poisson',
    ingredients: [
      { item: 'Crevettes', quantity: '600g' },
      { item: 'Ail', quantity: '6 gousses' },
      { item: 'Persil', quantity: '1 bouquet' },
      { item: 'Citron', quantity: '2' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
    ],
    steps: [
      'Faire revenir l\'ail dans l\'huile.',
      'Ajouter les crevettes.',
      'Cuire 5 minutes.',
      'Ajouter persil et citron.',
    ],
  },
  {
    id: 'super-12',
    name: 'Loup de Mer Grillé',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Poisson',
    ingredients: [
      { item: 'Loup de mer', quantity: '2' },
      { item: 'Citron', quantity: '2' },
      { item: 'Fenouil', quantity: '1' },
      { item: 'Thym', quantity: '4 branches' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
    ],
    steps: [
      'Farcir les poissons de fenouil et thym.',
      'Arroser d\'huile et citron.',
      'Griller 10 min de chaque côté.',
      'Servir avec légumes grillés.',
    ],
  },
  {
    id: 'super-13',
    name: 'Calamars Frits',
    image: 'https://images.unsplash.com/photo-1626667215766-0f85a8e7ae47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Poisson',
    ingredients: [
      { item: 'Calamars', quantity: '600g' },
      { item: 'Farine', quantity: '150g' },
      { item: 'Citron', quantity: '2' },
      { item: 'Huile de friture', quantity: '1L' },
    ],
    steps: [
      'Couper les calamars en anneaux.',
      'Les fariner.',
      'Frire dans l\'huile chaude.',
      'Servir avec citron.',
    ],
  },
  {
    id: 'super-14',
    name: 'Risotto aux Fruits de Mer',
    image: 'https://images.unsplash.com/photo-1476124369491-f117991cdc65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Riz arborio', quantity: '320g' },
      { item: 'Fruits de mer', quantity: '500g' },
      { item: 'Vin blanc', quantity: '100ml' },
      { item: 'Bouillon de poisson', quantity: '1L' },
      { item: 'Parmesan', quantity: '50g' },
    ],
    steps: [
      'Faire revenir les fruits de mer.',
      'Nacrer le riz.',
      'Déglacer au vin blanc.',
      'Ajouter bouillon louche par louche.',
      'Terminer avec parmesan.',
    ],
  },
  {
    id: 'super-15',
    name: 'Sole Meunière',
    image: 'https://images.unsplash.com/photo-1707576517985-a2e912cca325?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Soles', quantity: '4' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Farine', quantity: '100g' },
      { item: 'Citron', quantity: '2' },
      { item: 'Persil', quantity: '1 bouquet' },
    ],
    steps: [
      'Fariner les soles.',
      'Cuire au beurre.',
      'Préparer un beurre noisette.',
      'Arroser de citron.',
      'Parsemer de persil.',
    ],
  },

  // ===== PLATS RAPIDES =====
  {
    id: 'super-16',
    name: 'Tortellinis Créme Épinards',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Tortellinis', quantity: '500g' },
      { item: 'Épinards', quantity: '300g' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Parmesan', quantity: '80g' },
    ],
    steps: [
      'Cuire les tortellinis.',
      'Faire revenir les épinards.',
      'Ajouter la crème.',
      'Mélanger avec les pâtes.',
    ],
  },
  {
    id: 'super-17',
    name: 'Oeufs Cocotte',
    image: 'https://images.unsplash.com/photo-1732969331543-80e52902e0a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 12,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Œufs', quantity: '8' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Jambon', quantity: '100g' },
      { item: 'Gruyère', quantity: '80g' },
    ],
    steps: [
      'Beurrer des ramequins.',
      'Mettre crème et jambon au fond.',
      'Casser les œufs.',
      'Parsemer de gruyère.',
      'Cuire au bain-marie 12 min.',
    ],
  },
  {
    id: 'super-18',
    name: 'Quesadillas au Poulet',
    image: 'https://images.unsplash.com/photo-1546853846-53490ede35b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Mexicain',
    ingredients: [
      { item: 'Tortillas', quantity: '8' },
      { item: 'Poulet', quantity: '300g' },
      { item: 'Cheddar', quantity: '200g' },
      { item: 'Poivrons', quantity: '2' },
    ],
    steps: [
      'Faire revenir poulet et poivrons.',
      'Garnir les tortillas.',
      'Ajouter fromage.',
      'Plier et griller.',
    ],
  },
  {
    id: 'super-19',
    name: 'Pâtes à la Crème de Champignons',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Rapide',
    ingredients: [
      { item: 'Pâtes', quantity: '400g' },
      { item: 'Champignons', quantity: '400g' },
      { item: 'Crème fraîche', quantity: '250ml' },
      { item: 'Ail', quantity: '2 gousses' },
    ],
    steps: [
      'Cuire les pâtes.',
      'Faire revenir champignons et ail.',
      'Ajouter la crème.',
      'Mélanger avec les pâtes.',
    ],
  },
  {
    id: 'super-20',
    name: 'Club Sandwich',
    image: 'https://images.unsplash.com/photo-1626200419455-0348c232b193?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 5,
    servings: 2,
    difficulty: 'Facile',
    category: 'Rapide',
    ingredients: [
      { item: 'Pain de mie', quantity: '6 tranches' },
      { item: 'Poulet', quantity: '200g' },
      { item: 'Bacon', quantity: '4 tranches' },
      { item: 'Salade', quantity: '4 feuilles' },
      { item: 'Tomate', quantity: '1' },
    ],
    steps: [
      'Griller le pain.',
      'Faire cuire le bacon.',
      'Superposer les ingrédients.',
      'Couper en triangle.',
    ],
  },

  // ===== DESSERTS =====
  {
    id: 'super-21',
    name: 'Crêpes au Sucre',
    image: 'https://images.unsplash.com/photo-1695518069327-60d7601794a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '250g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Lait', quantity: '500ml' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Beurre', quantity: '50g' },
    ],
    steps: [
      'Préparer la pâte à crêpes.',
      'Laisser reposer.',
      'Cuire les crêpes.',
      'Saupoudrer de sucre.',
    ],
  },
  {
    id: 'super-22',
    name: 'Îles Flottantes',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 20,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Œufs', quantity: '6' },
      { item: 'Sucre', quantity: '200g' },
      { item: 'Lait', quantity: '500ml' },
      { item: 'Vanille', quantity: '1 gousse' },
    ],
    steps: [
      'Préparer une crème anglaise.',
      'Monter les blancs en neige.',
      'Pocher les blancs dans du lait.',
      'Servir sur la crème anglaise.',
    ],
  },
  {
    id: 'super-23',
    name: 'Tarte au Citron',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 35,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte sablée', quantity: '1' },
      { item: 'Citrons', quantity: '5' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Beurre', quantity: '100g' },
    ],
    steps: [
      'Cuire la pâte à blanc.',
      'Préparer la crème au citron.',
      'Verser dans le fond de tarte.',
      'Laisser prendre au frais.',
    ],
  },
  {
    id: 'super-24',
    name: 'Financiers aux Amandes',
    image: 'https://images.unsplash.com/photo-1571506165871-ee72a35bc9d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 12,
    servings: 12,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Poudre d\'amandes', quantity: '100g' },
      { item: 'Sucre glace', quantity: '150g' },
      { item: 'Blancs d\'œufs', quantity: '4' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Farine', quantity: '40g' },
    ],
    steps: [
      'Faire un beurre noisette.',
      'Mélanger tous les ingrédients.',
      'Verser dans des moules.',
      'Cuire 12 min à 200°C.',
    ],
  },
  {
    id: 'super-25',
    name: 'Paris-Brest',
    image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 45,
    cookTime: 30,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte à choux', quantity: '250g' },
      { item: 'Crème mousseline pralinée', quantity: '400g' },
      { item: 'Amandes effilées', quantity: '50g' },
      { item: 'Sucre glace', quantity: '50g' },
    ],
    steps: [
      'Former un couronne de pâte à choux.',
      'Parsemer d\'amandes.',
      'Cuire 30 min.',
      'Garnir de crème pralinée.',
      'Saupoudrer de sucre glace.',
    ],
  },

  // ===== CUISINE DU MONDE =====
  {
    id: 'super-26',
    name: 'Empanadas',
    image: 'https://images.unsplash.com/photo-1546853846-53490ede35b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 25,
    servings: 12,
    difficulty: 'Moyen',
    category: 'Argentin',
    ingredients: [
      { item: 'Pâte à empanadas', quantity: '12' },
      { item: 'Viande hachée', quantity: '400g' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Œufs durs', quantity: '3' },
      { item: 'Olives', quantity: '100g' },
    ],
    steps: [
      'Faire revenir viande et oignons.',
      'Ajouter œufs et olives.',
      'Garnir les empanadas.',
      'Fermer en chausson.',
      'Cuire au four 25 min.',
    ],
  },
  {
    id: 'super-27',
    name: 'Katsu Curry Japonais',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Japonais',
    ingredients: [
      { item: 'Porc pané', quantity: '4 escalopes' },
      { item: 'Curry japonais', quantity: '1 boîte' },
      { item: 'Pommes de terre', quantity: '3' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Oignon', quantity: '1' },
    ],
    steps: [
      'Paner et frire le porc.',
      'Préparer le curry avec légumes.',
      'Servir avec riz.',
      'Trancher le porc dessus.',
    ],
  },
  {
    id: 'super-28',
    name: 'Bibimbap Coréen',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Coréen',
    ingredients: [
      { item: 'Riz', quantity: '400g' },
      { item: 'Bœuf', quantity: '300g' },
      { item: 'Légumes variés', quantity: '500g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Gochujang', quantity: '4 c. à soupe' },
    ],
    steps: [
      'Cuire le riz.',
      'Faire revenir le bœuf.',
      'Préparer les légumes séparément.',
      'Assembler dans des bols.',
      'Ajouter œuf et sauce.',
    ],
  },
  {
    id: 'super-29',
    name: 'Shakshuka',
    image: 'https://images.unsplash.com/photo-1732969331543-80e52902e0a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Moyen-Orient',
    ingredients: [
      { item: 'Tomates', quantity: '800g' },
      { item: 'Œufs', quantity: '6' },
      { item: 'Poivrons', quantity: '2' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Cumin', quantity: '1 c. à café' },
    ],
    steps: [
      'Faire revenir oignons et poivrons.',
      'Ajouter tomates et épices.',
      'Mijoter 10 min.',
      'Casser les œufs dessus.',
      'Couvrir jusqu\'à cuisson des œufs.',
    ],
  },
  {
    id: 'super-30',
    name: 'Samosas aux Légumes',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 20,
    servings: 12,
    difficulty: 'Moyen',
    category: 'Indien',
    ingredients: [
      { item: 'Pâte à samosas', quantity: '12' },
      { item: 'Pommes de terre', quantity: '400g' },
      { item: 'Petits pois', quantity: '150g' },
      { item: 'Curry', quantity: '2 c. à soupe' },
      { item: 'Huile de friture', quantity: '1L' },
    ],
    steps: [
      'Cuire et écraser les pommes de terre.',
      'Mélanger avec petits pois et curry.',
      'Farcir les samosas.',
      'Frire jusqu\'à dorure.',
    ],
  },

  // ===== PÂTISSERIES =====
  {
    id: 'super-31',
    name: 'Éclair au Chocolat',
    image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 60,
    cookTime: 25,
    servings: 12,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte à choux', quantity: '300g' },
      { item: 'Crème pâtissière chocolat', quantity: '400g' },
      { item: 'Fondant chocolat', quantity: '200g' },
    ],
    steps: [
      'Former des éclairs.',
      'Cuire 25 min.',
      'Garnir de crème au chocolat.',
      'Glacer au fondant.',
    ],
  },
  {
    id: 'super-32',
    name: 'Tartelettes aux Fruits',
    image: 'https://images.unsplash.com/photo-1560529666-317819712619?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 20,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte sablée', quantity: '400g' },
      { item: 'Crème pâtissière', quantity: '300ml' },
      { item: 'Fruits frais', quantity: '500g' },
      { item: 'Nappage', quantity: '100g' },
    ],
    steps: [
      'Cuire les fonds de tartelettes.',
      'Garnir de crème pâtissière.',
      'Disposer les fruits.',
      'Napper de nappage.',
    ],
  },
  {
    id: 'super-33',
    name: 'Religieuses au Café',
    image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 90,
    cookTime: 30,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte à choux', quantity: '300g' },
      { item: 'Crème au café', quantity: '400g' },
      { item: 'Fondant café', quantity: '200g' },
    ],
    steps: [
      'Former des choux de 2 tailles.',
      'Cuire 30 min.',
      'Garnir de crème au café.',
      'Glacer et assembler.',
    ],
  },
  {
    id: 'super-34',
    name: 'Tarte Normande',
    image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 40,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte brisée', quantity: '1' },
      { item: 'Pommes', quantity: '6' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Calvados', quantity: '3 c. à soupe' },
      { item: 'Sucre', quantity: '80g' },
    ],
    steps: [
      'Disposer les pommes sur la pâte.',
      'Mélanger œufs, crème, sucre et calvados.',
      'Verser sur les pommes.',
      'Cuire 40 min à 180°C.',
    ],
  },
  {
    id: 'super-35',
    name: 'Cannelés Bordelais',
    image: 'https://images.unsplash.com/photo-1571506165871-ee72a35bc9d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 60,
    servings: 12,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Lait', quantity: '500ml' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Sucre', quantity: '250g' },
      { item: 'Farine', quantity: '125g' },
      { item: 'Rhum', quantity: '50ml' },
      { item: 'Vanille', quantity: '1 gousse' },
    ],
    steps: [
      'Préparer la pâte et laisser reposer 24h.',
      'Beurrer et fariner les moules.',
      'Verser la pâte.',
      'Cuire 1h à 240°C puis 180°C.',
    ],
  },

  // Continuons avec encore plus de recettes...
  {
    id: 'super-36',
    name: 'Steak Frites',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Steaks', quantity: '4' },
      { item: 'Pommes de terre', quantity: '1kg' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Huile', quantity: '2L' },
    ],
    steps: [
      'Couper et frire les pommes de terre.',
      'Cuire les steaks au beurre.',
      'Servir ensemble.',
    ],
  },
  {
    id: 'super-37',
    name: 'Soupe de Poissons',
    image: 'https://images.unsplash.com/photo-1621339881990-c94ba5cf98fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 40,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Poissons', quantity: '1kg' },
      { item: 'Tomates', quantity: '400g' },
      { item: 'Safran', quantity: '1 pincée' },
      { item: 'Rouille', quantity: '150g' },
    ],
    steps: [
      'Faire revenir les poissons.',
      'Ajouter tomates et safran.',
      'Couvrir d\'eau et cuire 30 min.',
      'Mixer et servir avec rouille.',
    ],
  },
  {
    id: 'super-38',
    name: 'Gigot d\'Agneau',
    image: 'https://images.unsplash.com/photo-1692106914421-e04e1066bd62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 90,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Gigot d\'agneau', quantity: '2kg' },
      { item: 'Ail', quantity: '10 gousses' },
      { item: 'Romarin', quantity: '4 branches' },
      { item: 'Pommes de terre', quantity: '1.5kg' },
    ],
    steps: [
      'Piquer le gigot d\'ail.',
      'Rôtir au four avec romarin.',
      'Ajouter pommes de terre.',
      'Cuire 1h30 à 180°C.',
    ],
  },
  {
    id: 'super-39',
    name: 'Tarte Alsacienne',
    image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 40,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte brisée', quantity: '1' },
      { item: 'Pommes', quantity: '6' },
      { item: 'Crème', quantity: '200ml' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Cannelle', quantity: '1 c. à café' },
    ],
    steps: [
      'Disposer pommes sur la pâte.',
      'Mélanger crème, œufs et cannelle.',
      'Verser sur les pommes.',
      'Cuire 40 min.',
    ],
  },
  {
    id: 'super-40',
    name: 'Riz au Lait',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 40,
    servings: 6,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Riz rond', quantity: '200g' },
      { item: 'Lait', quantity: '1L' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Vanille', quantity: '1 gousse' },
    ],
    steps: [
      'Cuire le riz dans le lait.',
      'Ajouter sucre et vanille.',
      'Cuire 35 min en remuant.',
      'Servir froid ou chaud.',
    ],
  },
  // Continuons encore...
  {
    id: 'super-41',
    name: 'Salade de Pâtes Italienne',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 10,
    servings: 6,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes', quantity: '500g' },
      { item: 'Tomates cerises', quantity: '300g' },
      { item: 'Mozzarella', quantity: '200g' },
      { item: 'Basilic', quantity: '1 bouquet' },
      { item: 'Pesto', quantity: '100g' },
    ],
    steps: [
      'Cuire les pâtes.',
      'Mélanger tous les ingrédients.',
      'Assaisonner de pesto.',
      'Servir frais.',
    ],
  },
  {
    id: 'super-42',
    name: 'Poulet Korma',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Indien',
    ingredients: [
      { item: 'Poulet', quantity: '800g' },
      { item: 'Yaourt', quantity: '200g' },
      { item: 'Crème de coco', quantity: '200ml' },
      { item: 'Amandes', quantity: '100g' },
      { item: 'Épices korma', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Faire mariner le poulet.',
      'Le faire revenir avec les épices.',
      'Ajouter yaourt et crème.',
      'Incorporer les amandes.',
      'Mijoter 25 min.',
    ],
  },
  {
    id: 'super-43',
    name: 'Crumble Salé Légumes',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Légumes variés', quantity: '800g' },
      { item: 'Farine', quantity: '150g' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Parmesan', quantity: '80g' },
    ],
    steps: [
      'Faire revenir les légumes.',
      'Préparer le crumble salé.',
      'Répartir sur les légumes.',
      'Cuire 30 min à 180°C.',
    ],
  },
  {
    id: 'super-44',
    name: 'Brownies Noix de Pécan',
    image: 'https://images.unsplash.com/photo-1606312619070-d48b4f50a8e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 12,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Chocolat noir', quantity: '250g' },
      { item: 'Beurre', quantity: '200g' },
      { item: 'Sucre', quantity: '200g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Noix de pécan', quantity: '150g' },
    ],
    steps: [
      'Faire fondre chocolat et beurre.',
      'Battre œufs et sucre.',
      'Incorporer chocolat et noix.',
      'Cuire 25 min à 180°C.',
    ],
  },
  {
    id: 'super-45',
    name: 'Soupe Thaï aux Crevettes',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Crevettes', quantity: '400g' },
      { item: 'Lait de coco', quantity: '400ml' },
      { item: 'Citronnelle', quantity: '2 tiges' },
      { item: 'Piment', quantity: '2' },
      { item: 'Champignons', quantity: '200g' },
    ],
    steps: [
      'Faire chauffer lait de coco.',
      'Ajouter citronnelle et piment.',
      'Incorporer crevettes et champignons.',
      'Cuire 10 min.',
    ],
  },
  {
    id: 'super-46',
    name: 'Galette Complète Bretonne',
    image: 'https://images.unsplash.com/photo-1695518069327-60d7601794a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Farine de sarrasin', quantity: '300g' },
      { item: 'Œufs', quantity: '8' },
      { item: 'Jambon', quantity: '8 tranches' },
      { item: 'Gruyère', quantity: '200g' },
    ],
    steps: [
      'Préparer la pâte à galettes.',
      'Cuire les galettes.',
      'Garnir de jambon, œuf et fromage.',
      'Plier et servir.',
    ],
  },
  {
    id: 'super-47',
    name: 'Couscous Végétarien',
    image: 'https://images.unsplash.com/photo-1645696329654-2a609cbea1f6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Semoule', quantity: '500g' },
      { item: 'Légumes variés', quantity: '1kg' },
      { item: 'Pois chiches', quantity: '400g' },
      { item: 'Harissa', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Faire revenir les légumes.',
      'Ajouter pois chiches et épices.',
      'Cuire dans du bouillon.',
      'Préparer la semoule.',
    ],
  },
  {
    id: 'super-48',
    name: 'Gâteau Basque',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 40,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '400g' },
      { item: 'Beurre', quantity: '250g' },
      { item: 'Sucre', quantity: '200g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Crème pâtissière', quantity: '300g' },
    ],
    steps: [
      'Préparer la pâte.',
      'Étaler les 2/3 dans un moule.',
      'Garnir de crème pâtissière.',
      'Recouvrir avec le reste de pâte.',
      'Cuire 40 min à 180°C.',
    ],
  },
  {
    id: 'super-49',
    name: 'Soufflé au Fromage',
    image: 'https://images.unsplash.com/photo-1732969331543-80e52902e0a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Difficile',
    category: 'Français',
    ingredients: [
      { item: 'Œufs', quantity: '6' },
      { item: 'Gruyère', quantity: '150g' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Farine', quantity: '50g' },
      { item: 'Lait', quantity: '300ml' },
    ],
    steps: [
      'Préparer une béchamel.',
      'Incorporer jaunes et fromage.',
      'Monter les blancs en neige.',
      'Les incorporer délicatement.',
      'Cuire 25 min à 200°C.',
    ],
  },
  {
    id: 'super-50',
    name: 'Onigiri Japonais',
    image: 'https://images.unsplash.com/photo-1625937751876-4515cd8e78bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 20,
    servings: 8,
    difficulty: 'Facile',
    category: 'Japonais',
    ingredients: [
      { item: 'Riz japonais', quantity: '400g' },
      { item: 'Algue nori', quantity: '4 feuilles' },
      { item: 'Saumon', quantity: '200g' },
      { item: 'Vinaigre de riz', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Cuire le riz.',
      'L\'assaisonner au vinaigre.',
      'Former des triangles.',
      'Garnir de saumon.',
      'Entourer d\'algue.',
    ],
  },
  // Encore 50 autres...
  {
    id: 'super-51',
    name: 'Poêlée Asiatique',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Légumes variés', quantity: '600g' },
      { item: 'Sauce soja', quantity: '4 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Ail', quantity: '2 gousses' },
    ],
    steps: [
      'Faire sauter ail et gingembre.',
      'Ajouter les légumes.',
      'Cuire à feu vif.',
      'Assaisonner de sauce soja.',
    ],
  },
  {
    id: 'super-52',
    name: 'Madeleine de Commercy',
    image: 'https://images.unsplash.com/photo-1571506165871-ee72a35bc9d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '200g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Beurre', quantity: '150g' },
      { item: 'Levure', quantity: '1 sachet' },
    ],
    steps: [
      'Mélanger œufs et sucre.',
      'Incorporer farine et levure.',
      'Ajouter beurre fondu.',
      'Verser dans moules.',
      'Cuire 12 min à 200°C.',
    ],
  },
  {
    id: 'super-53',
    name: 'Tourte Lorraine',
    image: 'https://images.unsplash.com/photo-1650844010413-3f24dc1c182b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 45,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Pâte feuilletée', quantity: '2' },
      { item: 'Porc', quantity: '400g' },
      { item: 'Veau', quantity: '200g' },
      { item: 'Échalotes', quantity: '3' },
      { item: 'Vin blanc', quantity: '100ml' },
    ],
    steps: [
      'Faire mariner les viandes.',
      'Garnir une pâte.',
      'Recouvrir de l\'autre pâte.',
      'Cuire 45 min à 180°C.',
    ],
  },
  {
    id: 'super-54',
    name: 'Congee Chinois',
    image: 'https://images.unsplash.com/photo-1625189657893-f8fd7b45a901?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 60,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Riz', quantity: '200g' },
      { item: 'Bouillon', quantity: '1.5L' },
      { item: 'Poulet', quantity: '200g' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Oignons verts', quantity: '3' },
    ],
    steps: [
      'Cuire le riz dans le bouillon.',
      'Ajouter poulet et gingembre.',
      'Mijoter 50 min.',
      'Garnir d\'oignons verts.',
    ],
  },
  {
    id: 'super-55',
    name: 'Clafoutis Cerises',
    image: 'https://images.unsplash.com/photo-1565695472822-c7ba1e11c5c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 40,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Cerises', quantity: '600g' },
      { item: 'Farine', quantity: '100g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Lait', quantity: '300ml' },
      { item: 'Sucre', quantity: '100g' },
    ],
    steps: [
      'Disposer les cerises.',
      'Mélanger tous les autres ingrédients.',
      'Verser sur les cerises.',
      'Cuire 40 min à 180°C.',
    ],
  },
  {
    id: 'super-56',
    name: 'Banh Mi Vietnamien',
    image: 'https://images.unsplash.com/photo-1626200419455-0348c232b193?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Baguette', quantity: '4' },
      { item: 'Porc', quantity: '300g' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Coriandre', quantity: '1 bouquet' },
    ],
    steps: [
      'Griller le porc.',
      'Préparer les légumes marinés.',
      'Garnir les baguettes.',
      'Ajouter sauce et coriandre.',
    ],
  },
  {
    id: 'super-57',
    name: 'Far Breton',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 45,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '150g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Lait', quantity: '500ml' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Pruneaux', quantity: '200g' },
    ],
    steps: [
      'Mélanger tous les ingrédients.',
      'Ajouter les pruneaux.',
      'Verser dans un moule.',
      'Cuire 45 min à 180°C.',
    ],
  },
  {
    id: 'super-58',
    name: 'Salade Thaï au Bœuf',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 10,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Bœuf', quantity: '400g' },
      { item: 'Salade', quantity: '200g' },
      { item: 'Menthe', quantity: '1 bouquet' },
      { item: 'Cacahuètes', quantity: '100g' },
      { item: 'Sauce de poisson', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Griller le bœuf.',
      'Trancher finement.',
      'Mélanger avec salade et herbes.',
      'Assaisonner de sauce.',
    ],
  },
  {
    id: 'super-59',
    name: 'Tarte Feuilletée Tomate',
    image: 'https://images.unsplash.com/photo-1627308595232-d0cd54b31a4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 6,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Pâte feuilletée', quantity: '1' },
      { item: 'Tomates', quantity: '6' },
      { item: 'Moutarde', quantity: '3 c. à soupe' },
      { item: 'Herbes', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Étaler la pâte.',
      'Badigeonner de moutarde.',
      'Disposer les tomates.',
      'Cuire 25 min à 200°C.',
    ],
  },
  {
    id: 'super-60',
    name: 'Kouign-Amann',
    image: 'https://images.unsplash.com/photo-1618667060775-1fe102237f94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 180,
    cookTime: 30,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '500g' },
      { item: 'Beurre', quantity: '300g' },
      { item: 'Sucre', quantity: '250g' },
      { item: 'Levure', quantity: '15g' },
    ],
    steps: [
      'Préparer une pâte levée feuilletée.',
      'Incorporer beurre et sucre par pliages.',
      'Former des gâteaux individuels.',
      'Cuire 30 min à 200°C.',
    ],
  },
  {
    id: 'super-61',
    name: 'Soupe Miso',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Japonais',
    ingredients: [
      { item: 'Miso', quantity: '4 c. à soupe' },
      { item: 'Tofu', quantity: '200g' },
      { item: 'Algues', quantity: '20g' },
      { item: 'Bouillon dashi', quantity: '1L' },
    ],
    steps: [
      'Chauffer le bouillon.',
      'Diluer le miso.',
      'Ajouter tofu et algues.',
      'Servir immédiatement.',
    ],
  },
  {
    id: 'super-62',
    name: 'Lasagnes Bolognaise',
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 50,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes lasagne', quantity: '16' },
      { item: 'Viande hachée', quantity: '800g' },
      { item: 'Sauce tomate', quantity: '800g' },
      { item: 'Béchamel', quantity: '800ml' },
      { item: 'Parmesan', quantity: '200g' },
    ],
    steps: [
      'Préparer la bolognaise.',
      'Alterner pâtes, bolognaise et béchamel.',
      'Terminer par béchamel et parmesan.',
      'Cuire 45 min à 180°C.',
    ],
  },
  {
    id: 'super-63',
    name: 'Spring Rolls',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Galettes de riz', quantity: '16' },
      { item: 'Crevettes', quantity: '300g' },
      { item: 'Vermicelles', quantity: '100g' },
      { item: 'Carottes', quantity: '2' },
      { item: 'Menthe', quantity: '1 bouquet' },
    ],
    steps: [
      'Cuire crevettes et vermicelles.',
      'Humidifier les galettes.',
      'Garnir et rouler.',
      'Servir avec sauce.',
    ],
  },
  {
    id: 'super-64',
    name: 'Opéra',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 120,
    cookTime: 10,
    servings: 12,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Biscuit joconde', quantity: '3' },
      { item: 'Ganache chocolat', quantity: '400g' },
      { item: 'Crème au beurre café', quantity: '300g' },
      { item: 'Sirop café', quantity: '200ml' },
      { item: 'Glaçage chocolat', quantity: '200g' },
    ],
    steps: [
      'Préparer tous les éléments.',
      'Monter en superposant.',
      'Glacer au chocolat.',
      'Réfrigérer 4h.',
    ],
  },
  {
    id: 'super-65',
    name: 'Pho Bœuf',
    image: 'https://images.unsplash.com/photo-1625189657893-f8fd7b45a901?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 120,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Vietnamien',
    ingredients: [
      { item: 'Bœuf', quantity: '800g' },
      { item: 'Nouilles de riz', quantity: '400g' },
      { item: 'Bouillon', quantity: '2L' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Anis étoilé', quantity: '3' },
    ],
    steps: [
      'Préparer un bouillon épicé 2h.',
      'Cuire les nouilles.',
      'Trancher le bœuf.',
      'Assembler et verser bouillon.',
    ],
  },
  {
    id: 'super-66',
    name: 'Sabayon',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Jaunes d\'œufs', quantity: '6' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Vin blanc', quantity: '100ml' },
    ],
    steps: [
      'Battre jaunes et sucre.',
      'Ajouter le vin.',
      'Cuire au bain-marie en fouettant.',
      'Servir tiède.',
    ],
  },
  {
    id: 'super-67',
    name: 'Arancini Siciliens',
    image: 'https://images.unsplash.com/photo-1476124369491-f117991cdc65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 45,
    cookTime: 30,
    servings: 12,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Risotto', quantity: '600g' },
      { item: 'Mozzarella', quantity: '200g' },
      { item: 'Chapelure', quantity: '200g' },
      { item: 'Œufs', quantity: '2' },
    ],
    steps: [
      'Préparer un risotto et laisser refroidir.',
      'Former des boules avec mozzarella au centre.',
      'Paner et frire.',
    ],
  },
  {
    id: 'super-68',
    name: 'Soupe Harira',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 60,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Maghrébin',
    ingredients: [
      { item: 'Agneau', quantity: '400g' },
      { item: 'Pois chiches', quantity: '300g' },
      { item: 'Lentilles', quantity: '200g' },
      { item: 'Tomates', quantity: '400g' },
      { item: 'Épices', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Faire revenir l\'agneau.',
      'Ajouter légumineuses et tomates.',
      'Couvrir d\'eau et épices.',
      'Mijoter 50 min.',
    ],
  },
  {
    id: 'super-69',
    name: 'Charlotte aux Fraises',
    image: 'https://images.unsplash.com/photo-1560529666-317819712619?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 0,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Biscuits cuillère', quantity: '30' },
      { item: 'Fraises', quantity: '800g' },
      { item: 'Crème chantilly', quantity: '500ml' },
      { item: 'Sucre', quantity: '100g' },
    ],
    steps: [
      'Tapisser un moule de biscuits.',
      'Préparer une mousse aux fraises.',
      'Garnir le moule.',
      'Réfrigérer 4h.',
    ],
  },
  {
    id: 'super-70',
    name: 'Udon Sauté',
    image: 'https://images.unsplash.com/photo-1718964313403-2db158f67844?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Japonais',
    ingredients: [
      { item: 'Nouilles udon', quantity: '400g' },
      { item: 'Légumes', quantity: '400g' },
      { item: 'Sauce soja', quantity: '4 c. à soupe' },
      { item: 'Huile de sésame', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Cuire les udon.',
      'Faire sauter les légumes.',
      'Ajouter nouilles et sauces.',
      'Servir chaud.',
    ],
  },
  {
    id: 'super-71',
    name: 'Poires Belle Hélène',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Poires', quantity: '4' },
      { item: 'Glace vanille', quantity: '400ml' },
      { item: 'Chocolat noir', quantity: '200g' },
      { item: 'Crème', quantity: '100ml' },
      { item: 'Sucre', quantity: '100g' },
    ],
    steps: [
      'Pocher les poires au sirop.',
      'Préparer une sauce chocolat.',
      'Dresser poires et glace.',
      'Napper de sauce chocolat.',
    ],
  },
  {
    id: 'super-72',
    name: 'Focaccia Italienne',
    image: 'https://images.unsplash.com/photo-1630230596557-ad07b433f5c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 120,
    cookTime: 25,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Farine', quantity: '500g' },
      { item: 'Levure', quantity: '15g' },
      { item: 'Huile d\'olive', quantity: '100ml' },
      { item: 'Romarin', quantity: '2 branches' },
      { item: 'Fleur de sel', quantity: 'Au goût' },
    ],
    steps: [
      'Préparer une pâte levée.',
      'Laisser lever 1h30.',
      'Étaler et faire des trous.',
      'Arroser d\'huile, romarin et sel.',
      'Cuire 25 min à 200°C.',
    ],
  },
  {
    id: 'super-73',
    name: 'Beignets de Carnaval',
    image: 'https://images.unsplash.com/photo-1619546952812-16f4c7b0fd6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 90,
    cookTime: 20,
    servings: 20,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '500g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Lait', quantity: '200ml' },
      { item: 'Levure', quantity: '15g' },
      { item: 'Sucre glace', quantity: '100g' },
    ],
    steps: [
      'Préparer une pâte levée.',
      'Laisser lever 1h.',
      'Former des beignets.',
      'Frire dans l\'huile chaude.',
      'Saupoudrer de sucre glace.',
    ],
  },
  {
    id: 'super-74',
    name: 'Salade de Fruits Exotiques',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 0,
    servings: 6,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Ananas', quantity: '1' },
      { item: 'Mangue', quantity: '2' },
      { item: 'Fruit de la passion', quantity: '4' },
      { item: 'Litchis', quantity: '200g' },
      { item: 'Menthe', quantity: '1 bouquet' },
    ],
    steps: [
      'Couper tous les fruits.',
      'Mélanger délicatement.',
      'Ajouter menthe ciselée.',
      'Réfrigérer avant de servir.',
    ],
  },
  {
    id: 'super-75',
    name: 'Rösti Suisse',
    image: 'https://images.unsplash.com/photo-1753289595628-e3732ce60039?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Suisse',
    ingredients: [
      { item: 'Pommes de terre', quantity: '1kg' },
      { item: 'Beurre', quantity: '80g' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Sel', quantity: 'Au goût' },
    ],
    steps: [
      'Râper les pommes de terre.',
      'Presser pour retirer l\'eau.',
      'Faire dorer dans le beurre.',
      'Former une galette.',
      'Cuire 10 min de chaque côté.',
    ],
  },
  {
    id: 'super-76',
    name: 'Crème Caramel',
    image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Lait', quantity: '500ml' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Vanille', quantity: '1 gousse' },
    ],
    steps: [
      'Préparer un caramel.',
      'Battre œufs et sucre.',
      'Ajouter lait vanillé.',
      'Verser dans des ramequins caramélisés.',
      'Cuire au bain-marie 40 min.',
    ],
  },
  {
    id: 'super-77',
    name: 'Carbonara Authentique',
    image: 'https://images.unsplash.com/photo-1588013273468-315fd88ea34c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Spaghetti', quantity: '400g' },
      { item: 'Guanciale', quantity: '150g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Pecorino', quantity: '100g' },
      { item: 'Poivre', quantity: 'Au goût' },
    ],
    steps: [
      'Cuire les pâtes.',
      'Faire revenir le guanciale.',
      'Battre œufs et pecorino.',
      'Mélanger pâtes, guanciale et œufs.',
      'Poivrer généreusement.',
    ],
  },
  {
    id: 'super-78',
    name: 'Velouté de Potimarron',
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: 'Facile',
    category: 'Soupe',
    ingredients: [
      { item: 'Potimarron', quantity: '1kg' },
      { item: 'Bouillon', quantity: '1L' },
      { item: 'Crème', quantity: '150ml' },
      { item: 'Muscade', quantity: '1 pincée' },
    ],
    steps: [
      'Couper et cuire le potimarron.',
      'Mixer avec le bouillon.',
      'Ajouter crème et muscade.',
      'Servir chaud.',
    ],
  },
  {
    id: 'super-79',
    name: 'Pizza Calzone',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 90,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pâte à pizza', quantity: '1' },
      { item: 'Jambon', quantity: '200g' },
      { item: 'Mozzarella', quantity: '200g' },
      { item: 'Ricotta', quantity: '150g' },
      { item: 'Sauce tomate', quantity: '200g' },
    ],
    steps: [
      'Garnir la moitié de la pâte.',
      'Plier en chausson.',
      'Souder les bords.',
      'Cuire au four 15 min à 250°C.',
    ],
  },
  {
    id: 'super-80',
    name: 'Chocolat Liégeois',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Glace chocolat', quantity: '400ml' },
      { item: 'Crème chantilly', quantity: '200ml' },
      { item: 'Chocolat', quantity: '100g' },
      { item: 'Copeaux de chocolat', quantity: '50g' },
    ],
    steps: [
      'Disposer la glace dans des verres.',
      'Ajouter la chantilly.',
      'Parsemer de copeaux de chocolat.',
    ],
  },
  {
    id: 'super-81',
    name: 'Coq au Riesling',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 75,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Poulet', quantity: '1.5kg' },
      { item: 'Riesling', quantity: '500ml' },
      { item: 'Champignons', quantity: '300g' },
      { item: 'Crème', quantity: '200ml' },
      { item: 'Lardons', quantity: '150g' },
    ],
    steps: [
      'Faire dorer le poulet.',
      'Ajouter lardons et champignons.',
      'Mouiller au riesling.',
      'Mijoter 1h.',
      'Lier à la crème.',
    ],
  },
  {
    id: 'super-82',
    name: 'Streusel aux Pommes',
    image: 'https://images.unsplash.com/photo-1706799419621-14d7f424de83?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 35,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte sablée', quantity: '1' },
      { item: 'Pommes', quantity: '6' },
      { item: 'Farine', quantity: '150g' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Cannelle', quantity: '1 c. à café' },
    ],
    steps: [
      'Disposer pommes sur la pâte.',
      'Préparer un crumble.',
      'Répartir sur les pommes.',
      'Cuire 35 min à 180°C.',
    ],
  },
  {
    id: 'super-83',
    name: 'Salade Caprese',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Tomates', quantity: '4' },
      { item: 'Mozzarella', quantity: '250g' },
      { item: 'Basilic', quantity: '1 bouquet' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
    ],
    steps: [
      'Trancher tomates et mozzarella.',
      'Alterner sur un plat.',
      'Ajouter basilic.',
      'Arroser d\'huile d\'olive.',
    ],
  },
  {
    id: 'super-84',
    name: 'Yakitori Japonais',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Japonais',
    ingredients: [
      { item: 'Poulet', quantity: '600g' },
      { item: 'Sauce soja', quantity: '100ml' },
      { item: 'Mirin', quantity: '50ml' },
      { item: 'Sucre', quantity: '2 c. à soupe' },
      { item: 'Oignons verts', quantity: '6' },
    ],
    steps: [
      'Couper poulet en morceaux.',
      'Enfiler sur brochettes avec oignons.',
      'Préparer sauce yakitori.',
      'Griller en badigeonnant.',
    ],
  },
  {
    id: 'super-85',
    name: 'Forêt Noire',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 90,
    cookTime: 30,
    servings: 12,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Génoise chocolat', quantity: '3' },
      { item: 'Cerises', quantity: '600g' },
      { item: 'Chantilly', quantity: '800ml' },
      { item: 'Kirsch', quantity: '100ml' },
      { item: 'Copeaux chocolat', quantity: '100g' },
    ],
    steps: [
      'Imbiber les génoises de kirsch.',
      'Monter avec chantilly et cerises.',
      'Recouvrir de chantilly.',
      'Décorer de copeaux de chocolat.',
    ],
  },
  {
    id: 'super-86',
    name: 'Roulés de Poulet Épinards',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 35,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Volaille',
    ingredients: [
      { item: 'Escalopes poulet', quantity: '4' },
      { item: 'Épinards', quantity: '300g' },
      { item: 'Ricotta', quantity: '200g' },
      { item: 'Parmesan', quantity: '80g' },
      { item: 'Tomates', quantity: '400g' },
    ],
    steps: [
      'Mélanger épinards et ricotta.',
      'Garnir les escalopes.',
      'Rouler et ficeler.',
      'Cuire dans sauce tomate 30 min.',
    ],
  },
  {
    id: 'super-87',
    name: 'Muffins Chocolat Banane',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 12,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '300g' },
      { item: 'Bananes', quantity: '3' },
      { item: 'Chocolat', quantity: '150g' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Sucre', quantity: '120g' },
    ],
    steps: [
      'Écraser les bananes.',
      'Mélanger tous les ingrédients.',
      'Verser dans moules.',
      'Cuire 20 min à 180°C.',
    ],
  },
  {
    id: 'super-88',
    name: 'Salade de Betteraves',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Betteraves cuites', quantity: '500g' },
      { item: 'Chèvre', quantity: '150g' },
      { item: 'Noix', quantity: '80g' },
      { item: 'Mâche', quantity: '100g' },
      { item: 'Vinaigrette', quantity: '6 c. à soupe' },
    ],
    steps: [
      'Couper les betteraves.',
      'Mélanger avec mâche.',
      'Ajouter chèvre et noix.',
      'Assaisonner.',
    ],
  },
  {
    id: 'super-89',
    name: 'Gâteau au Yaourt',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 30,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Yaourt', quantity: '1 pot' },
      { item: 'Sucre', quantity: '2 pots' },
      { item: 'Farine', quantity: '3 pots' },
      { item: 'Huile', quantity: '1 pot' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Levure', quantity: '1 sachet' },
    ],
    steps: [
      'Mélanger tous les ingrédients.',
      'Verser dans un moule.',
      'Cuire 30 min à 180°C.',
    ],
  },
  {
    id: 'super-90',
    name: 'Gratin de Fruits de Mer',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 25,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Poisson',
    ingredients: [
      { item: 'Fruits de mer', quantity: '800g' },
      { item: 'Béchamel', quantity: '600ml' },
      { item: 'Gruyère', quantity: '150g' },
      { item: 'Vin blanc', quantity: '100ml' },
    ],
    steps: [
      'Faire revenir les fruits de mer au vin blanc.',
      'Disposer dans un plat.',
      'Napper de béchamel.',
      'Parsemer de gruyère.',
      'Gratiner 20 min.',
    ],
  },
  {
    id: 'super-91',
    name: 'Croque-Cake',
    image: 'https://images.unsplash.com/photo-1531664412848-9610afed156c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 45,
    servings: 8,
    difficulty: 'Facile',
    category: 'Apéritif',
    ingredients: [
      { item: 'Farine', quantity: '200g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Lait', quantity: '100ml' },
      { item: 'Jambon', quantity: '200g' },
      { item: 'Gruyère', quantity: '150g' },
    ],
    steps: [
      'Mélanger farine, œufs et lait.',
      'Ajouter jambon et gruyère.',
      'Verser dans un moule à cake.',
      'Cuire 45 min à 180°C.',
    ],
  },
  {
    id: 'super-92',
    name: 'Smoothie Bowl',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: 'Facile',
    category: 'Brunch',
    ingredients: [
      { item: 'Bananes', quantity: '3' },
      { item: 'Fruits rouges', quantity: '200g' },
      { item: 'Yaourt', quantity: '200g' },
      { item: 'Granola', quantity: '100g' },
      { item: 'Miel', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Mixer bananes, fruits et yaourt.',
      'Verser dans des bols.',
      'Garnir de granola et fruits.',
      'Arroser de miel.',
    ],
  },
  {
    id: 'super-93',
    name: 'Saint-Honoré',
    image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 120,
    cookTime: 30,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte feuilletée', quantity: '1' },
      { item: 'Pâte à choux', quantity: '300g' },
      { item: 'Crème chiboust', quantity: '500g' },
      { item: 'Caramel', quantity: '200g' },
    ],
    steps: [
      'Cuire le fond feuilleté.',
      'Préparer des petits choux.',
      'Les caraméliser.',
      'Garnir de crème chiboust.',
      'Assembler le tout.',
    ],
  },
  {
    id: 'super-94',
    name: 'Tajine de Poulet aux Olives',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 60,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Maghrébin',
    ingredients: [
      { item: 'Poulet', quantity: '1.5kg' },
      { item: 'Olives', quantity: '200g' },
      { item: 'Citrons confits', quantity: '2' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Épices', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Faire revenir le poulet.',
      'Ajouter oignons et épices.',
      'Incorporer olives et citrons.',
      'Mijoter 1h.',
    ],
  },
  {
    id: 'super-95',
    name: 'Smoothie Vert Détox',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: 'Facile',
    category: 'Brunch',
    ingredients: [
      { item: 'Épinards', quantity: '100g' },
      { item: 'Banane', quantity: '2' },
      { item: 'Pomme verte', quantity: '1' },
      { item: 'Concombre', quantity: '1/2' },
      { item: 'Citron', quantity: '1/2' },
    ],
    steps: [
      'Mixer tous les ingrédients.',
      'Ajouter de l\'eau si nécessaire.',
      'Servir frais.',
    ],
  },
  {
    id: 'super-96',
    name: 'Tatin d\'Endives',
    image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Végétarien',
    ingredients: [
      { item: 'Endives', quantity: '8' },
      { item: 'Pâte feuilletée', quantity: '1' },
      { item: 'Sucre', quantity: '80g' },
      { item: 'Beurre', quantity: '50g' },
      { item: 'Vinaigre balsamique', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Caraméliser endives avec sucre et beurre.',
      'Ajouter vinaigre balsamique.',
      'Couvrir de pâte.',
      'Cuire 30 min à 180°C.',
      'Démouler à l\'envers.',
    ],
  },
  {
    id: 'super-97',
    name: 'Cacik Turc',
    image: 'https://images.unsplash.com/photo-1604908815541-ae5e2b7e4c2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: 'Facile',
    category: 'Turc',
    ingredients: [
      { item: 'Yaourt grec', quantity: '500g' },
      { item: 'Concombre', quantity: '2' },
      { item: 'Ail', quantity: '3 gousses' },
      { item: 'Menthe', quantity: '1 bouquet' },
      { item: 'Huile d\'olive', quantity: '3 c. à soupe' },
    ],
    steps: [
      'Râper les concombres.',
      'Mélanger avec yaourt et ail.',
      'Ajouter menthe ciselée.',
      'Arroser d\'huile d\'olive.',
    ],
  },
  {
    id: 'super-98',
    name: 'Bugnes Lyonnaises',
    image: 'https://images.unsplash.com/photo-1619546952812-16f4c7b0fd6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 90,
    cookTime: 20,
    servings: 30,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '500g' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Sucre', quantity: '80g' },
      { item: 'Rhum', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Préparer une pâte.',
      'Laisser reposer 1h.',
      'Former des bugnes.',
      'Frire dans l\'huile.',
      'Saupoudrer de sucre glace.',
    ],
  },
  {
    id: 'super-99',
    name: 'Pâtes Amatriciana',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Pâtes', quantity: '400g' },
      { item: 'Guanciale', quantity: '150g' },
      { item: 'Tomates', quantity: '400g' },
      { item: 'Pecorino', quantity: '80g' },
      { item: 'Piment', quantity: '1' },
    ],
    steps: [
      'Faire revenir le guanciale.',
      'Ajouter tomates et piment.',
      'Cuire 15 min.',
      'Mélanger avec pâtes cuites.',
      'Parsemer de pecorino.',
    ],
  },
  {
    id: 'super-100',
    name: 'Vacherin Glacé',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 120,
    cookTime: 0,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Meringue', quantity: '200g' },
      { item: 'Glace vanille', quantity: '500ml' },
      { item: 'Glace fraise', quantity: '500ml' },
      { item: 'Chantilly', quantity: '300ml' },
      { item: 'Fruits rouges', quantity: '200g' },
    ],
    steps: [
      'Préparer un cercle de meringue.',
      'Garnir de glaces.',
      'Recouvrir de chantilly.',
      'Décorer de fruits.',
      'Congeler 2h.',
    ],
  },
];
