// Collection ULTIME de 50 recettes supplémentaires - Total Maximum !
import type { Recipe } from '../components/RecipesScreen';

export const ultimateRecipes: Recipe[] = [
  // ===== RECETTES ULTRA POPULAIRES =====
  {
    id: 'ultra-1',
    name: 'Croque Hawaïen',
    image: 'https://images.unsplash.com/photo-1531664412848-9610afed156c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Rapide',
    ingredients: [
      { item: 'Pain de mie', quantity: '8 tranches' },
      { item: 'Jambon', quantity: '4 tranches' },
      { item: 'Ananas', quantity: '8 rondelles' },
      { item: 'Gruyère', quantity: '200g' },
    ],
    steps: [
      'Disposer jambon et ananas sur le pain.',
      'Couvrir de gruyère.',
      'Gratiner au four 10 minutes.',
    ],
  },
  {
    id: 'ultra-2',
    name: 'Salade de Chèvre Chaud',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Salade mesclun', quantity: '200g' },
      { item: 'Fromage de chèvre', quantity: '200g' },
      { item: 'Pain', quantity: '8 tranches' },
      { item: 'Miel', quantity: '3 c. à soupe' },
      { item: 'Noix', quantity: '80g' },
    ],
    steps: [
      'Griller le pain.',
      'Disposer le chèvre dessus.',
      'Gratiner 5 minutes.',
      'Disposer sur la salade.',
      'Arroser de miel.',
    ],
  },
  {
    id: 'ultra-3',
    name: 'Osso-Bucco de Dinde',
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Volaille',
    ingredients: [
      { item: 'Jarret de dinde', quantity: '6 tranches' },
      { item: 'Tomates concassées', quantity: '400g' },
      { item: 'Vin blanc', quantity: '200ml' },
      { item: 'Carottes', quantity: '3' },
      { item: 'Bouillon', quantity: '500ml' },
    ],
    steps: [
      'Faire dorer les jarrets.',
      'Ajouter légumes.',
      'Déglacer au vin.',
      'Ajouter tomates et bouillon.',
      'Mijoter 1h30.',
    ],
  },
  {
    id: 'ultra-4',
    name: 'Poisson en Papillote',
    image: 'https://images.unsplash.com/photo-1707576517985-a2e912cca325?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Poisson',
    ingredients: [
      { item: 'Filets de poisson', quantity: '4' },
      { item: 'Légumes', quantity: '400g' },
      { item: 'Citron', quantity: '1' },
      { item: 'Herbes', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Disposer poisson et légumes sur papier.',
      'Arroser de citron.',
      'Parsemer d\'herbes.',
      'Fermer les papillotes.',
      'Cuire 20 min à 180°C.',
    ],
  },
  {
    id: 'ultra-5',
    name: 'Couscous Express',
    image: 'https://images.unsplash.com/photo-1645696329654-2a609cbea1f6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Facile',
    category: 'Maghrébin',
    ingredients: [
      { item: 'Semoule', quantity: '400g' },
      { item: 'Poulet', quantity: '400g' },
      { item: 'Légumes', quantity: '600g' },
      { item: 'Bouillon', quantity: '1L' },
      { item: 'Épices', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Faire revenir le poulet.',
      'Ajouter légumes et épices.',
      'Couvrir de bouillon.',
      'Mijoter 25 minutes.',
      'Préparer la semoule et servir.',
    ],
  },
  {
    id: 'ultra-6',
    name: 'Poke Bowl',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Riz', quantity: '300g' },
      { item: 'Saumon cru', quantity: '400g' },
      { item: 'Avocat', quantity: '2' },
      { item: 'Edamame', quantity: '150g' },
      { item: 'Sauce soja', quantity: '4 c. à soupe' },
      { item: 'Sésame', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Cuire le riz.',
      'Couper le saumon en dés.',
      'Préparer tous les accompagnements.',
      'Assembler dans des bols.',
      'Arroser de sauce soja.',
      'Parsemer de sésame.',
    ],
  },
  {
    id: 'ultra-7',
    name: 'Poulet Tandoori',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 120,
    cookTime: 30,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Indien',
    ingredients: [
      { item: 'Poulet', quantity: '800g' },
      { item: 'Yaourt', quantity: '200g' },
      { item: 'Tandoori masala', quantity: '3 c. à soupe' },
      { item: 'Citron', quantity: '2' },
      { item: 'Gingembre', quantity: '1 morceau' },
    ],
    steps: [
      'Mélanger yaourt, épices, citron et gingembre.',
      'Faire mariner le poulet 2h.',
      'Griller au four 30 minutes.',
      'Servir avec riz et naan.',
    ],
  },
  {
    id: 'ultra-8',
    name: 'Bœuf Wellington',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 35,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Fêtes',
    ingredients: [
      { item: 'Filet de bœuf', quantity: '1kg' },
      { item: 'Pâte feuilletée', quantity: '2' },
      { item: 'Duxelles de champignons', quantity: '300g' },
      { item: 'Foie gras', quantity: '150g' },
      { item: 'Jambon cru', quantity: '6 tranches' },
    ],
    steps: [
      'Saisir le filet.',
      'Envelopper de duxelles et jambon.',
      'Enrober de pâte feuilletée.',
      'Dorer au jaune d\'œuf.',
      'Cuire 35 min à 200°C.',
    ],
  },
  {
    id: 'ultra-9',
    name: 'Moussaka Grecque',
    image: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 60,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Grec',
    ingredients: [
      { item: 'Aubergines', quantity: '3' },
      { item: 'Viande hachée', quantity: '600g' },
      { item: 'Tomates', quantity: '400g' },
      { item: 'Béchamel', quantity: '600ml' },
      { item: 'Cannelle', quantity: '1 c. à café' },
    ],
    steps: [
      'Griller les aubergines.',
      'Faire revenir la viande avec tomates et cannelle.',
      'Alterner aubergines et viande.',
      'Napper de béchamel.',
      'Cuire 50 min à 180°C.',
    ],
  },
  {
    id: 'ultra-10',
    name: 'Tempura de Légumes',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Légumes variés', quantity: '600g' },
      { item: 'Farine', quantity: '150g' },
      { item: 'Eau gazeuse', quantity: '200ml' },
      { item: 'Œuf', quantity: '1' },
      { item: 'Huile de friture', quantity: '1L' },
    ],
    steps: [
      'Préparer la pâte avec farine, œuf et eau.',
      'Tremper les légumes.',
      'Frire dans l\'huile chaude.',
      'Égoutter.',
      'Servir avec sauce soja.',
    ],
  },
  {
    id: 'ultra-11',
    name: 'Salade Caprese',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Italien',
    ingredients: [
      { item: 'Tomates', quantity: '4' },
      { item: 'Mozzarella', quantity: '250g' },
      { item: 'Basilic', quantity: '1 bouquet' },
      { item: 'Huile d\'olive', quantity: '4 c. à soupe' },
      { item: 'Vinaigre balsamique', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Trancher tomates et mozzarella.',
      'Alterner sur un plat.',
      'Parsemer de basilic.',
      'Arroser d\'huile et vinaigre.',
    ],
  },
  {
    id: 'ultra-12',
    name: 'Soupe Tom Yum',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Crevettes', quantity: '400g' },
      { item: 'Champignons', quantity: '200g' },
      { item: 'Citronnelle', quantity: '2 tiges' },
      { item: 'Piment', quantity: '2' },
      { item: 'Lait de coco', quantity: '200ml' },
      { item: 'Bouillon', quantity: '1L' },
    ],
    steps: [
      'Faire bouillir le bouillon avec citronnelle.',
      'Ajouter champignons et piment.',
      'Incorporer les crevettes.',
      'Ajouter lait de coco.',
      'Servir avec coriandre.',
    ],
  },
  {
    id: 'ultra-13',
    name: 'Frites Maison',
    image: 'https://images.unsplash.com/photo-1579208570378-8c970854bc23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Facile',
    category: 'Accompagnement',
    ingredients: [
      { item: 'Pommes de terre', quantity: '1kg' },
      { item: 'Huile de friture', quantity: '2L' },
      { item: 'Sel', quantity: 'Au goût' },
    ],
    steps: [
      'Couper les pommes de terre en bâtonnets.',
      'Frire une première fois à 160°C.',
      'Égoutter et laisser reposer.',
      'Frire une seconde fois à 180°C.',
      'Saler et servir.',
    ],
  },
  {
    id: 'ultra-14',
    name: 'Carbonade Flamande',
    image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 120,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Belge',
    ingredients: [
      { item: 'Bœuf', quantity: '1kg' },
      { item: 'Bière brune', quantity: '500ml' },
      { item: 'Oignons', quantity: '4' },
      { item: 'Pain d\'épices', quantity: '2 tranches' },
      { item: 'Cassonade', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Faire dorer le bœuf.',
      'Faire revenir les oignons.',
      'Ajouter bière et pain d\'épices.',
      'Mijoter 2h à feu doux.',
      'Servir avec frites.',
    ],
  },
  {
    id: 'ultra-15',
    name: 'Ramen Miso',
    image: 'https://images.unsplash.com/photo-1625189657893-f8fd7b45a901?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 25,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Asiatique',
    ingredients: [
      { item: 'Nouilles ramen', quantity: '400g' },
      { item: 'Bouillon', quantity: '1.5L' },
      { item: 'Miso', quantity: '4 c. à soupe' },
      { item: 'Porc', quantity: '300g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Oignons verts', quantity: '3' },
    ],
    steps: [
      'Préparer le bouillon au miso.',
      'Cuire le porc.',
      'Cuire les œufs mollets.',
      'Cuire les nouilles.',
      'Assembler tous les éléments.',
    ],
  },
  {
    id: 'ultra-16',
    name: 'Gaufres Belges',
    image: 'https://images.unsplash.com/photo-1618667060775-1fe102237f94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '300g' },
      { item: 'Lait', quantity: '400ml' },
      { item: 'Œufs', quantity: '3' },
      { item: 'Beurre fondu', quantity: '100g' },
      { item: 'Sucre', quantity: '50g' },
      { item: 'Levure', quantity: '1 sachet' },
    ],
    steps: [
      'Mélanger tous les ingrédients.',
      'Laisser reposer 30 min.',
      'Cuire dans un gaufrier.',
      'Servir avec sucre glace ou chantilly.',
    ],
  },
  {
    id: 'ultra-17',
    name: 'Baba au Rhum',
    image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 25,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '250g' },
      { item: 'Œufs', quantity: '4' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Levure', quantity: '15g' },
      { item: 'Rhum', quantity: '100ml' },
      { item: 'Sucre', quantity: '200g' },
    ],
    steps: [
      'Préparer la pâte à baba.',
      'Faire lever 1h.',
      'Cuire dans des moules 20 min.',
      'Préparer un sirop au rhum.',
      'Imbiber les babas.',
    ],
  },
  {
    id: 'ultra-18',
    name: 'Tajine d\'Agneau',
    image: 'https://images.unsplash.com/photo-1692106914421-e04e1066bd62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 90,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Maghrébin',
    ingredients: [
      { item: 'Agneau', quantity: '1kg' },
      { item: 'Pruneaux', quantity: '200g' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Miel', quantity: '2 c. à soupe' },
      { item: 'Épices', quantity: '3 c. à soupe' },
      { item: 'Amandes', quantity: '100g' },
    ],
    steps: [
      'Faire revenir l\'agneau.',
      'Ajouter oignons et épices.',
      'Couvrir d\'eau.',
      'Mijoter 1h.',
      'Ajouter pruneaux et miel.',
      'Cuire encore 20 min.',
      'Parsemer d\'amandes grillées.',
    ],
  },
  {
    id: 'ultra-19',
    name: 'Sushi Rolls Maison',
    image: 'https://images.unsplash.com/photo-1625937751876-4515cd8e78bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 60,
    cookTime: 20,
    servings: 4,
    difficulty: 'Difficile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Riz à sushi', quantity: '400g' },
      { item: 'Saumon', quantity: '200g' },
      { item: 'Avocat', quantity: '2' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Algues nori', quantity: '10' },
      { item: 'Vinaigre de riz', quantity: '100ml' },
    ],
    steps: [
      'Cuire et assaisonner le riz.',
      'Préparer les garnitures.',
      'Étaler le riz sur les feuilles.',
      'Garnir et rouler.',
      'Trancher en morceaux.',
      'Servir avec sauce soja.',
    ],
  },
  {
    id: 'ultra-20',
    name: 'Ailes de Poulet BBQ',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    difficulty: 'Facile',
    category: 'Volaille',
    ingredients: [
      { item: 'Ailes de poulet', quantity: '1kg' },
      { item: 'Sauce BBQ', quantity: '250ml' },
      { item: 'Miel', quantity: '2 c. à soupe' },
      { item: 'Paprika', quantity: '1 c. à soupe' },
    ],
    steps: [
      'Mélanger sauce BBQ, miel et paprika.',
      'Enrober les ailes.',
      'Cuire au four 40 min à 200°C.',
      'Retourner à mi-cuisson.',
      'Servir chaud.',
    ],
  },
  {
    id: 'ultra-21',
    name: 'Verrines Avocat Crevettes',
    image: 'https://images.unsplash.com/photo-1604908815541-ae5e2b7e4c2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 0,
    servings: 6,
    difficulty: 'Facile',
    category: 'Apéritif',
    ingredients: [
      { item: 'Avocats', quantity: '3' },
      { item: 'Crevettes', quantity: '300g' },
      { item: 'Citron', quantity: '2' },
      { item: 'Crème fraîche', quantity: '100ml' },
      { item: 'Ciboulette', quantity: '1 bouquet' },
    ],
    steps: [
      'Préparer une crème d\'avocat.',
      'Disposer dans des verrines.',
      'Ajouter les crevettes.',
      'Arroser de jus de citron.',
      'Parsemer de ciboulette.',
    ],
  },
  {
    id: 'ultra-22',
    name: 'Lasagnes Saumon Épinards',
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 45,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Poisson',
    ingredients: [
      { item: 'Pâtes à lasagne', quantity: '12' },
      { item: 'Saumon', quantity: '600g' },
      { item: 'Épinards', quantity: '400g' },
      { item: 'Béchamel', quantity: '800ml' },
      { item: 'Parmesan', quantity: '100g' },
    ],
    steps: [
      'Cuire les épinards.',
      'Alterner pâtes, saumon, épinards et béchamel.',
      'Terminer par béchamel et parmesan.',
      'Cuire 45 min à 180°C.',
    ],
  },
  {
    id: 'ultra-23',
    name: 'Tartiflette Reblochon',
    image: 'https://images.unsplash.com/photo-1599046792003-e1e6c40b2e6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Pommes de terre', quantity: '1.5kg' },
      { item: 'Reblochon', quantity: '1' },
      { item: 'Lardons', quantity: '200g' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Vin blanc', quantity: '100ml' },
    ],
    steps: [
      'Cuire les pommes de terre.',
      'Faire revenir oignons et lardons.',
      'Alterner pommes de terre et lardons.',
      'Arroser de vin blanc.',
      'Couvrir de reblochon.',
      'Gratiner 30 min.',
    ],
  },
  {
    id: 'ultra-24',
    name: 'Donuts Maison',
    image: 'https://images.unsplash.com/photo-1619546952812-16f4c7b0fd6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 120,
    cookTime: 15,
    servings: 12,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '400g' },
      { item: 'Lait', quantity: '200ml' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Sucre', quantity: '80g' },
      { item: 'Levure', quantity: '15g' },
      { item: 'Glaçage', quantity: '200g' },
    ],
    steps: [
      'Préparer une pâte levée.',
      'Laisser lever 1h30.',
      'Former des donuts.',
      'Frire dans l\'huile chaude.',
      'Glacer et décorer.',
    ],
  },
  {
    id: 'ultra-25',
    name: 'Sauté de Veau Marengo',
    image: 'https://images.unsplash.com/photo-1733700469173-15d46efc2c09?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 90,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Français',
    ingredients: [
      { item: 'Veau', quantity: '1kg' },
      { item: 'Tomates', quantity: '400g' },
      { item: 'Champignons', quantity: '300g' },
      { item: 'Vin blanc', quantity: '200ml' },
      { item: 'Oignons', quantity: '2' },
    ],
    steps: [
      'Faire dorer le veau.',
      'Ajouter oignons et champignons.',
      'Déglacer au vin blanc.',
      'Ajouter les tomates.',
      'Mijoter 1h30.',
    ],
  },
  {
    id: 'ultra-26',
    name: 'Crêpes Suzette',
    image: 'https://images.unsplash.com/photo-1695518069327-60d7601794a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Crêpes', quantity: '12' },
      { item: 'Oranges', quantity: '4' },
      { item: 'Beurre', quantity: '100g' },
      { item: 'Sucre', quantity: '80g' },
      { item: 'Grand Marnier', quantity: '100ml' },
    ],
    steps: [
      'Préparer un beurre d\'orange.',
      'Plier les crêpes en quatre.',
      'Les faire réchauffer dans le beurre.',
      'Flamber au Grand Marnier.',
      'Servir chaud.',
    ],
  },
  {
    id: 'ultra-27',
    name: 'Tarte Tropézienne',
    image: 'https://images.unsplash.com/photo-1560529666-317819712619?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 40,
    cookTime: 25,
    servings: 8,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Brioche', quantity: '1' },
      { item: 'Crème pâtissière', quantity: '400ml' },
      { item: 'Crème au beurre', quantity: '300ml' },
      { item: 'Sucre grains', quantity: '50g' },
    ],
    steps: [
      'Préparer une brioche.',
      'La couper en deux.',
      'Mélanger crème pâtissière et crème au beurre.',
      'Garnir la brioche.',
      'Saupoudrer de sucre grains.',
    ],
  },
  {
    id: 'ultra-28',
    name: 'Bricks au Thon',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 10,
    servings: 6,
    difficulty: 'Facile',
    category: 'Maghrébin',
    ingredients: [
      { item: 'Feuilles de brick', quantity: '6' },
      { item: 'Thon', quantity: '200g' },
      { item: 'Œufs', quantity: '6' },
      { item: 'Câpres', quantity: '2 c. à soupe' },
      { item: 'Persil', quantity: '1 bouquet' },
    ],
    steps: [
      'Mélanger thon, câpres et persil.',
      'Disposer sur les feuilles.',
      'Casser un œuf au centre.',
      'Plier en triangle.',
      'Frire jusqu\'à dorure.',
    ],
  },
  {
    id: 'ultra-29',
    name: 'Poulet Basque',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 50,
    servings: 6,
    difficulty: 'Facile',
    category: 'Français',
    ingredients: [
      { item: 'Poulet', quantity: '1.2kg' },
      { item: 'Poivrons', quantity: '4' },
      { item: 'Tomates', quantity: '6' },
      { item: 'Oignons', quantity: '2' },
      { item: 'Piment', quantity: '1' },
    ],
    steps: [
      'Faire dorer le poulet.',
      'Ajouter légumes émincés.',
      'Mijoter 45 minutes.',
      'Servir avec du riz.',
    ],
  },
  {
    id: 'ultra-30',
    name: 'Gnocchis Maison',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 45,
    cookTime: 10,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Pommes de terre', quantity: '1kg' },
      { item: 'Farine', quantity: '300g' },
      { item: 'Œuf', quantity: '1' },
      { item: 'Parmesan', quantity: '50g' },
    ],
    steps: [
      'Cuire et écraser les pommes de terre.',
      'Mélanger avec farine et œuf.',
      'Former des gnocchis.',
      'Cuire dans l\'eau bouillante.',
      'Servir avec sauce.',
    ],
  },
  {
    id: 'ultra-31',
    name: 'Salade Waldorf',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: 'Facile',
    category: 'Salade',
    ingredients: [
      { item: 'Pommes', quantity: '3' },
      { item: 'Céleri', quantity: '3 branches' },
      { item: 'Noix', quantity: '100g' },
      { item: 'Raisins secs', quantity: '50g' },
      { item: 'Mayonnaise', quantity: '150ml' },
    ],
    steps: [
      'Couper pommes et céleri.',
      'Mélanger avec noix et raisins.',
      'Assaisonner de mayonnaise.',
      'Réfrigérer avant de servir.',
    ],
  },
  {
    id: 'ultra-32',
    name: 'Pavlova aux Fruits',
    image: 'https://images.unsplash.com/photo-1565695472822-c7ba1e11c5c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 90,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Blancs d\'œufs', quantity: '6' },
      { item: 'Sucre', quantity: '300g' },
      { item: 'Crème chantilly', quantity: '500ml' },
      { item: 'Fruits rouges', quantity: '400g' },
      { item: 'Vinaigre', quantity: '1 c. à café' },
    ],
    steps: [
      'Monter les blancs en neige.',
      'Incorporer sucre et vinaigre.',
      'Former un disque sur une plaque.',
      'Cuire 90 min à 120°C.',
      'Garnir de chantilly et fruits.',
    ],
  },
  {
    id: 'ultra-33',
    name: 'Porc au Caramel',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Porc', quantity: '600g' },
      { item: 'Sucre', quantity: '100g' },
      { item: 'Sauce soja', quantity: '4 c. à soupe' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Ail', quantity: '3 gousses' },
    ],
    steps: [
      'Faire un caramel avec le sucre.',
      'Ajouter sauce soja.',
      'Faire revenir le porc.',
      'Ajouter ail et gingembre.',
      'Mijoter 25 min.',
    ],
  },
  {
    id: 'ultra-34',
    name: 'Salade de Poulpe',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 45,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Poisson',
    ingredients: [
      { item: 'Poulpe', quantity: '800g' },
      { item: 'Pommes de terre', quantity: '400g' },
      { item: 'Citron', quantity: '2' },
      { item: 'Huile d\'olive', quantity: '100ml' },
      { item: 'Persil', quantity: '1 bouquet' },
    ],
    steps: [
      'Cuire le poulpe 40 min.',
      'Cuire les pommes de terre.',
      'Couper en morceaux.',
      'Assaisonner d\'huile et citron.',
      'Parsemer de persil.',
    ],
  },
  {
    id: 'ultra-35',
    name: 'Soupe Miso',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: 'Facile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Miso', quantity: '4 c. à soupe' },
      { item: 'Bouillon dashi', quantity: '1L' },
      { item: 'Tofu', quantity: '200g' },
      { item: 'Algues wakame', quantity: '20g' },
      { item: 'Oignons verts', quantity: '3' },
    ],
    steps: [
      'Faire chauffer le bouillon.',
      'Diluer le miso.',
      'Ajouter tofu et algues.',
      'Parsemer d\'oignons verts.',
      'Servir immédiatement.',
    ],
  },
  {
    id: 'ultra-36',
    name: 'Cannellonis Ricotta Épinards',
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 35,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Cannellonis', quantity: '20' },
      { item: 'Ricotta', quantity: '500g' },
      { item: 'Épinards', quantity: '400g' },
      { item: 'Sauce tomate', quantity: '600g' },
      { item: 'Parmesan', quantity: '100g' },
    ],
    steps: [
      'Mélanger ricotta et épinards.',
      'Farcir les cannellonis.',
      'Napper de sauce tomate.',
      'Parsemer de parmesan.',
      'Cuire 35 min à 180°C.',
    ],
  },
  {
    id: 'ultra-37',
    name: 'Chakchouka',
    image: 'https://images.unsplash.com/photo-1732969331543-80e52902e0a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'Facile',
    category: 'Maghrébin',
    ingredients: [
      { item: 'Tomates', quantity: '6' },
      { item: 'Poivrons', quantity: '3' },
      { item: 'Œufs', quantity: '6' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Cumin', quantity: '1 c. à café' },
    ],
    steps: [
      'Faire revenir oignon et poivrons.',
      'Ajouter tomates et cumin.',
      'Mijoter 15 min.',
      'Casser les œufs dessus.',
      'Couvrir et cuire jusqu\'à ce que les œufs soient pris.',
    ],
  },
  {
    id: 'ultra-38',
    name: 'Muffins aux Myrtilles',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 20,
    servings: 12,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '300g' },
      { item: 'Sucre', quantity: '150g' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Lait', quantity: '200ml' },
      { item: 'Myrtilles', quantity: '200g' },
      { item: 'Levure', quantity: '1 sachet' },
    ],
    steps: [
      'Mélanger tous les ingrédients secs.',
      'Incorporer œufs et lait.',
      'Ajouter les myrtilles.',
      'Verser dans des moules.',
      'Cuire 20 min à 180°C.',
    ],
  },
  {
    id: 'ultra-39',
    name: 'Bœuf Stroganoff',
    image: 'https://images.unsplash.com/photo-1664741662725-bd131742b7b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Russe',
    ingredients: [
      { item: 'Bœuf', quantity: '600g' },
      { item: 'Champignons', quantity: '300g' },
      { item: 'Oignon', quantity: '1' },
      { item: 'Crème fraîche', quantity: '250ml' },
      { item: 'Moutarde', quantity: '2 c. à soupe' },
    ],
    steps: [
      'Faire revenir le bœuf émincé.',
      'Ajouter oignon et champignons.',
      'Incorporer crème et moutarde.',
      'Mijoter 15 min.',
      'Servir avec riz ou pâtes.',
    ],
  },
  {
    id: 'ultra-40',
    name: 'Guacamole Mexicain',
    image: 'https://images.unsplash.com/photo-1604908815541-ae5e2b7e4c2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: 'Facile',
    category: 'Mexicain',
    ingredients: [
      { item: 'Avocats', quantity: '4' },
      { item: 'Tomates', quantity: '2' },
      { item: 'Oignon rouge', quantity: '1' },
      { item: 'Citron vert', quantity: '2' },
      { item: 'Coriandre', quantity: '1 bouquet' },
      { item: 'Piment', quantity: '1' },
    ],
    steps: [
      'Écraser les avocats.',
      'Concasser les tomates.',
      'Émincer oignon et piment.',
      'Mélanger avec jus de citron.',
      'Ajouter coriandre.',
      'Servir avec tortilla chips.',
    ],
  },
  {
    id: 'ultra-41',
    name: 'Tarte Bourdaloue',
    image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 40,
    servings: 8,
    difficulty: 'Moyen',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte sablée', quantity: '1' },
      { item: 'Poires', quantity: '6' },
      { item: 'Crème d\'amandes', quantity: '400g' },
      { item: 'Amandes effilées', quantity: '50g' },
    ],
    steps: [
      'Étaler la pâte dans un moule.',
      'Préparer la crème d\'amandes.',
      'Disposer les poires en éventail.',
      'Verser la crème d\'amandes.',
      'Parsemer d\'amandes.',
      'Cuire 40 min à 180°C.',
    ],
  },
  {
    id: 'ultra-42',
    name: 'Spaghetti alle Vongole',
    image: 'https://images.unsplash.com/photo-1563897539633-7a3d1b17371f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Spaghetti', quantity: '400g' },
      { item: 'Palourdes', quantity: '1kg' },
      { item: 'Vin blanc', quantity: '100ml' },
      { item: 'Ail', quantity: '4 gousses' },
      { item: 'Persil', quantity: '1 bouquet' },
      { item: 'Piment', quantity: '1' },
    ],
    steps: [
      'Faire ouvrir les palourdes au vin blanc.',
      'Cuire les spaghetti.',
      'Faire revenir ail et piment.',
      'Ajouter palourdes et leur jus.',
      'Mélanger avec les pâtes.',
      'Parsemer de persil.',
    ],
  },
  {
    id: 'ultra-43',
    name: 'Brochettes de Poulet Mariné',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 120,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Volaille',
    ingredients: [
      { item: 'Poulet', quantity: '800g' },
      { item: 'Yaourt', quantity: '150g' },
      { item: 'Citron', quantity: '2' },
      { item: 'Épices', quantity: '2 c. à soupe' },
      { item: 'Poivrons', quantity: '2' },
    ],
    steps: [
      'Faire mariner le poulet 2h.',
      'Enfiler sur des brochettes avec poivrons.',
      'Griller 15 minutes.',
      'Retourner régulièrement.',
      'Servir avec riz.',
    ],
  },
  {
    id: 'ultra-44',
    name: 'Millefeuille Vanille',
    image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 60,
    cookTime: 25,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte feuilletée', quantity: '500g' },
      { item: 'Crème pâtissière', quantity: '600ml' },
      { item: 'Sucre glace', quantity: '100g' },
      { item: 'Fondant', quantity: '200g' },
    ],
    steps: [
      'Cuire la pâte feuilletée.',
      'Découper en rectangles.',
      'Monter avec crème pâtissière.',
      'Glacer le dessus.',
      'Décorer.',
    ],
  },
  {
    id: 'ultra-45',
    name: 'Ceviche de Poisson',
    image: 'https://images.unsplash.com/photo-1580217593608-61931cefc821?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 0,
    servings: 4,
    difficulty: 'Moyen',
    category: 'Poisson',
    ingredients: [
      { item: 'Poisson blanc', quantity: '600g' },
      { item: 'Citron vert', quantity: '6' },
      { item: 'Oignon rouge', quantity: '1' },
      { item: 'Coriandre', quantity: '1 bouquet' },
      { item: 'Piment', quantity: '1' },
    ],
    steps: [
      'Couper le poisson en dés.',
      'Couvrir de jus de citron.',
      'Laisser mariner 20 min.',
      'Ajouter oignon, coriandre et piment.',
      'Servir frais.',
    ],
  },
  {
    id: 'ultra-46',
    name: 'Cookies Pépites Chocolat',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 15,
    cookTime: 12,
    servings: 20,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Farine', quantity: '250g' },
      { item: 'Beurre', quantity: '125g' },
      { item: 'Sucre roux', quantity: '150g' },
      { item: 'Œufs', quantity: '1' },
      { item: 'Pépites de chocolat', quantity: '200g' },
    ],
    steps: [
      'Mélanger beurre et sucre.',
      'Ajouter œuf puis farine.',
      'Incorporer les pépites.',
      'Former des boules.',
      'Cuire 12 min à 180°C.',
    ],
  },
  {
    id: 'ultra-47',
    name: 'Salade de Quinoa',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Facile',
    category: 'Végétarien',
    ingredients: [
      { item: 'Quinoa', quantity: '250g' },
      { item: 'Tomates cerises', quantity: '200g' },
      { item: 'Concombre', quantity: '1' },
      { item: 'Feta', quantity: '150g' },
      { item: 'Menthe', quantity: '1 bouquet' },
    ],
    steps: [
      'Cuire le quinoa.',
      'Laisser refroidir.',
      'Couper légumes et feta.',
      'Mélanger avec le quinoa.',
      'Assaisonner et ajouter menthe.',
    ],
  },
  {
    id: 'ultra-48',
    name: 'Poulet Cacciatore',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    difficulty: 'Moyen',
    category: 'Italien',
    ingredients: [
      { item: 'Poulet', quantity: '1.2kg' },
      { item: 'Tomates', quantity: '800g' },
      { item: 'Poivrons', quantity: '2' },
      { item: 'Champignons', quantity: '200g' },
      { item: 'Vin rouge', quantity: '150ml' },
      { item: 'Olives', quantity: '100g' },
    ],
    steps: [
      'Faire dorer le poulet.',
      'Ajouter légumes.',
      'Déglacer au vin rouge.',
      'Ajouter tomates et olives.',
      'Mijoter 40 min.',
    ],
  },
  {
    id: 'ultra-49',
    name: 'Tarte aux Pommes Alsacienne',
    image: 'https://images.unsplash.com/photo-1616953882462-8a583e0afbb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 25,
    cookTime: 40,
    servings: 8,
    difficulty: 'Facile',
    category: 'Dessert',
    ingredients: [
      { item: 'Pâte sablée', quantity: '1' },
      { item: 'Pommes', quantity: '6' },
      { item: 'Œufs', quantity: '2' },
      { item: 'Crème fraîche', quantity: '200ml' },
      { item: 'Sucre', quantity: '80g' },
      { item: 'Cannelle', quantity: '1 c. à café' },
    ],
    steps: [
      'Étaler la pâte dans un moule.',
      'Disposer les pommes tranchées.',
      'Mélanger œufs, crème et sucre.',
      'Verser sur les pommes.',
      'Saupoudrer de cannelle.',
      'Cuire 40 min à 180°C.',
    ],
  },
  {
    id: 'ultra-50',
    name: 'Soupe Pho Vietnamienne',
    image: 'https://images.unsplash.com/photo-1625189657893-f8fd7b45a901?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    prepTime: 30,
    cookTime: 120,
    servings: 6,
    difficulty: 'Difficile',
    category: 'Asiatique',
    ingredients: [
      { item: 'Bœuf', quantity: '800g' },
      { item: 'Nouilles de riz', quantity: '400g' },
      { item: 'Bouillon', quantity: '2L' },
      { item: 'Gingembre', quantity: '1 morceau' },
      { item: 'Anis étoilé', quantity: '3' },
      { item: 'Herbes fraîches', quantity: '1 bouquet' },
    ],
    steps: [
      'Préparer un bouillon avec les épices.',
      'Mijoter 2h.',
      'Cuire les nouilles.',
      'Trancher le bœuf finement.',
      'Assembler dans des bols.',
      'Verser le bouillon bouillant.',
      'Garnir d\'herbes fraîches.',
    ],
  },
];
